Repository mxsm/rocketmq-rust, pull requests merged in 2024-06, with the labels that each got.

#546 [ISSUE #545]🔧Update label-on-approval.yml
  .github/workflows/label-on-approval.yml
Labels: approved, auto merge

#548 [ISSUE #547]🔧Update automerge.yml
  .github/workflows/automerge.yml
Labels: approved, auto merge

#550 [ISSUE #549]🔧Update automerge.yml
  .github/workflows/automerge.yml
Labels: approved, auto merge

#556 [ISSUE #555]🔨Update label-on-approval.yml
  .github/workflows/label-on-approval.yml
Labels: approved, auto merge

#561 [ISSUE #560]🔧Update workflows config file
  .github/workflows/auto-comment-pr.yml
  .github/workflows/auto_request_review.yml
  .github/workflows/automerge.yml
Labels: approved, auto merge

#584 Update config file
  .github/workflows/label-on-approval.yml
Labels: approved, auto merge

#589 update config file
  .github/workflows/label-on-approval.yml
Labels: approved, auto merge

#594 Update automerge.yml
  .github/workflows/automerge.yml
Labels: approved

#596 Update automerge.yml
  .github/workflows/automerge.yml
Labels: approved

#595 Update auto-comment-pr.yml
  .github/workflows/auto-comment-pr.yml
Labels: approved, auto merge

#593 [ISSUE #592]Add doc for StatisticsItemScheduledPrinter struct
  rocketmq-common/src/common/statistics/statistics_item_scheduled_printer.rs
Labels: approved

#603 Update auto-comment-pr.yml
  .github/workflows/auto-comment-pr.yml
Labels: approved

#606 Update auto-comment-pr.yml
  .github/workflows/auto-comment-pr.yml
Labels: approved

#608 Update auto_request_review.yml
  .github/workflows/auto_request_review.yml
Labels: approved

#623 Delete .github/workflows/work_flow_watch.yml
  .github/workflows/work_flow_watch.yml
Labels: approved, auto merge

#612 Update Cargo.toml
  Cargo.toml
Labels: approved, auto merge

#626 Delete .github/workflows/label-on-approval.yml
  .github/workflows/label-on-approval.yml
Labels: approved, auto merge

#629 [ISSUE #627]🔧Optimize auto actions config
  .github/workflows/auto-comment-pr.yml
  .github/workflows/auto_request_review.yml
  .github/workflows/automerge.yml
Labels: approved, auto merge

#631 [ISSUE #630]✅Add test case for TopicConfigAndMappingSerializeWrapper
  rocketmq-common/src/common/config.rs
  rocketmq-remoting/src/protocol/body/topic_info_wrapper/topic_config_wrapper.rs
  rocketmq-remoting/src/protocol/static_topic/logic_queue_mapping_item.rs
  rocketmq-remoting/src/protocol/static_topic/topic_queue_info.rs
  rocketmq-remoting/src/protocol/static_topic/topic_queue_mapping_detail.rs
Labels: approved, auto merge

#632 [ISSUE #574] ✅Add test case for MessageQueue
  rocketmq-common/src/common/message/message_queue.rs
Labels: approved, auto merge

#634 [ISSUE #633]🔧 Add test template
  .github/ISSUE_TEMPLATE/unit_test.yml
Labels: approved, auto merge

#638 [ISSUE #637]✅ Add test case for TopicList
  rocketmq-remoting/src/protocol/body/topic/topic_list.rs
Labels: approved, auto merge

#640 [ISSUE #639]🔧Update auto actions token with PAT
  .github/workflows/auto-comment-pr.yml
  .github/workflows/automerge.yml
Labels: approved, auto merge

#642 [ISSUE #641]🎨Optimize ProducerManager#unregister_producer
  rocketmq-broker/src/client/manager/producer_manager.rs
Labels: approved, auto merge

#644 [ISSUE #643]🐛Fix topic_config_and_mapping_serialize_wrapper_default t…
  rocketmq-remoting/src/protocol/body/topic_info_wrapper/topic_config_wrapper.rs
Labels: approved, auto merge

#646 [ISSUE #645]🐛Fix test case topic_config_and_mapping_serialize_wrapper_getters error
  rocketmq-remoting/src/protocol/body/topic_info_wrapper/topic_config_wrapper.rs
Labels: approved, auto merge

#650 [ISSUE #649]✅Fix DataVersion test case for data_version_next_version error
  rocketmq-remoting/src/protocol.rs
Labels: approved, auto merge

#652 [ISSUE ##651]🚀Enhance the functionality of BrokerStatsManager-5
  rocketmq-broker/src/broker_runtime.rs
  rocketmq-broker/src/client/manager/consumer_manager.rs
  rocketmq-remoting/src/protocol/heartbeat.rs
  rocketmq-store/src/stats/broker_stats_manager.rs
Labels: approved, auto merge

#654 [ISSUE #653]🐛Fix Broker can not start
  rocketmq-store/src/stats/broker_stats_manager.rs
Labels: approved, auto merge

#657 [ISSUE ##656] 🎨Add ConsumeMessageContext struct and ConsumeMessageHook trait
  rocketmq-broker/src/mqtrace.rs
  rocketmq-broker/src/mqtrace/consume_message_context.rs
  rocketmq-broker/src/mqtrace/consume_message_hook.rs
Labels: approved, auto merge

#661 [ISSUE #660]🔧Update rustfmt.toml
  rustfmt.toml
Labels: approved, auto merge

#659 [ISSUE #658]🚀Support pull message consume
  rocketmq-broker/src/mqtrace/consume_message_hook.rs
  rocketmq-broker/src/processor.rs
  rocketmq-broker/src/processor/pull_message_processor.rs
  rocketmq-broker/src/processor/pull_message_result_handler.rs
  rocketmq-common/src/common/broker/broker_config.rs
  rocketmq-remoting/src/protocol.rs
  rocketmq-remoting/src/protocol/header.rs
  rocketmq-remoting/src/protocol/header/message_operation_header/send_message_response_header.rs
  rocketmq-remoting/src/protocol/header/namesrv/topic_operation_header.rs
  rocketmq-remoting/src/protocol/header/pull_message_request_header.rs
  rocketmq-remoting/src/protocol/header/pull_message_response_header.rs
  rocketmq-remoting/src/protocol/remoting_command.rs
  rocketmq-store/src/lib.rs
  rocketmq/src/lib.rs
Labels: approved, auto merge

#666 [ISSUE #665]🚀Implemention ConsumerGroupInfo struct
  rocketmq-broker/src/client.rs
  rocketmq-broker/src/client/consumer_group_info.rs
  rocketmq-remoting/src/protocol/heartbeat.rs
Labels: approved, auto merge

#668 [ISSUE #667]🍻Optimize socket connection
  Cargo.lock
  rocketmq-remoting/Cargo.toml
  rocketmq-remoting/src/connection.rs
  rocketmq-remoting/src/net.rs
  rocketmq-remoting/src/net/channel.rs
  rocketmq-remoting/src/runtime/server.rs
Labels: approved, auto merge

#677 [ISSUE #676]♻️Refactor RemotingCommand struct🚀
  rocketmq-broker/src/broker_runtime.rs
  rocketmq-broker/src/processor/pull_message_processor.rs
  rocketmq-broker/src/subscription/manager/subscription_group_manager.rs
  rocketmq-remoting/src/codec/remoting_command_codec.rs
  rocketmq-remoting/src/lib.rs
  rocketmq-remoting/src/protocol/remoting_command.rs
Labels: approved, auto merge

#679 [ISSUE #678]🚀Support rocketmq serialize type
  rocketmq-remoting/src/error.rs
  rocketmq-remoting/src/lib.rs
  rocketmq-remoting/src/protocol.rs
  rocketmq-remoting/src/protocol/command_custom_header.rs
  rocketmq-remoting/src/protocol/header/pull_message_request_header.rs
  rocketmq-remoting/src/protocol/remoting_command.rs
  rocketmq-remoting/src/protocol/rocketmq_serializable.rs
Labels: approved, auto merge

#681 [ISSUE #680]🐛Fix Broker can not start
  rocketmq-broker/src/broker_runtime.rs
  rocketmq-broker/src/processor.rs
  rocketmq-broker/src/processor/default_pull_message_result_handler.rs
  rocketmq-broker/src/processor/pull_message_processor.rs
Labels: approved, auto merge

#683 [ISSUE #682]🚀Optimize ResponseCode
  rocketmq-broker/src/out_api/broker_outer_api.rs
  rocketmq-remoting/src/code/response_code.rs
Labels: approved, auto merge

#685 [ISSUE #684]🎨Optimize RocketmqDefaultClient struct
  rocketmq-remoting/src/clients/rocketmq_default_impl.rs
Labels: approved, auto merge

#691 [ISSUE #323]🚀Support heart beat (requst code 34)-consumer
  rocketmq-broker/src/broker_runtime.rs
  rocketmq-broker/src/client/consumer_group_event.rs
  rocketmq-broker/src/client/consumer_group_info.rs
  rocketmq-broker/src/client/consumer_ids_change_listener.rs
  rocketmq-broker/src/client/default_consumer_ids_change_listener.rs
  rocketmq-broker/src/client/manager/consumer_manager.rs
  rocketmq-broker/src/processor.rs
  rocketmq-broker/src/processor/client_manage_processor.rs
  rocketmq-common/src/common/broker/broker_config.rs
  rocketmq-common/src/common/mix_all.rs
Labels: approved, auto merge

#697 [ISSUE #696]🚀Support pull message consume-5
  rocketmq-remoting/src/protocol/header/pull_message_request_header.rs
  rocketmq-store/src/base/select_result.rs
  rocketmq-store/src/consume_queue/consume_queue_ext.rs
  rocketmq-store/src/log_file/mapped_file/default_impl.rs
  rocketmq-store/src/message_store/default_message_store.rs
  rocketmq-store/src/queue.rs
  rocketmq-store/src/queue/batch_consume_queue.rs
  rocketmq-store/src/queue/consume_queue_ext.rs
  rocketmq-store/src/queue/single_consume_queue.rs
Labels: approved, auto merge

#700 [ISSUE #698]🚀Support UpdateConsumerOffset(15) request⚡️
  rocketmq-broker/src/broker_runtime.rs
  rocketmq-broker/src/offset/manager/consumer_offset_manager.rs
  rocketmq-broker/src/processor/consumer_manage_processor.rs
  rocketmq-broker/src/subscription/manager/subscription_group_manager.rs
  rocketmq-broker/src/topic/manager/topic_config_manager.rs
  rocketmq-common/src/common/broker/broker_config.rs
  rocketmq-remoting/src/protocol/body/topic_info_wrapper/topic_config_wrapper.rs
  rocketmq-remoting/src/protocol/header.rs
  rocketmq-remoting/src/protocol/header/update_consumer_offset_header.rs
Labels: approved, auto merge

#701 [ISSUE #699]🚀Support pull message result handle
  rocketmq-broker/src/broker_runtime.rs
  rocketmq-broker/src/offset/manager/broadcast_offset_manager.rs
  rocketmq-broker/src/processor/default_pull_message_result_handler.rs
  rocketmq-broker/src/processor/pull_message_processor.rs
  rocketmq-broker/src/topic/manager/topic_queue_mapping_manager.rs
  rocketmq-common/src/common/broker/broker_config.rs
  rocketmq-remoting/src/error.rs
  rocketmq-remoting/src/protocol/header/pull_message_response_header.rs
  rocketmq-remoting/src/protocol/remoting_command.rs
  rocketmq-remoting/src/protocol/static_topic.rs
  rocketmq-remoting/src/protocol/static_topic/logic_queue_mapping_item.rs
  rocketmq-remoting/src/protocol/static_topic/topic_queue_mapping_detail.rs
  rocketmq-remoting/src/protocol/static_topic/topic_queue_mapping_utils.rs
  rocketmq-remoting/src/rpc.rs
  rocketmq-remoting/src/rpc/rpc_client_utils.rs
  rocketmq-remoting/src/rpc/rpc_request.rs
  rocketmq-remoting/src/rpc/rpc_response.rs
Labels: approved, auto merge

#705 [ISSUE #704]🚀Add SerdeJsonUtils struct tool 🚀
  Cargo.lock
  rocketmq-common/Cargo.toml
  rocketmq-common/src/error.rs
  rocketmq-common/src/lib.rs
  rocketmq-common/src/utils/serde_json_utils.rs
Labels: approved, auto merge

#706 [ISSUE #702]🚀Support pull message result handle-2🚀
  rocketmq-broker/src/broker_runtime.rs
  rocketmq-broker/src/offset/manager/broadcast_offset_manager.rs
  rocketmq-broker/src/offset/manager/consumer_offset_manager.rs
  rocketmq-broker/src/processor/default_pull_message_result_handler.rs
  rocketmq-broker/src/processor/pull_message_processor.rs
  rocketmq-common/src/common/broker/broker_config.rs
  rocketmq-remoting/src/protocol/request_source.rs
  rocketmq-remoting/src/rpc/rpc_client_utils.rs
  rocketmq-store/src/base/get_message_result.rs
  rocketmq-store/src/stats/broker_stats_manager.rs
Labels: approved, auto merge

#707 [ISSUE #703]🚀Implement RpcClientUtils#encode_body method🚀
  rocketmq-broker/src/offset/manager/consumer_offset_manager.rs
  rocketmq-broker/src/out_api/broker_outer_api.rs
  rocketmq-broker/src/processor/client_manage_processor.rs
  rocketmq-broker/src/subscription/manager/subscription_group_manager.rs
  rocketmq-common/src/utils.rs
  rocketmq-common/src/utils/serde_json_utils.rs
  rocketmq-namesrv/src/kvconfig.rs
  rocketmq-namesrv/src/kvconfig/kvconfig_mananger.rs
  rocketmq-namesrv/src/processor/default_request_processor.rs
  rocketmq-remoting/src/protocol.rs
  rocketmq-remoting/src/protocol/body/broker_body/broker_member_group.rs
  rocketmq-remoting/src/protocol/body/broker_body/cluster_info.rs
  rocketmq-remoting/src/protocol/body/broker_body/register_broker_body.rs
  rocketmq-remoting/src/protocol/body/get_consumer_listby_group_response_body.rs
  rocketmq-remoting/src/protocol/body/kv_table.rs
  rocketmq-remoting/src/protocol/body/topic/topic_list.rs
  rocketmq-remoting/src/protocol/body/topic_info_wrapper.rs
  rocketmq-remoting/src/protocol/body/topic_info_wrapper/topic_config_wrapper.rs
  rocketmq-remoting/src/protocol/body/topic_info_wrapper/topic_queue_wrapper.rs
  rocketmq-remoting/src/protocol/header/message_operation_header/send_message_request_header.rs
  rocketmq-remoting/src/protocol/header/message_operation_header/send_message_response_header.rs
  rocketmq-remoting/src/protocol/header/pull_message_response_header.rs
  rocketmq-remoting/src/protocol/heartbeat/heartbeat_data.rs
  rocketmq-remoting/src/protocol/route/route_data_view.rs
  rocketmq-remoting/src/rpc/rpc_client_utils.rs
Labels: approved, auto merge

#709 [ISSUE #708]🚀Optimize TopicConfigManager🎨
  rocketmq-broker/src/lib.rs
  rocketmq-broker/src/topic/manager/topic_config_manager.rs
  rocketmq-common/src/utils/serde_json_utils.rs
Labels: approved, auto merge

#712 [ISSUE #711]🔨Add emoji for issue template
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/doc.yml
  .github/ISSUE_TEMPLATE/enhancement_request.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/ISSUE_TEMPLATE/unit_test.yml
Labels: approved, auto merge

#716 [ISSUE #715]✅Add test case for ClientChannelInfo
  rocketmq-broker/src/client/client_channel_info.rs
Labels: approved, auto merge, testing

#718 [ISSUE #717]⚡️Optimize ConsumerOffsetManager
  rocketmq-broker/src/offset/manager/consumer_offset_manager.rs
Labels: approved, auto merge

#720 [ISSUE #719]⚡️Add SyncUnsafeCell and Mutex bench
  Cargo.lock
  rocketmq-broker/Cargo.toml
  rocketmq-broker/benches/syncunsafecell_mut.rs
  rocketmq-common/src/utils/util_all.rs
Labels: approved, auto merge

#721 [ISSUE #710]🚀Support pull message result handle-3🎨
  Cargo.lock
  rocketmq-broker/Cargo.toml
  rocketmq-broker/src/lib.rs
  rocketmq-broker/src/long_polling.rs
  rocketmq-broker/src/long_polling/long_polling_service.rs
  rocketmq-broker/src/long_polling/long_polling_service/pull_request_hold_service.rs
  rocketmq-broker/src/long_polling/many_pull_request.rs
  rocketmq-broker/src/long_polling/notify_message_arriving_listener.rs
  rocketmq-broker/src/long_polling/pull_request.rs
  rocketmq-broker/src/longpolling.rs
  rocketmq-broker/src/processor/default_pull_message_result_handler.rs
  rocketmq-broker/src/processor/pull_message_processor.rs
  rocketmq-common/src/common/broker/broker_config.rs
  rocketmq-remoting/src/protocol.rs
  rocketmq-remoting/src/protocol/header/pull_message_request_header.rs
  rocketmq-remoting/src/protocol/remoting_command.rs
Labels: approved, auto merge
