Repository mxsm/rocketmq-rust, pull requests merged in 2024-11, with the labels that each got.

#1102 [ISSUE #1101] fix "subtract with overflow" bug for allocate_message_queue_averagely
  rocketmq-client/src/consumer/rebalance_strategy/allocate_message_queue_averagely.rs
Labels: approved, auto merge

#1108 [ISSUE #1106]Fix When topic not create the client can not consume
  rocketmq-client/examples/quickstart/consumer.rs
  rocketmq-client/src/consumer/consumer_impl/default_mq_push_consumer_impl.rs
  rocketmq-client/src/consumer/consumer_impl/re_balance/rebalance_impl.rs
  rocketmq-client/src/consumer/mq_consumer_inner.rs
  rocketmq-client/src/factory/mq_client_instance.rs
  rocketmq-client/src/implementation/mq_admin_impl.rs
  rocketmq-client/src/implementation/mq_client_api_impl.rs
Labels: approved, auto merge

#1111 [ISSUE #1110] Enable Consumer logging
  rocketmq-client/examples/quickstart/consumer.rs
Labels: approved, auto merge

#1113 [ISSUE #1112]Optimize MessageTrait's methods signature
  rocketmq-broker/src/processor/reply_message_processor.rs
  rocketmq-broker/src/processor/send_message_processor.rs
  rocketmq-broker/src/transaction/queue/transactional_message_bridge.rs
  rocketmq-broker/src/transaction/queue/transactional_message_util.rs
  rocketmq-client/src/consumer/consumer_impl/consume_message_concurrently_service.rs
  rocketmq-client/src/consumer/consumer_impl/consume_message_orderly_service.rs
  rocketmq-client/src/consumer/consumer_impl/default_mq_push_consumer_impl.rs
  rocketmq-client/src/consumer/consumer_impl/process_queue.rs
  rocketmq-client/src/consumer/consumer_impl/pull_api_wrapper.rs
  rocketmq-client/src/implementation/client_remoting_processor.rs
  rocketmq-client/src/producer/default_mq_producer.rs
  rocketmq-client/src/producer/producer_impl/default_mq_producer_impl.rs
  rocketmq-client/src/producer/transaction_mq_producer.rs
  rocketmq-client/src/utils/message_util.rs
  rocketmq-common/src/common/message.rs
  rocketmq-common/src/common/message/message_accessor.rs
  rocketmq-common/src/common/message/message_batch.rs
  rocketmq-common/src/common/message/message_client_ext.rs
  rocketmq-common/src/common/message/message_client_id_setter.rs
  rocketmq-common/src/common/message/message_decoder.rs
  rocketmq-common/src/common/message/message_ext.rs
  rocketmq-common/src/common/message/message_ext_broker_inner.rs
  rocketmq-common/src/common/message/message_single.rs
Labels: approved, auto merge

#1122 [ISSUE #1121]🧪Add test case for AccessChannel
  rocketmq-client/src/base/access_channel.rs
Labels: approved, auto merge

#1124 [ISSUE #1123]🧪Add test case for Validators
  rocketmq-client/src/base/validators.rs
Labels: approved, auto merge

#1126 [ISSUE #1125]🔊Implementing functionality similar to Java's LinkedBlockingQueue in Rust using Tokio🚀
  rocketmq/src/blocking_queue.rs
  rocketmq/src/lib.rs
Labels: approved, auto merge

#1128 [ISSUE #1127]🧪Add test case for BlockingQueue
  rocketmq/src/blocking_queue.rs
Labels: approved, auto merge

#1130 [ISSUE #1129]📝Add doc for BlockingQueue
  rocketmq/src/blocking_queue.rs
Labels: approved, auto merge

#1131 [ISSUE #1097]🚧Support broker receive transaction message-2🔥
  rocketmq-broker/src/broker_runtime.rs
  rocketmq-broker/src/processor.rs
  rocketmq-broker/src/processor/end_transaction_processor.rs
  rocketmq-broker/src/transaction/operation_result.rs
  rocketmq-broker/src/transaction/queue/default_transactional_message_service.rs
  rocketmq-broker/src/transaction/queue/message_queue_op_context.rs
  rocketmq-broker/src/transaction/queue/transactional_message_bridge.rs
  rocketmq-broker/src/transaction/queue/transactional_op_batch_service.rs
  rocketmq-broker/src/transaction/transactional_message_service.rs
  rocketmq-common/src/common/broker/broker_config.rs
  rocketmq/src/blocking_queue.rs
Labels: approved, auto merge

#1135 [ISSUE #1134]🔥Remove BrokerConfig duplicate codes🔥
  rocketmq-common/src/common/broker/broker_config.rs
Labels: approved, auto merge

#1141 [ISSUE #1140]⚡️Enhanced the RequestHeaderCodec macro
  rocketmq-macros/src/request_header_custom.rs
Labels: approved, auto merge

#1143 [ISSUE #1142]🔥Use CheetahString to replace std String🍻
  Cargo.lock
  rocketmq-broker/src/filter/expression_for_retry_message_filter.rs
  rocketmq-broker/src/filter/expression_message_filter.rs
  rocketmq-broker/src/long_polling/long_polling_service/pull_request_hold_service.rs
  rocketmq-broker/src/long_polling/notify_message_arriving_listener.rs
  rocketmq-broker/src/processor/end_transaction_processor.rs
  rocketmq-broker/src/processor/reply_message_processor.rs
  rocketmq-broker/src/processor/send_message_processor.rs
  rocketmq-broker/src/topic/manager/topic_queue_mapping_manager.rs
  rocketmq-broker/src/transaction/queue/transactional_message_bridge.rs
  rocketmq-broker/src/transaction/queue/transactional_message_util.rs
  rocketmq-broker/src/util/hook_utils.rs
  rocketmq-cli/Cargo.toml
  rocketmq-cli/src/content_show.rs
  rocketmq-client/src/base/validators.rs
  rocketmq-client/src/consumer/consumer_impl/consume_message_concurrently_service.rs
  rocketmq-client/src/consumer/consumer_impl/consume_message_orderly_service.rs
  rocketmq-client/src/consumer/consumer_impl/default_mq_push_consumer_impl.rs
  rocketmq-client/src/consumer/consumer_impl/process_queue.rs
  rocketmq-client/src/consumer/consumer_impl/pull_api_wrapper.rs
  rocketmq-client/src/implementation/client_remoting_processor.rs
  rocketmq-client/src/implementation/mq_client_api_impl.rs
  rocketmq-client/src/producer/default_mq_produce_builder.rs
  rocketmq-client/src/producer/default_mq_producer.rs
  rocketmq-client/src/producer/produce_accumulator.rs
  rocketmq-client/src/producer/producer_impl/default_mq_producer_impl.rs
  rocketmq-client/src/producer/request_response_future.rs
  rocketmq-client/src/producer/send_result.rs
  rocketmq-client/src/producer/transaction_mq_produce_builder.rs
  rocketmq-client/src/utils/message_util.rs
  rocketmq-common/src/common/message.rs
  rocketmq-common/src/common/message/message_accessor.rs
  rocketmq-common/src/common/message/message_batch.rs
  rocketmq-common/src/common/message/message_client_ext.rs
  rocketmq-common/src/common/message/message_client_id_setter.rs
  rocketmq-common/src/common/message/message_decoder.rs
  rocketmq-common/src/common/message/message_ext.rs
  rocketmq-common/src/common/message/message_ext_broker_inner.rs
  rocketmq-common/src/common/message/message_single.rs
  rocketmq-common/src/utils/message_utils.rs
  rocketmq-common/src/utils/string_utils.rs
  rocketmq-remoting/src/protocol/header/get_max_offset_request_header.rs
  rocketmq-remoting/src/protocol/header/get_min_offset_request_header.rs
  rocketmq-remoting/src/protocol/header/message_operation_header.rs
  rocketmq-remoting/src/protocol/header/message_operation_header/send_message_request_header.rs
  rocketmq-remoting/src/protocol/header/message_operation_header/send_message_request_header_v2.rs
  rocketmq-remoting/src/protocol/header/pull_message_request_header.rs
  rocketmq-remoting/src/protocol/header/query_consumer_offset_request_header.rs
  rocketmq-remoting/src/protocol/header/update_consumer_offset_header.rs
  rocketmq-remoting/src/protocol/static_topic/topic_queue_mapping_context.rs
  rocketmq-store/src/base/dispatch_request.rs
  rocketmq-store/src/base/message_arriving_listener.rs
  rocketmq-store/src/filter.rs
  rocketmq-store/src/log_file/commit_log.rs
Labels: approved, auto merge

#1145 [ISSUE #1144]Bump cheetah-string 0.1.2 to 0.1.4
  Cargo.toml
Labels: approved, auto merge

#1147 [ISSUE #1146]Update Github Actions CI
  .github/workflows/ci.yaml
Labels: approved, auto merge

#1149 [ISSUE #1148]Update codecov Github actions CI
  .github/workflows/codecov.yml
Labels: approved, auto merge

#1151 [ISSUE #1150]Use CheetahString to replace std String in MessageQueue
  Cargo.lock
  rocketmq-broker/src/processor/admin_broker_processor/consumer_request_handler.rs
  rocketmq-broker/src/processor/admin_broker_processor/topic_request_handler.rs
  rocketmq-broker/src/processor/default_pull_message_result_handler.rs
  rocketmq-client/src/base/client_config.rs
  rocketmq-common/src/common/message/message_queue.rs
Labels: approved, auto merge

#1153 [ISSUE #1152] Add test case for MessageQueue
  rocketmq-common/src/common/message/message_queue.rs
Labels: approved, auto merge

#1159 [ISSUE #1158]Refactor message_utils#delete_property method
  rocketmq-common/src/utils/message_utils.rs
Labels: approved, auto merge

#1161 [ISSUE #1160]🔥Optimize ValidateTopicResult String with CheetahString
  rocketmq-broker/src/processor/admin_broker_processor/topic_request_handler.rs
  rocketmq-common/src/common/topic.rs
Labels: auto merge, ready to review

#1164 [ISSUE #1163]📝Add rocketmq-rust roadmap
  README.md
  resources/rocektmq-rust-roadmap.excalidraw
  resources/rocektmq-rust-roadmap.png
Labels: approved, auto merge

#1166 [ISSUE #1165]📝Update README.md
  README.md
Labels: approved, auto merge

#1168 [ISSUE #1167]🎨Optimize RemotingCommand#with_remark method🎨
  rocketmq-broker/src/processor/send_message_processor.rs
  rocketmq-remoting/src/protocol/remoting_command.rs
Labels: approved, auto merge

#1172 [ISSUE #1171]Fix test case TopicConfigAndMappingSerializeWrapper#topic_config_and_mapping_serialize_wrapper_getters error
  rocketmq-remoting/src/protocol/body/topic_info_wrapper/topic_config_wrapper.rs
Labels: approved, auto merge

#1181 [ISSUE #1180]Fix cargo clippy -- -D warnings error
  rocketmq-broker/src/processor/pull_message_processor.rs
  rocketmq-broker/src/processor/send_message_processor.rs
  rocketmq-client/src/consumer/consumer_impl/pull_api_wrapper.rs
  rocketmq-client/src/implementation/mq_client_api_impl.rs
  rocketmq-common/src/utils/string_utils.rs
  rocketmq-namesrv/src/route/route_info_manager.rs
  rocketmq-store/src/log_file/commit_log.rs
Labels: approved, auto merge

#1183 [ISSUE #1182]🔨Add remove-label-on-approve.yml
  .github/workflows/remove-label-on-approve.yml
Labels: approved, auto merge, ready to review

#1185 [ISSUE #1184]🔨Upate Github actions CI🔧
  .github/workflows/auto-comment-pr.yml
  .github/workflows/automerge.yml
  .github/workflows/remove-label-on-approve.yml
Labels: approved, auto merge

#1187 [ISSUE #1186]🔥Optimize MQClientAPIImpl method🚀
  rocketmq-client/examples/transaction/transaction_producer.rs
  rocketmq-client/src/factory/mq_client_instance.rs
  rocketmq-client/src/hook/end_transaction_context.rs
  rocketmq-client/src/implementation/client_remoting_processor.rs
  rocketmq-client/src/implementation/mq_client_api_impl.rs
  rocketmq-client/src/producer/default_mq_producer.rs
  rocketmq-client/src/producer/producer_impl/default_mq_producer_impl.rs
  rocketmq-client/src/producer/producer_impl/mq_producer_inner.rs
  rocketmq-common/src/common/message.rs
  rocketmq-common/src/common/message/message_batch.rs
  rocketmq-common/src/common/message/message_client_ext.rs
  rocketmq-common/src/common/message/message_ext.rs
  rocketmq-common/src/common/message/message_ext_broker_inner.rs
  rocketmq-common/src/common/message/message_single.rs
Labels: approved, auto merge, Ai ready to review

#1189 [ISSUE #1188]🔨Upate Github actions CI🔧
  .github/workflows/auto-comment-pr.yml
Labels: approved, auto merge, Ai ready to review

#1193 [ISSUE #1192] 🔨Upate Github actions CI🔧
  .github/workflows/auto-comment-pr.yml
Labels: approved, auto merge, Ai ready to review

#1191 [ISSUE #1190]🧪Add unit test for CMResult
  rocketmq-remoting/src/protocol/body/cm_result.rs
Labels: ready to review, waiting-review, Ai ready to review

#1195 [ISSUE #1194]🔥Add doc for log.rs🚀
  rocketmq-common/src/log.rs
Labels: approved, auto merge, Ai ready to review

#1197 [ISSUE #1196]🔥Optimize CheetahString as method arg🎨
  rocketmq-broker/src/out_api/broker_outer_api.rs
  rocketmq-broker/src/processor/admin_broker_processor/batch_mq_handler.rs
  rocketmq-client/src/consumer/consumer_impl/re_balance/rebalance_impl.rs
  rocketmq-client/src/consumer/consumer_impl/re_balance/rebalance_push_impl.rs
  rocketmq-client/src/consumer/store/remote_broker_offset_store.rs
  rocketmq-client/src/factory/mq_client_instance.rs
  rocketmq-client/src/implementation/mq_client_api_impl.rs
  rocketmq-client/src/producer/producer_impl/default_mq_producer_impl.rs
  rocketmq-namesrv/src/route/route_info_manager.rs
  rocketmq-remoting/src/clients.rs
  rocketmq-remoting/src/clients/rocketmq_default_impl.rs
  rocketmq-remoting/src/rpc/rpc_client_impl.rs
Labels: approved, auto merge, Ai ready to review

#1199 [ISSUE #1194]🔨Update package , publish script📝
  distribution/package_publish_workspace.bat
  distribution/package_publish_workspace.sh
Labels: approved, auto merge, Ai ready to review

#1201 [ISSUE #1200]⚡️Optimize CheetahString for rocketmq-broker and rocketmq-store🎨
  rocketmq-broker/src/broker_runtime.rs
  rocketmq-broker/src/client/consumer_group_info.rs
  rocketmq-broker/src/client/manager/consumer_manager.rs
  rocketmq-broker/src/filter/consumer_filter_data.rs
  rocketmq-broker/src/filter/manager/consumer_filter_manager.rs
  rocketmq-broker/src/long_polling/long_polling_service/pull_request_hold_service.rs
  rocketmq-broker/src/long_polling/notify_message_arriving_listener.rs
  rocketmq-broker/src/offset/manager/consumer_offset_manager.rs
  rocketmq-broker/src/processor/admin_broker_processor/consumer_request_handler.rs
  rocketmq-broker/src/processor/admin_broker_processor/offset_request_handler.rs
  rocketmq-broker/src/processor/admin_broker_processor/topic_request_handler.rs
  rocketmq-broker/src/processor/client_manage_processor.rs
  rocketmq-broker/src/processor/consumer_manage_processor.rs
  rocketmq-broker/src/processor/default_pull_message_result_handler.rs
  rocketmq-broker/src/processor/pop_inflight_message_counter.rs
  rocketmq-broker/src/processor/pull_message_processor.rs
  rocketmq-broker/src/processor/query_message_processor.rs
  rocketmq-broker/src/processor/send_message_processor.rs
  rocketmq-broker/src/subscription/manager/subscription_group_manager.rs
  rocketmq-broker/src/topic/manager/topic_config_manager.rs
  rocketmq-broker/src/topic/manager/topic_queue_mapping_manager.rs
  rocketmq-broker/src/transaction/queue/transactional_message_bridge.rs
  rocketmq-client/src/consumer/consumer_impl/default_mq_push_consumer_impl.rs
  rocketmq-client/src/consumer/default_mq_push_consumer.rs
  rocketmq-client/src/consumer/mq_consumer_inner.rs
  rocketmq-client/src/factory/mq_client_instance.rs
  rocketmq-common/src/common/message/message_ext.rs
  rocketmq-common/src/common/message/message_ext_broker_inner.rs
  rocketmq-common/src/common/message/message_single.rs
  rocketmq-common/src/common/statistics/state_getter.rs
  rocketmq-remoting/src/protocol/body/group_list.rs
  rocketmq-remoting/src/protocol/heartbeat/consumer_data.rs
  rocketmq-remoting/src/protocol/subscription/subscription_group_config.rs
  rocketmq-store/src/base/dispatch_request.rs
  rocketmq-store/src/base/message_arriving_listener.rs
  rocketmq-store/src/kv/compaction_store.rs
  rocketmq-store/src/log_file.rs
  rocketmq-store/src/log_file/commit_log.rs
  rocketmq-store/src/message_store/default_message_store.rs
  rocketmq-store/src/queue.rs
  rocketmq-store/src/queue/batch_consume_queue.rs
  rocketmq-store/src/queue/consume_queue_ext.rs
  rocketmq-store/src/queue/local_file_consume_queue_store.rs
  rocketmq-store/src/queue/queue_offset_operator.rs
  rocketmq-store/src/queue/single_consume_queue.rs
  rocketmq-store/src/stats/broker_stats_manager.rs
  rocketmq-store/src/timer/timer_message_store.rs
Labels: approved, auto merge, AI review first

#1203 [ISSUE #1202]🔨Upate Github actions CI🔧
  .github/workflows/auto-comment-pr.yml
Labels: approved, auto merge, Ai ready to review

#1208 [ISSUE #1207]🔥Rename rocketmq-client crate name to rocketmq-client-rust🐛
  Cargo.lock
  Cargo.toml
  rocketmq-broker/Cargo.toml
  rocketmq-broker/src/transaction/queue/get_result.rs
  rocketmq-broker/src/transaction/queue/transactional_message_bridge.rs
  rocketmq-client/Cargo.toml
  rocketmq-client/README.md
  rocketmq-client/examples/batch/callback_batch_producer.rs
  rocketmq-client/examples/batch/simple_batch_producer.rs
  rocketmq-client/examples/broadcast/push_consumer.rs
  rocketmq-client/examples/ordermessage/ordermessage_consumer.rs
  rocketmq-client/examples/ordermessage/ordermessage_producer.rs
  rocketmq-client/examples/producer/simple_producer.rs
  rocketmq-client/examples/quickstart/consumer.rs
  rocketmq-client/examples/quickstart/producer.rs
  rocketmq-client/examples/rpc/request_callback_producer.rs
  rocketmq-client/examples/rpc/request_producer.rs
  rocketmq-client/examples/transaction/transaction_producer.rs
Labels: approved, auto merge, AI review first

#1211 [ISSUE #1210]✨Update the version to 0.4.0 for development
  Cargo.lock
  Cargo.toml
Labels: approved, auto merge, AI review first

#1213 [ISSUE #1212]🐛Fix TopicConfigSerializeWrapper unit test error
  rocketmq-remoting/src/protocol/body/topic_info_wrapper/topic_config_wrapper.rs
Labels: approved, auto merge, AI review first

#1215 [ISSUE #1214]🔥Optimize Send message put PROPERTY_UNIQ_CLIENT_MESSAGE_ID_KEYIDX Property
  rocketmq-broker/src/processor/send_message_processor.rs
Labels: approved, auto merge, AI review first

#1217 [ISSUE #1216]✅Optimize TransactionalMessageUtil some method⚡️
  rocketmq-broker/src/transaction/queue/transactional_message_util.rs
Labels: approved, auto merge, AI review first

#1218 [ISSUE #1136]🚀Support broker receive transaction message-3
  rocketmq-broker/src/processor/end_transaction_processor.rs
  rocketmq-broker/src/transaction/queue/default_transactional_message_service.rs
  rocketmq-broker/src/transaction/transactional_message_service.rs
Labels: approved, auto merge, AI review first

#1220 [ISSUE #1219]📝Update README.md
  README.md
Labels: approved, auto merge, AI review first

#1222 [ISSUE #1221]Optimize MappedFile method
  rocketmq-cli/src/content_show.rs
  rocketmq-remoting/src/protocol/body/topic_info_wrapper/topic_config_wrapper.rs
  rocketmq-store/src/base/append_message_callback.rs
  rocketmq-store/src/consume_queue/mapped_file_queue.rs
  rocketmq-store/src/index/index_file.rs
  rocketmq-store/src/log_file/mapped_file.rs
  rocketmq-store/src/log_file/mapped_file/default_mapped_file_impl.rs
Labels: approved, auto merge, AI review first

#1224 [ISSUE #1223]Change the return type of the get_transaction_id method in MessageTrait to &CheetahString
  rocketmq-broker/src/processor/end_transaction_processor.rs
  rocketmq-broker/src/transaction/queue/transactional_message_util.rs
  rocketmq-client/examples/transaction/transaction_producer.rs
  rocketmq-client/src/producer/producer_impl/default_mq_producer_impl.rs
  rocketmq-common/src/common/message.rs
  rocketmq-common/src/common/message/message_batch.rs
  rocketmq-common/src/common/message/message_client_ext.rs
  rocketmq-common/src/common/message/message_ext.rs
  rocketmq-common/src/common/message/message_ext_broker_inner.rs
  rocketmq-common/src/common/message/message_single.rs
Labels: approved, auto merge, AI review first

#1229 [ISSUE #1228]🚀Implement Java MessageDecoder class encodeUniquely and encode method
  rocketmq-client/src/producer/producer_impl/default_mq_producer_impl.rs
  rocketmq-common/src/common/compression/compression_type.rs
  rocketmq-common/src/common/compression/compressor.rs
  rocketmq-common/src/common/compression/lz4_compressor.rs
  rocketmq-common/src/common/compression/zlib_compressor.rs
  rocketmq-common/src/common/compression/zstd_compressor.rs
  rocketmq-common/src/common/message/message_decoder.rs
Labels: approved, auto merge, AI review first

#1231 [ISSUE #1230]🚀Support broker receive transaction message-4
  rocketmq-broker/src/broker_runtime.rs
  rocketmq-broker/src/client/manager/producer_manager.rs
  rocketmq-broker/src/client/net/broker_to_client.rs
  rocketmq-broker/src/error.rs
  rocketmq-broker/src/transaction.rs
  rocketmq-broker/src/transaction/queue/default_transactional_message_check_listener.rs
  rocketmq-broker/src/transaction/transactional_message_check_listener.rs
  rocketmq-broker/src/transaction/transactional_message_check_service.rs
  rocketmq-remoting/src/net/channel.rs
  rocketmq-remoting/src/protocol/header/check_transaction_state_request_header.rs
Labels: approved, auto merge, AI review first

#1233 [ISSUE #1232]Optimize DefaultRequestProcessor code
  rocketmq-namesrv/src/bootstrap.rs
  rocketmq-namesrv/src/processor.rs
  rocketmq-namesrv/src/processor/client_request_processor.rs
  rocketmq-namesrv/src/processor/default_request_processor.rs
Labels: approved, auto merge, AI review first

#1237 [ISSUE #1236]Add #[inline] for DefaultRemotingRequestProcessor#process_request
  rocketmq-remoting/src/request_processor/default_request_processor.rs
Labels: approved, auto merge, AI review first

#1238 [ISSUE #1234]🐛NameServer Cannot drop a runtime in a context where blocking is not allowed
  rocketmq-namesrv/src/bootstrap.rs
  rocketmq-remoting/src/clients/rocketmq_default_impl.rs
Labels: approved, auto merge, AI review first

#1240 [ISSUE #1239]🔥Optimize KVConfigManager code⚡️
  rocketmq-namesrv/src/bootstrap.rs
  rocketmq-namesrv/src/kvconfig/kvconfig_mananger.rs
  rocketmq-namesrv/src/processor.rs
  rocketmq-namesrv/src/processor/client_request_processor.rs
  rocketmq-namesrv/src/processor/default_request_processor.rs
  rocketmq-namesrv/src/route/route_info_manager.rs
Labels: approved, auto merge, AI review first

#1242 [ISSUE #1241]🔨Add Associate Milestone Github Action
  .github/workflows/associate_milestone.yml
Labels: approved, auto merge, AI review first

#1246 [ISSUE #1245]🔨Update Associate Milestone Github Action CI
  .github/workflows/associate_milestone_issue.yml
  .github/workflows/associate_milestone_pr.yml
Labels: approved, auto merge, AI review first

#1248 [ISSUE #1247]🔨Add Sync Issue Labels to PR Github action CI
  .github/workflows/sync-issue-labels.yml
Labels: feature, approved, auto merge, AI review first

#1250 [ISSUE #1249]🍻Optimize RouteInfoManager logic
  rocketmq-namesrv/src/processor/default_request_processor.rs
  rocketmq-namesrv/src/route/route_info_manager.rs
Labels: enhancement, approved, auto merge, AI review first

#1255 [ISSUE #1254]🚀RocketMQRuntime add schedule_at_fixed_rate_mut method
  rocketmq-runtime/src/lib.rs
Labels: feature, approved, auto merge, AI review first

#1257 [ISSUE #1256]🔨Update Associate Milestone Github actions CI
  .github/workflows/associate_milestone_issue.yml
  .github/workflows/associate_milestone_pr.yml
Labels: enhancement, approved, auto merge, AI review first

#1259 [ISSUE #1253]⚡️Optimize RouteInfoManager in NameServerBootstrap, remove RouteInfoManager parking_lot::RwLock
  rocketmq-broker/src/out_api/broker_outer_api.rs
  rocketmq-namesrv/src/bootstrap.rs
  rocketmq-namesrv/src/processor/client_request_processor.rs
  rocketmq-namesrv/src/processor/default_request_processor.rs
  rocketmq-namesrv/src/route/route_info_manager.rs
  rocketmq-remoting/src/protocol/header/namesrv/register_broker_header.rs
  rocketmq-remoting/src/protocol/namesrv.rs
  rocketmq-remoting/src/protocol/remoting_command.rs
Labels: enhancement, approved, auto merge, AI review first

#1262 [ISSUE #1261]⚡️TopicFilterType implement Display
  rocketmq-common/src/common.rs
Labels: enhancement, approved, auto merge, AI review first

#1264 [ISSUE #1263]🔨Optimize TopicConfig encode📝
  rocketmq-common/src/common/config.rs
Labels: enhancement, approved, auto merge, AI review first

#1268 [ISSUE #1267]⚡️Optimize Name server DefaultRequestProcessor#query_broker_topic_config
  rocketmq-namesrv/src/processor/default_request_processor.rs
  rocketmq-namesrv/src/route/route_info_manager.rs
Labels: enhancement, approved, auto merge, AI review first

#1274 [ISSUE #1269]⚡️Optimize name server DefaultRequestProcessor#process_register_broker
  rocketmq-namesrv/src/processor/default_request_processor.rs
  rocketmq-namesrv/src/route/route_info_manager.rs
  rocketmq-remoting/src/protocol/route/route_data_view.rs
Labels: enhancement, approved, auto merge, AI review first

#1276 [ISSUE #1275]⚡️Optimize name server DefaultRequestProcessor#get_broker_member_group
  Cargo.lock
  rocketmq-broker/src/out_api/broker_outer_api.rs
  rocketmq-client/src/factory/mq_client_instance.rs
  rocketmq-namesrv/src/route/route_info_manager.rs
  rocketmq-namesrv/src/route_info/broker_addr_info.rs
  rocketmq-remoting/src/protocol/header/namesrv/brokerid_change_request_header.rs
  rocketmq-remoting/src/protocol/header/namesrv/register_broker_header.rs
  rocketmq-remoting/src/protocol/route/route_data_view.rs
  rocketmq-remoting/src/rpc/client_metadata.rs
Labels: enhancement, approved, auto merge, AI review first

#1278 [ISSUE #1277]⚡️Optimize name server DefaultRequestProcessor#wipe_write_perm_of_broker_by_lock
  rocketmq-namesrv/src/processor/default_request_processor.rs
  rocketmq-namesrv/src/route/route_info_manager.rs
Labels: enhancement, approved, auto merge, AI review first

#1280 [ISSUE #1279]⚡️Optimize name server DefaultRequestProcessor#get_all_topic_list_from_nameserver
  rocketmq-namesrv/src/route/route_info_manager.rs
Labels: approved, auto merge, AI review first

#1282 [ISSUE #1281]⚡️Optimize name server DefaultRequestProcessor#delete_topic_in_name_srv
  rocketmq-namesrv/src/processor/default_request_processor.rs
  rocketmq-namesrv/src/route/route_info_manager.rs
Labels: enhancement, approved, auto merge, AI review first

#1284 [ISSUE #1283]⚡️Optimize name server DefaultRequestProcessor
  rocketmq-namesrv/src/processor/default_request_processor.rs
  rocketmq-namesrv/src/route/route_info_manager.rs
Labels: enhancement, approved, auto merge, AI review first

#1286 [ISSUE #1285]⚡️Optimize name server ClientRequestProcessor#get_route_info_by_topic
  rocketmq-namesrv/src/processor/client_request_processor.rs
  rocketmq-namesrv/src/route/route_info_manager.rs
Labels: approved, auto merge, AI review first

#1289 [ISSUE #1288]⚡️Add doc for MessageSysFlag and optimize code
  rocketmq-common/src/common/sys_flag/message_sys_flag.rs
Labels: enhancement, approved, auto merge, AI review first

#1306 [ISSUE #1305]🚀Add SetMessageRequestModeRequestBody
  rocketmq-remoting/src/protocol/body.rs
  rocketmq-remoting/src/protocol/body/set_message_request_mode_request_body.rs
Labels: feature, approved, auto merge, AI review first

#1308 [ISSUE ##1307]🚀Implement MessageRequestModeManager
  rocketmq-broker/src/lib.rs
  rocketmq-broker/src/load_balance.rs
  rocketmq-broker/src/load_balance/message_request_mode_manager.rs
Labels: feature, approved, auto merge, AI review first

#1311 [ISSUE #1310]⚡️Refactor AllocateMessageQueueStrategy
  rocketmq-client/src/consumer/allocate_message_queue_strategy.rs
  rocketmq-client/src/consumer/rebalance_strategy/allocate_message_queue_averagely.rs
Labels: enhancement, approved, auto merge, AI review first

#1320 [ISSUE #1319]🔨Update Github Actions CI
  .github/workflows/associate_milestone_issue.yml
  .github/workflows/associate_milestone_pr.yml
  .github/workflows/auto-comment-pr.yml
  .github/workflows/remove-label-on-approve.yml
  .github/workflows/sync-issue-labels.yml
Labels: enhancement, approved, auto merge, AI review first

#1325 Revert "[ISSUE #1319]🔨Update Github Actions CI"
  .github/workflows/associate_milestone_issue.yml
  .github/workflows/associate_milestone_pr.yml
  .github/workflows/auto-comment-pr.yml
  .github/workflows/remove-label-on-approve.yml
  .github/workflows/sync-issue-labels.yml
Labels: enhancement, approved, auto merge, AI review first

#1326 Revert "[ISSUE #1313]🔨Update Github Actions CI"
  .github/workflows/associate_milestone_issue.yml
  .github/workflows/associate_milestone_pr.yml
  .github/workflows/sync-issue-labels.yml
Labels: ready to review, waiting-review, AI review first

#1327 [ISSUE #1323]🔨Update Github Actions CI
  .github/workflows/associate_milestone_issue.yml
  .github/workflows/associate_milestone_pr.yml
Labels: ready to review, waiting-review, AI review first

#1322 [ISSUE #1321]🧪Add unit test for OperationResult
  rocketmq-broker/src/transaction/operation_result.rs
Labels: ready to review, waiting-review, AI review first

#1329 [ISSUE #1328]🧪Add test for ConsumerData
  rocketmq-remoting/src/protocol/heartbeat/consumer_data.rs
Labels: approved, auto merge, testing, AI review first

#1333 [ISSUE #1332]🔨Update Github Actions CI
  .github/workflows/remove-label-on-approve.yml
  .github/workflows/sync-issue-labels.yml
Labels: enhancement, approved, auto merge, AI review first

#1337 [ISSUE #1336]🔨Update Github Actions CI
  .github/workflows/automerge.yml
  .github/workflows/remove-label-on-approve.yml
  .github/workflows/sync-issue-labels.yml
Labels: enhancement, ready to review, waiting-review, AI review first

#1335 [ISSUE #1330]🧪Add unit test for MessageModel
  rocketmq-remoting/src/protocol/heartbeat/message_model.rs
Labels: approved, auto merge, AI review first

#1341 [ISSUE #1340]🔨Update Github Actions CI
  .github/workflows/automerge.yml
  .github/workflows/remove-label-on-approve.yml
  .github/workflows/sync-issue-labels.yml
  .github/workflows/update-labels.yml
Labels: approved, auto merge, ready to review, waiting-review, AI review first

#1339 [ISSUE #1338]🧪Add Unit test for ProducerData
  rocketmq-remoting/src/protocol/heartbeat/producer_data.rs
Labels: ready to review, waiting-review, AI review first

#1346 [ISSUE #1345]🔨Update Github Actions CI
  .github/workflows/update-labels.yml
Labels: enhancement, approved, auto merge, AI review first

#1350 [ISSUE #1349]🔨Update Github Actions CI
  .github/workflows/remove-label-on-approve.yml
  .github/workflows/update-labels.yml
Labels: enhancement, ready to review, waiting-review, AI review first

#1353 [ISSUE #1352]🔨Update Github Actions CI
  .github/workflows/remove-label-on-approve.yml
Labels: enhancement, ready to review, waiting-review, AI review first

#1348 [ISSUE #1347]🧪Add unit test for route_data_view
  rocketmq-remoting/src/protocol/route/route_data_view.rs
Labels: ready to review, testing, waiting-review, AI review first

#1355 [ISSUE #1354]🔨Update Github Actions CI
  .github/workflows/remove-label-on-approve.yml
  .github/workflows/update-labels.yml
Labels: enhancement, approved, auto merge, ready to review, waiting-review, AI review first

#1357 [ISSUE #1356]🧪Add unit test for CreateTopicRequestHeader
  rocketmq-remoting/src/protocol/header/create_topic_request_header.rs
Labels: ready to review, testing, waiting-review, AI review first

#1359 [ISSUE #1358]🔨Update Github Actions CI
  .github/workflows/auto-comment-pr.yml
  .github/workflows/automerge.yml
  .github/workflows/remove-label-on-approve.yml
Labels: enhancement, approved, auto merge, AI review first

#1361 [ISSUE #1360]🧪Add unit test for DeleteTopicRequestHeader
  rocketmq-remoting/src/protocol/header/delete_topic_request_header.rs
Labels: approved, auto merge, ready to review, testing, waiting-review, AI review first

#1363 [ISSUE #1362]🎨Refactor QueryAssignmentProcessor
  rocketmq-broker/src/broker_runtime.rs
  rocketmq-broker/src/load_balance/message_request_mode_manager.rs
  rocketmq-broker/src/processor/query_assignment_processor.rs
  rocketmq-client/src/consumer/rebalance_strategy.rs
Labels: enhancement, auto merge, ready to review, waiting-review, AI review first

#1369 [ISSUE #1368]📝Update README.md
  README.md
Labels: documentation, auto merge, ready to review, waiting-review, AI review first

#1371 [ISSUE #1370]🚀Add PlainAccessConfig
  rocketmq-common/src/common/base.rs
  rocketmq-common/src/common/base/plain_access_config.rs
Labels: feature, rust, auto merge, ready to review, waiting-review, AI review first

#1375 [ISSUE #1374]🚀Add CheckRocksdbCqWriteProgressResponseBody and ProducerConnection
  rocketmq-remoting/src/protocol/body.rs
  rocketmq-remoting/src/protocol/body/check_rocksdb_cqwrite_progress_response_body.rs
  rocketmq-remoting/src/protocol/body/connection.rs
  rocketmq-remoting/src/protocol/body/producer_connection.rs
Labels: feature, auto merge, ready to review, waiting-review, AI review first

#1388 [ISSUE #1387]🚀Add rocketmq-tools crate🔥
  Cargo.lock
  Cargo.toml
  rocketmq-tools/Cargo.toml
  rocketmq-tools/README.md
  rocketmq-tools/src/lib.rs
Labels: feature, auto merge, ready to review, waiting-review, AI review first

#1390 [ISSUE #1389]🔨Update package and publish script🔊
  distribution/package_publish_workspace.bat
  distribution/package_publish_workspace.sh
Labels: enhancement, auto merge, ready to review, waiting-review, AI review first

#1395 [ISSUE #1367]🚀Client Supports request code SetMessageRequestMode (401)
  Cargo.lock
  rocketmq-client/src/consumer/consumer_impl/pull_request_ext.rs
  rocketmq-client/src/consumer/mq_consumer_inner.rs
  rocketmq-client/src/implementation/mq_client_api_impl.rs
  rocketmq-client/src/lib.rs
  rocketmq-client/src/producer/producer_impl/mq_producer_inner.rs
  rocketmq-tools/Cargo.toml
  rocketmq-tools/src/admin.rs
  rocketmq-tools/src/admin/default_mq_admin_ext.rs
  rocketmq-tools/src/admin/default_mq_admin_ext_impl.rs
  rocketmq-tools/src/lib.rs
  rocketmq-tools/src/tools_error.rs
Labels: feature, auto merge, ready to review, waiting-review, AI review first

#1397 [ISSUE #1396]🔥Remove unused crate in rocketmq-store
  Cargo.lock
  rocketmq-store/Cargo.toml
Labels: enhancement, auto merge, ready to review, waiting-review, AI review first

#1401 [ISSUE #1400]⚡️Add #[inline] for WeakArcMut and ArcMut
  rocketmq/src/arc_mut.rs
Labels: enhancement, auto merge, ready to review, waiting-review, AI review first

#1402 [ISSUE #1301]🔥Rocketmq-rust broker supports request code QUERY_ASSIGNMENT(400)🚀
  rocketmq-broker/src/broker_runtime.rs
  rocketmq-broker/src/error.rs
  rocketmq-broker/src/processor/query_assignment_processor.rs
  rocketmq-common/src/common/broker/broker_config.rs
Labels: help wanted, feature, auto merge, ready to review, waiting-review, AI review first

#1406 [ISSUE #1405]🚀Remove unused crate in rocketmq-common🔊
  Cargo.lock
  rocketmq-common/Cargo.toml
Labels: enhancement, auto merge, ready to review, waiting-review, AI review first

#1408 [ISSUE #1407]🔥Remove unused crate in rocketmq-broker🚨
  Cargo.lock
  rocketmq-broker/Cargo.toml
  rocketmq-broker/src/processor/query_assignment_processor.rs
  rocketmq-broker/src/processor/reply_message_processor.rs
  rocketmq-broker/src/transaction/queue/transactional_op_batch_service.rs
Labels: enhancement, auto merge, ready to review, waiting-review, AI review first

#1410 [ISSUE #1409]🔥Remove unused crate in rocketmq-namesrv🚨
  Cargo.lock
  rocketmq-namesrv/Cargo.toml
Labels: enhancement, auto merge, ready to review, waiting-review, AI review first

#1414 [ISSUE #1385]🚀Add UserInfo and AclInfo
  rocketmq-remoting/src/protocol/body.rs
  rocketmq-remoting/src/protocol/body/acl_info.rs
  rocketmq-remoting/src/protocol/body/user_info.rs
Labels: feature, auto merge, ready to review, waiting-review, AI review first

#1415 [ISSUE #1302]🔥Rocketmq-rust client supports request code QUERY_ASSIGNMENT(400)
  rocketmq-client/src/consumer/consumer_impl/re_balance/rebalance_impl.rs
  rocketmq-client/src/factory/mq_client_instance.rs
  rocketmq-client/src/implementation/mq_client_api_impl.rs
Labels: help wanted, feature, auto merge, ready to review, waiting-review, AI review first

#1418 [ISSUE #1417]🔥BrokerData and QueueData add Default implement
  rocketmq-remoting/src/protocol/route/route_data_view.rs
Labels: enhancement, auto merge, ready to review, waiting-review, AI review first

#1419 [ISSUE #1416]🐛Fix TopicRouteData Serialize and Deserialize field name error
  rocketmq-remoting/src/protocol/route/topic_route_data.rs
Labels: bug, auto merge, ready to review, waiting-review, AI review first

#1424 [ISSUE #1423]🚀Add TraceBean
  rocketmq-client/src/trace.rs
  rocketmq-client/src/trace/trace_bean.rs
  rocketmq-common/src/utils/util_all.rs
Labels: feature, auto merge, ready to review, waiting-review, AI review first

#1427 [ISSUE #1425]🚀Add TraceType struct
  rocketmq-client/src/trace.rs
  rocketmq-client/src/trace/trace_type.rs
Labels: feature, auto merge, ready to review, waiting-review, AI review first

#1428 [ISSUE #1426]🚀Add TraceContext struct
  rocketmq-client/src/trace.rs
  rocketmq-client/src/trace/trace_context.rs
Labels: feature, auto merge, ready to review, waiting-review, AI review first

#1431 [ISSUE #1430] Add TopicMessageQueueChangeListener trait for client
  rocketmq-client/src/consumer.rs
  rocketmq-client/src/consumer/topic_message_queue_change_listener.rs
Labels: feature, auto merge, ready to review, waiting-review, AI review first

#1434 [ISSUE #1433]🐛Fix LitePullConsumerLocal trait_variant::make error
  rocketmq-client/src/consumer/lite_pull_consumer.rs
Labels: bug, auto merge, ready to review, waiting-review, AI review first

#1436 [ISSUE #1435]🔥Update rocketmq-cli Cargo.toml🚨
  rocketmq-cli/Cargo.toml
Labels: enhancement, auto merge, ready to review, waiting-review, AI review first

#1440 [ISSUE #1437]🔥Remove unused crate from rocketmq-remoting🚨
  Cargo.lock
  rocketmq-remoting/Cargo.toml
Labels: enhancement, auto merge, ready to review, waiting-review, AI review first

#1441 [ISSUE #1438]🔥Remove unused crate from rocketmq-runtime🚨
  Cargo.lock
  rocketmq-runtime/Cargo.toml
Labels: enhancement, auto merge, ready to review, waiting-review, AI review first

#1444 [ISSUE #1443]🔨Add Template for code refactor
  .github/ISSUE_TEMPLATE/refactor.yml
Labels: documentation, auto merge, ready to review, waiting-review, AI review first

#1446 [ISSUE #1445]🔨Update refactor.yml
  .github/ISSUE_TEMPLATE/refactor.yml
Labels: enhancement, auto merge, ready to review, waiting-review, AI review first

#1447 🔨Update refactor.yml
  .github/ISSUE_TEMPLATE/refactor.yml
Labels: auto merge, ready to review, waiting-review, AI review first

#1451 [ISSUE #1450]🔨Update refactor.yml
  .github/ISSUE_TEMPLATE/refactor.yml
Labels: enhancement, auto merge, ready to review, waiting-review, AI review first

#1455 [ISSUE #1452]🔥Refactor rocketmq-remoting crate error handle🚨
  rocketmq-broker/src/error.rs
  rocketmq-broker/src/lib.rs
  rocketmq-client/src/error.rs
  rocketmq-remoting/src/clients/client.rs
  rocketmq-remoting/src/clients/rocketmq_default_impl.rs
  rocketmq-remoting/src/code/broker_request_code.rs
  rocketmq-remoting/src/codec/remoting_command_codec.rs
  rocketmq-remoting/src/error.rs
  rocketmq-remoting/src/lib.rs
  rocketmq-remoting/src/net/channel.rs
  rocketmq-remoting/src/protocol/remoting_command.rs
  rocketmq-remoting/src/protocol/rocketmq_serializable.rs
  rocketmq-remoting/src/remoting_error.rs
  rocketmq-remoting/src/remoting_server/server.rs
  rocketmq-remoting/src/rpc/rpc_client_impl.rs
  rocketmq-remoting/src/rpc/rpc_response.rs
Labels: refactor, auto merge, ready to review, waiting-review, AI review first

#1457 [ISSUE #1456]🔥Refactor rocketmq-broker crate error handle🚨
  rocketmq-broker/src/broker_error.rs
  rocketmq-broker/src/client/net/broker_to_client.rs
  rocketmq-broker/src/lib.rs
  rocketmq-broker/src/out_api/broker_outer_api.rs
  rocketmq-broker/src/processor/query_assignment_processor.rs
  rocketmq-broker/src/topic/manager/topic_route_info_manager.rs
Labels: refactor, auto merge, ready to review, waiting-review, AI review first

#1459 [ISSUE #1458]🔥Refactor rocketmq-client crate error handle🚨
  rocketmq-broker/src/broker_error.rs
  rocketmq-client/src/base/validators.rs
  rocketmq-client/src/client_error.rs
  rocketmq-client/src/consumer/consumer_impl/default_mq_push_consumer_impl.rs
  rocketmq-client/src/consumer/consumer_impl/pull_api_wrapper.rs
  rocketmq-client/src/consumer/consumer_impl/re_balance/rebalance_impl.rs
  rocketmq-client/src/consumer/consumer_impl/re_balance/rebalance_push_impl.rs
  rocketmq-client/src/consumer/pull_callback.rs
  rocketmq-client/src/consumer/rebalance_strategy.rs
  rocketmq-client/src/consumer/store/local_file_offset_store.rs
  rocketmq-client/src/consumer/store/remote_broker_offset_store.rs
  rocketmq-client/src/error.rs
  rocketmq-client/src/factory/mq_client_instance.rs
  rocketmq-client/src/implementation/mq_admin_impl.rs
  rocketmq-client/src/implementation/mq_client_api_impl.rs
  rocketmq-client/src/lib.rs
  rocketmq-client/src/producer/default_mq_producer.rs
  rocketmq-client/src/producer/producer_impl/default_mq_producer_impl.rs
  rocketmq-client/src/producer/request_callback.rs
  rocketmq-client/src/producer/request_future_holder.rs
  rocketmq-client/src/utils/message_util.rs
  rocketmq-tools/src/tools_error.rs
Labels: refactor, auto merge, ready to review, waiting-review, AI review first

#1461 [ISSUE #1460]🔥Add macro for create client error🚀
  rocketmq-client/src/client_error.rs
Labels: feature, auto merge, ready to review, waiting-review, AI review first

#1465 [ISSUE #1462]🔥Add macro for create client broker error🚀
  rocketmq-client/src/client_error.rs
Labels: feature, auto merge, ready to review, waiting-review, AI review first

#1467 [ISSUE #1466]🔥Optimize mq_client_err! macro🚀
  rocketmq-client/src/client_error.rs
Labels: enhancement, auto merge, ready to review, waiting-review, AI review first

#1469 [ISSUE #1468]📝Update README.md🚀
  README.md
Labels: documentation, auto merge, ready to review, waiting-review, AI review first

#1473 [ISSUE #1470]♻️FromMap trait from mehtod return type changed from Option<Self::Target> to Result<Self::Target,Self::Error>🚀
  rocketmq-broker/src/out_api/broker_outer_api.rs
  rocketmq-broker/src/processor/admin_broker_processor/offset_request_handler.rs
  rocketmq-broker/src/processor/reply_message_processor.rs
  rocketmq-broker/src/processor/send_message_processor.rs
  rocketmq-macros/src/request_header_custom.rs
  rocketmq-remoting/src/protocol/command_custom_header.rs
  rocketmq-remoting/src/protocol/header/broker/broker_heartbeat_request_header.rs
  rocketmq-remoting/src/protocol/header/check_transaction_state_request_header.rs
  rocketmq-remoting/src/protocol/header/client_request_header.rs
  rocketmq-remoting/src/protocol/header/consumer_send_msg_back_request_header.rs
  rocketmq-remoting/src/protocol/header/create_topic_request_header.rs
  rocketmq-remoting/src/protocol/header/delete_topic_request_header.rs
  rocketmq-remoting/src/protocol/header/end_transaction_request_header.rs
  rocketmq-remoting/src/protocol/header/get_all_topic_config_response_header.rs
  rocketmq-remoting/src/protocol/header/get_consume_stats_request_header.rs
  rocketmq-remoting/src/protocol/header/get_consumer_connection_list_request_header.rs
  rocketmq-remoting/src/protocol/header/get_consumer_listby_group_request_header.rs
  rocketmq-remoting/src/protocol/header/get_consumer_listby_group_response_header.rs
  rocketmq-remoting/src/protocol/header/get_max_offset_request_header.rs
  rocketmq-remoting/src/protocol/header/get_min_offset_request_header.rs
  rocketmq-remoting/src/protocol/header/get_topic_config_request_header.rs
  rocketmq-remoting/src/protocol/header/get_topic_stats_request_header.rs
  rocketmq-remoting/src/protocol/header/heartbeat_request_header.rs
  rocketmq-remoting/src/protocol/header/lock_batch_mq_request_header.rs
  rocketmq-remoting/src/protocol/header/message_operation_header/send_message_request_header.rs
  rocketmq-remoting/src/protocol/header/message_operation_header/send_message_request_header_v2.rs
  rocketmq-remoting/src/protocol/header/namesrv/broker_request.rs
  rocketmq-remoting/src/protocol/header/namesrv/brokerid_change_request_header.rs
  rocketmq-remoting/src/protocol/header/namesrv/kv_config_header.rs
  rocketmq-remoting/src/protocol/header/namesrv/perm_broker_header.rs
  rocketmq-remoting/src/protocol/header/namesrv/query_data_version_header.rs
  rocketmq-remoting/src/protocol/header/namesrv/register_broker_header.rs
  rocketmq-remoting/src/protocol/header/namesrv/topic_operation_header.rs
  rocketmq-remoting/src/protocol/header/notify_consumer_ids_changed_request_header.rs
  rocketmq-remoting/src/protocol/header/pull_message_request_header.rs
  rocketmq-remoting/src/protocol/header/pull_message_response_header.rs
  rocketmq-remoting/src/protocol/header/query_consumer_offset_request_header.rs
  rocketmq-remoting/src/protocol/header/query_message_request_header.rs
  rocketmq-remoting/src/protocol/header/query_topic_consume_by_who_request_header.rs
  rocketmq-remoting/src/protocol/header/query_topics_by_consumer_request_header.rs
  rocketmq-remoting/src/protocol/header/reply_message_request_header.rs
  rocketmq-remoting/src/protocol/header/unlock_batch_mq_request_header.rs
  rocketmq-remoting/src/protocol/header/unregister_client_request_header.rs
  rocketmq-remoting/src/protocol/header/update_consumer_offset_header.rs
  rocketmq-remoting/src/protocol/remoting_command.rs
  rocketmq-remoting/src/rpc/rpc_request_header.rs
  rocketmq-remoting/src/rpc/topic_request_header.rs
Labels: refactor, auto merge, ready to review, waiting-review, AI review first
