Repository mxsm/rocketmq-rust, pull requests merged in 2024-12, with the labels that each got.

#1475 [ISSUE #1474]⚡Optimize derive RequestHeaderCodec and add required attribute🚀
  rocketmq-macros/src/lib.rs
  rocketmq-macros/src/request_header_custom.rs
Labels: enhancement, feature, auto merge, ready to review, waiting-review, AI review first

#1478 [ISSUE #1476]♻️Refactor derive RequestHeaderCodec parse logic🔥
  rocketmq-macros/src/request_header_custom.rs
Labels: refactor, auto merge, ready to review, waiting-review, AI review first

#1481 [ISSUE #1480]⚡️Optimize SendMessageProcessor error handle🔥
  rocketmq-broker/src/broker_error.rs
  rocketmq-broker/src/processor.rs
  rocketmq-broker/src/processor/send_message_processor.rs
Labels: enhancement, auto merge, ready to review, waiting-review, AI review first

#1483 [ISSUE #1482]♻️Refactor create MQClientErr replace with mq_client_err! macro🔥
  rocketmq-client/src/base/validators.rs
  rocketmq-client/src/consumer/consumer_impl/default_mq_push_consumer_impl.rs
  rocketmq-client/src/consumer/consumer_impl/pull_api_wrapper.rs
  rocketmq-client/src/consumer/consumer_impl/re_balance/rebalance_push_impl.rs
  rocketmq-client/src/consumer/store/local_file_offset_store.rs
  rocketmq-client/src/consumer/store/remote_broker_offset_store.rs
  rocketmq-client/src/factory/mq_client_instance.rs
  rocketmq-client/src/implementation/mq_admin_impl.rs
  rocketmq-client/src/implementation/mq_client_api_impl.rs
  rocketmq-client/src/producer/default_mq_producer.rs
  rocketmq-client/src/producer/producer_impl/default_mq_producer_impl.rs
  rocketmq-client/src/utils/message_util.rs
  rocketmq/src/shutdown.rs
Labels: refactor, auto merge, ready to review, waiting-review, AI review first

#1485 feat/91: Add get namesrv config request
  rocketmq-common/src/common/namesrv/namesrv_config.rs
  rocketmq-namesrv/src/processor/default_request_processor.rs
Labels: enhancement, help wanted, good first issue, feature, auto merge, ready to review, waiting-review, AI review first

#1486 [ISSUE #1484]♻️Refactor create MQBrokerErr replace with client_broker_err! macro🔥
  rocketmq-client/src/implementation/mq_client_api_impl.rs
Labels: refactor, auto merge, ready to review, waiting-review, AI review first

#1487 [ISSUE #1477]🚀derive RequestHeaderCodec support Struct🔥
  rocketmq-macros/src/lib.rs
  rocketmq-macros/src/request_header_custom.rs
Labels: feature, auto merge, ready to review, waiting-review, AI review first

#1490 [ISSUE #1489]📝Update rocketmq-macros README.md
  rocketmq-macros/README.md
Labels: documentation, auto merge, ready to review, waiting-review, AI review first

#1499 [ISSUE #1498]📝Update README.md
  README.md
Labels: documentation, auto merge, ready to review, waiting-review, AI review first

#1501 [ISSUE #1500]♻️Refactor SendMessageRequestHeaderV2🍻
  rocketmq-remoting/src/protocol/command_custom_header.rs
  rocketmq-remoting/src/protocol/header/message_operation_header/send_message_request_header_v2.rs
  rocketmq-remoting/src/protocol/header/pull_message_request_header.rs
  rocketmq-remoting/src/protocol/header/pull_message_response_header.rs
  rocketmq-remoting/src/protocol/remoting_command.rs
Labels: refactor, auto merge, ready to review, waiting-review, AI review first

#1504 [ISSUE #1502]♻️Refactor PullMessageRequestHeader🍻
  rocketmq-broker/src/processor/default_pull_message_result_handler.rs
  rocketmq-broker/src/processor/pull_message_processor.rs
  rocketmq-client/src/consumer/consumer_impl/pull_api_wrapper.rs
  rocketmq-remoting/src/protocol/header/pull_message_request_header.rs
Labels: refactor, auto merge, ready to review, waiting-review, AI review first

#1506 [ISSUE #1503]🍻Refactor PullMessageResponseHeader♻️
  rocketmq-broker/src/processor/default_pull_message_result_handler.rs
  rocketmq-broker/src/processor/pull_message_processor.rs
  rocketmq-client/src/implementation/mq_client_api_impl.rs
  rocketmq-remoting/src/protocol/header/pull_message_response_header.rs
Labels: refactor, auto merge, ready to review, waiting-review, AI review first

#1518 [ISSUE #1510]♻️Refactor GetBrokerMemberGroupRequestHeader with derive marco RequestHeaderCodec
  rocketmq-remoting/src/protocol/header/namesrv/broker_request.rs
Labels: refactor, approved, auto merge, ready to review, waiting-review, AI review first

#1517 [ISSUE #1495]🚀Optimize RemotingSerializable methods return type🔥
  rocketmq-broker/src/offset/manager/consumer_offset_manager.rs
  rocketmq-broker/src/out_api/broker_outer_api.rs
  rocketmq-broker/src/processor/admin_broker_processor/batch_mq_handler.rs
  rocketmq-broker/src/processor/admin_broker_processor/consumer_request_handler.rs
  rocketmq-broker/src/processor/admin_broker_processor/topic_request_handler.rs
  rocketmq-broker/src/processor/consumer_manage_processor.rs
  rocketmq-broker/src/processor/query_assignment_processor.rs
  rocketmq-broker/src/subscription/manager/subscription_group_manager.rs
  rocketmq-broker/src/topic/manager/topic_config_manager.rs
  rocketmq-broker/src/topic/manager/topic_queue_mapping_manager.rs
  rocketmq-client/src/consumer/store/local_file_offset_store.rs
  rocketmq-client/src/consumer/store/offset_serialize.rs
  rocketmq-client/src/implementation/mq_client_api_impl.rs
  rocketmq-namesrv/src/kvconfig/kvconfig_mananger.rs
  rocketmq-namesrv/src/processor/client_request_processor.rs
  rocketmq-namesrv/src/processor/default_request_processor.rs
  rocketmq-remoting/src/protocol.rs
  rocketmq-remoting/src/protocol/body/broker_body/register_broker_body.rs
  rocketmq-remoting/src/protocol/heartbeat/heartbeat_data.rs
  rocketmq-remoting/src/remoting_error.rs
  rocketmq-remoting/src/rpc/rpc_client_utils.rs
Labels: enhancement, auto merge, ready to review, waiting-review, AI review first

#1520 [ISSUE #1519] Replace SendMessageProcessor#process_request return type to crate::Result<Option<RemotingCommand>>
  rocketmq-broker/src/processor.rs
  rocketmq-broker/src/processor/send_message_processor.rs
  rocketmq-remoting/src/protocol/header/message_operation_header/send_message_request_header.rs
Labels: enhancement, auto merge, ready to review, waiting-review, AI review first

#1523 [ISSUE #1522]♻️Refactor UpdateConsumerOffsetRequestHeader with derive macro RequestHeaderCodec
  rocketmq-broker/src/processor/consumer_manage_processor.rs
  rocketmq-client/src/consumer/store/remote_broker_offset_store.rs
  rocketmq-remoting/src/protocol/header/update_consumer_offset_header.rs
Labels: refactor, auto merge, ready to review, waiting-review, AI review first

#1524 [ISSUE #1521]🔥Remove SendMessageRequestHeader queue_id Option🚀
  rocketmq-broker/src/processor/reply_message_processor.rs
  rocketmq-broker/src/processor/send_message_processor.rs
  rocketmq-broker/src/topic/manager/topic_queue_mapping_manager.rs
  rocketmq-client/src/common/thread_local_index.rs
  rocketmq-client/src/producer/producer_impl/default_mq_producer_impl.rs
  rocketmq-remoting/src/protocol/header/get_max_offset_request_header.rs
  rocketmq-remoting/src/protocol/header/get_min_offset_request_header.rs
  rocketmq-remoting/src/protocol/header/message_operation_header.rs
  rocketmq-remoting/src/protocol/header/message_operation_header/send_message_request_header.rs
  rocketmq-remoting/src/protocol/header/message_operation_header/send_message_request_header_v2.rs
  rocketmq-remoting/src/protocol/header/pull_message_request_header.rs
  rocketmq-remoting/src/protocol/header/query_consumer_offset_request_header.rs
  rocketmq-remoting/src/protocol/header/update_consumer_offset_header.rs
  rocketmq-store/src/log_file/commit_log.rs
Labels: enhancement, auto merge, ready to review, AI review first

#1526 [ISSUE #1525]Optimization condition judgment
  rocketmq-broker/src/processor/send_message_processor.rs
Labels: enhancement, auto merge, ready to review, AI review first

#1528 [ISSUE #1527]⚡️Optimize SendMessageProcessor handle error logic
  rocketmq-broker/src/processor/send_message_processor.rs
  rocketmq-common/src/common/message/message_ext_broker_inner.rs
Labels: enhancement, auto merge, ready to review, waiting-review, AI review first

#1531 [ISSUE #1530]⚡️Optimize CommitLog put message logic
  rocketmq-store/src/base/append_message_callback.rs
  rocketmq-store/src/log_file/commit_log.rs
  rocketmq-store/src/log_file/mapped_file/default_mapped_file_impl.rs
Labels: enhancement, auto merge, ready to review, waiting-review, AI review first

#1537 [ISSUE #1536]📝Update README.md
  README.md
Labels: documentation, auto merge, ready to review, waiting-review, AI review first

#1538 [ISSUE #1532]🚀Add support append enabled_append_prop_crc⚡️
  Cargo.lock
  rocketmq-common/Cargo.toml
  rocketmq-common/src/common/message/message_decoder.rs
  rocketmq-common/src/common/message/message_ext_broker_inner.rs
  rocketmq-store/src/base/append_message_callback.rs
  rocketmq-store/src/log_file/commit_log.rs
  rocketmq-store/src/log_file/mapped_file.rs
  rocketmq-store/src/log_file/mapped_file/default_mapped_file_impl.rs
  rocketmq-store/src/message_encoder/message_ext_encoder.rs
Labels: feature, auto merge, ready to review, waiting-review, AI review first

#1540 [ISSUE #1539]🐛Fix cargo clippy -- -D warnings error
  rocketmq-client/src/common/thread_local_index.rs
  rocketmq-store/src/log_file/commit_log.rs
Labels: bug, auto merge, ready to review, waiting-review, AI review first

#1543 [ISSUE #1542]♻️Refactor ConsumerSendMsgBackRequestHeader with derive RequestHeaderCodec🔥
  rocketmq-remoting/src/protocol/header/consumer_send_msg_back_request_header.rs
Labels: refactor, auto merge, ready to review, waiting-review, AI review first

#1545 [ISSUE #1544]🍻Add #[inline] for SubscriptionGroupConfig methods
  rocketmq-remoting/src/protocol/subscription/subscription_group_config.rs
Labels: enhancement, auto merge, ready to review, waiting-review, AI review first

#1547 [ISSUE #1546]🚀Rocketmq-rust broker supports RequestCode ConsumerSendMsgBack(36)🔥
  rocketmq-broker/src/processor/reply_message_processor.rs
  rocketmq-broker/src/processor/send_message_processor.rs
Labels: feature, auto merge, ready to review, waiting-review, AI review first

#1550 [ISSUE #1549]♻️Refactor GetRouteInfoRequestHeader with derive macro RequestHeaderCodec🔥
  rocketmq-remoting/src/protocol/header/client_request_header.rs
Labels: refactor, auto merge, ready to review, waiting-review, AI review first

#1557 [ISSUE #1556]🔨Update Gtihub sync-issue-labels.yml action
  .github/workflows/sync-issue-labels.yml
Labels: enhancement, auto merge, ready to review, waiting-review, AI review first

#1559 [ISSUE #1558]🚀Add error for rocketmq-namesrv
  Cargo.lock
  rocketmq-namesrv/Cargo.toml
  rocketmq-namesrv/src/lib.rs
  rocketmq-namesrv/src/namesrv_error.rs
Labels: feature, auto merge, ready to review, waiting-review, AI review first

#1561 [ISSUE #1553]🔥Optimize rocketmq-namesrv crate DefaultRequestProcessor error handle⚡️
  rocketmq-namesrv/src/processor.rs
  rocketmq-namesrv/src/processor/default_request_processor.rs
Labels: enhancement, auto merge, ready to review, waiting-review, AI review first

#1563 [ISSUE #1562]⚡️Optimize DefaultRequestProcessor error handle
  rocketmq-namesrv/src/namesrv_error.rs
  rocketmq-namesrv/src/processor/client_request_processor.rs
  rocketmq-namesrv/src/processor/default_request_processor.rs
Labels: enhancement, auto merge, ready to review, waiting-review, AI review first

#1571 [ISSUE #1570]🚀Add ConsumeMessageDirectlyResultRequestHeader struct🔥
  rocketmq-remoting/src/protocol/header.rs
  rocketmq-remoting/src/protocol/header/consume_message_directly_result_request_header.rs
Labels: feature, auto merge, ready to review, waiting-review, AI review first

#1572 [ISSUE #1569]🔥Add GetConsumerRunningInfoRequestHeader struct🚀
  rocketmq-remoting/src/protocol/header.rs
  rocketmq-remoting/src/protocol/header/get_consumer_running_info_request_header.rs
Labels: feature, auto merge, ready to review, waiting-review, AI review first

#1573 [ISSUE #1568]🔥Add ResetOffsetRequestHeader struct🚀
  rocketmq-remoting/src/protocol/header.rs
  rocketmq-remoting/src/protocol/header/reset_offset_request_header.rs
Labels: feature, auto merge, ready to review, waiting-review, AI review first

#1574 [ISSUE #1567]🔥Add DeleteSubscriptionGroupRequestHeader struct🍻
  rocketmq-remoting/src/protocol/header.rs
  rocketmq-remoting/src/protocol/header/delete_subscription_group_request_header.rs
Labels: feature, auto merge, ready to review, waiting-review, AI review first

#1575 [ISSUE #1566]🚀Add QueryConsumeTimeSpanRequestHeader struct🍻
  rocketmq-remoting/src/protocol/header.rs
  rocketmq-remoting/src/protocol/header/query_consume_time_span_request_header.rs
Labels: feature, auto merge, ready to review, waiting-review, AI review first

#1576 [ISSUE #1565]🍻Add GetTopicStatsInfoRequestHeader struct 💡
  rocketmq-remoting/src/protocol/header.rs
  rocketmq-remoting/src/protocol/header/get_topic_stats_info_request_header.rs
Labels: feature, auto merge, ready to review, waiting-review, AI review first

#1578 [ISSUE #1577]🍻Replace ConsumeMessageDirectlyResultRequestHeader and ResetOffsetRequestHeader's RpcRequestHeader with TopicRequestHeader
  rocketmq-remoting/src/protocol/header/consume_message_directly_result_request_header.rs
  rocketmq-remoting/src/protocol/header/reset_offset_request_header.rs
Labels: enhancement, auto merge, ready to review, waiting-review, AI review first

#1580 [ISSUE #1579]🐛get_topic_stats_info_request_header inner struct incorrect
  rocketmq-remoting/src/protocol/header/get_topic_stats_info_request_header.rs
Labels: bug, auto merge, ready to review, waiting-review, AI review first

#1582 [ISSUE #1581]🚀Add QueueTimeSpan struct
  rocketmq-remoting/src/protocol/body.rs
  rocketmq-remoting/src/protocol/body/queue_time_span.rs
Labels: enhancement, feature, auto merge, ready to review, waiting-review, AI review first

#1584 [ISSUE #1583]🍻Add QuerySubscriptionByConsumerRequestHeader struct
  rocketmq-remoting/src/protocol/header.rs
  rocketmq-remoting/src/protocol/header/query_subscription_by_consumer_request_header.rs
Labels: feature, auto merge, ready to review, waiting-review, AI review first

#1585 [ISSUE #1564]🍻Add MqClientAdmin trait💡
  rocketmq-client/src/base.rs
  rocketmq-client/src/base/mq_client_admin.rs
Labels: feature, auto merge, ready to review, waiting-review, AI review first

#1588 [ISSUE #1529]Add #[inline] for MessageExtBrokerInner methods
  rocketmq-common/src/common/message/message_ext_broker_inner.rs
Labels: enhancement, approved, auto merge, ready to review, waiting-review, AI review first

#1587 [ISSUE #1586]📝Update rocketmq-client Cargo.toml🍻
  rocketmq-client/Cargo.toml
Labels: enhancement, auto merge, ready to review, waiting-review, AI review first

#1589 [ISSUE #1507]♻️Refactor BrokerHeartbeatRequestHeader with derive marco RequestHeaderCodec
  rocketmq-remoting/src/protocol/header/broker/broker_heartbeat_request_header.rs
Labels: refactor, approved, auto merge, ready to review, waiting-review, AI review first

#1592 [ISSUE #1508]♻️Refactor UnRegisterBrokerRequestHeader with derive marco RequestHeaderCodec
  rocketmq-remoting/src/protocol/header/namesrv/broker_request.rs
Labels: refactor, approved, auto merge, ready to review, waiting-review, AI review first

#1596 [ISSUE #1595]🔥Remove label_approved_pull_requests.yml action
  .github/workflows/label_approved_pull_requests.yml
Labels: documentation, auto merge, ready to review, waiting-review, AI review first

#1600 [ISSUE #1598]🚀Rocketmq-client support Pop consumer-1
  rocketmq-client/src/consumer/consumer_impl/pop_process_queue.rs
  rocketmq-client/src/consumer/consumer_impl/pop_request.rs
  rocketmq-client/src/consumer/consumer_impl/re_balance.rs
  rocketmq-client/src/consumer/consumer_impl/re_balance/rebalance_impl.rs
  rocketmq-client/src/consumer/consumer_impl/re_balance/rebalance_push_impl.rs
  rocketmq-client/src/implementation/client_remoting_processor.rs
Labels: feature, auto merge, ready to review, waiting-review, AI review first

#1602 [ISSUE #1601]Optimize PopProcessQueue
  rocketmq-client/src/consumer/consumer_impl/pop_process_queue.rs
Labels: enhancement, auto merge, ready to review, waiting-review, AI review first

#1604 [ISSUE #1603]Add #[inline] to PopProcessQueue method and optimize code
  rocketmq-client/src/consumer/consumer_impl/pop_process_queue.rs
Labels: enhancement, auto merge, ready to review, waiting-review, AI review first

#1606 [ISSUE #1605]🚀Add a pop consume example🔥
  rocketmq-client/Cargo.toml
  rocketmq-client/examples/consumer/pop_consumer.rs
Labels: feature, auto merge, ready to review, waiting-review, AI review first

#1608 [ISSUE #1607]♻️Remove Rebalance trait useless method remove_unnecessary_pop_message_queue_pop🔥
  rocketmq-client/src/consumer/consumer_impl/re_balance.rs
  rocketmq-client/src/consumer/consumer_impl/re_balance/rebalance_push_impl.rs
Labels: refactor, auto merge, ready to review, waiting-review, AI review first

#1609 [ISSUE #1599]🚀Rocketmq-client support Pop consumer-2📝
  rocketmq-client/src/consumer/consumer_impl/default_mq_push_consumer_impl.rs
  rocketmq-client/src/consumer/consumer_impl/re_balance.rs
  rocketmq-client/src/consumer/consumer_impl/re_balance/rebalance_push_impl.rs
Labels: feature, auto merge, ready to review, waiting-review, AI review first

#1613 [ISSUE #1612]⚡️Optimize ConsumeMessageDirectlyResult struct🔥
  rocketmq-remoting/src/protocol/body/consume_message_directly_result.rs
Labels: enhancement, auto merge, ready to review, waiting-review, AI review first

#1621 [ISSUE #1381]🚀Add GroupForbidden
  rocketmq-remoting/src/protocol/subscription.rs
  rocketmq-remoting/src/protocol/subscription/group_forbidden.rs
Labels: feature, approved, auto merge, ready to review, waiting-review, AI review first

#1623 [ISSUE #1615]Implement ConsumeMessageConcurrentlyService#consumeMessageDirectly
  rocketmq-client/src/consumer/consumer_impl/consume_message_concurrently_service.rs
  rocketmq-common/src/common/message/message_client_ext.rs
Labels: feature, approved, auto merge, ready to review, waiting-review, AI review first

#1625 [ISSUE #1624]🚀Replace ClientRemotingProcessor's WeakArcMut<MQClientInstance> with ArcMut<MQClientInstance>🔥
  rocketmq-client/src/factory/mq_client_instance.rs
  rocketmq-client/src/implementation/client_remoting_processor.rs
Labels: enhancement, auto merge, ready to review, waiting-review, AI review first

#1626 [ISSUE #1509]Refactor BrokerHeartbeatRequestHeader with derive marco RequestHeaderCodec
  rocketmq-remoting/src/protocol/header/namesrv/broker_request.rs
Labels: refactor, approved, auto merge, ready to review, waiting-review, AI review first

#1628 [ISSUE #1616]🚀Implement ConsumeMessageOrderlyService#consumeMessageDirectly🔥
  rocketmq-client/src/consumer/consumer_impl/consume_message_orderly_service.rs
Labels: feature, auto merge, ready to review, waiting-review, AI review first

#1629 [ISSUE #1627]🚀Replace Client consumer's WeakArcMut<DefaultMQPushConsumerImpl> with ArcMut<DefaultMQPushConsumerImpl>🔥
  rocketmq-client/src/consumer/consumer_impl/consume_message_concurrently_service.rs
  rocketmq-client/src/consumer/consumer_impl/consume_message_orderly_service.rs
  rocketmq-client/src/consumer/consumer_impl/consume_message_pop_concurrently_service.rs
  rocketmq-client/src/consumer/consumer_impl/consume_message_pop_orderly_service.rs
  rocketmq-client/src/consumer/consumer_impl/consume_message_service.rs
  rocketmq-client/src/consumer/consumer_impl/default_mq_push_consumer_impl.rs
  rocketmq-client/src/consumer/consumer_impl/pop_process_queue.rs
  rocketmq-client/src/consumer/consumer_impl/process_queue.rs
  rocketmq-client/src/consumer/consumer_impl/re_balance/rebalance_push_impl.rs
  rocketmq-client/src/consumer/default_mq_push_consumer.rs
  rocketmq-client/src/consumer/mq_consumer_inner.rs
  rocketmq-client/src/consumer/pull_callback.rs
Labels: enhancement, auto merge, ready to review, waiting-review, AI review first

#1630 [ISSUE #1617]🚀Implement ConsumeMessagePopConcurrentlyService#consumeMessageDirectly🔥
  rocketmq-client/src/consumer/consumer_impl/consume_message_pop_concurrently_service.rs
  rocketmq-client/src/consumer/consumer_impl/default_mq_push_consumer_impl.rs
Labels: feature, auto merge, ready to review, waiting-review, AI review first

#1632 [ISSUE #1631]Remove useless code
  rocketmq-client/src/consumer/consumer_impl/default_mq_push_consumer_impl.rs
Labels: enhancement, approved, auto merge, ready to review, waiting-review, AI review first

#1633 [ISSUE #1618]🚀Implement ConsumeMessagePopOrderlyService#consumeMessageDirectly🔥
  rocketmq-client/src/consumer/consumer_impl/consume_message_pop_orderly_service.rs
  rocketmq-client/src/consumer/consumer_impl/default_mq_push_consumer_impl.rs
Labels: feature, auto merge, ready to review, waiting-review, AI review first

#1635 [ISSUE #1634]📝Add doc for ConsumeMessageServiceTrait trait🔥
  rocketmq-client/src/consumer/consumer_impl/consume_message_service.rs
Labels: documentation, auto merge, ready to review, waiting-review, AI review first

#1636 [ISSUE #1378] Add BrokerStatsData
  rocketmq-remoting/src/protocol/body.rs
  rocketmq-remoting/src/protocol/body/broker_item.rs
  rocketmq-remoting/src/protocol/subscription.rs
  rocketmq-remoting/src/protocol/subscription/broker_stats_data.rs
Labels: feature, approved, auto merge, ready to review, waiting-review, AI review first

#1641 [Issue #1295] Rocketmq-client supports the AllocateMessageQueueStrategy algorithm-AllocateMessageQueueByMachineRoom
  rocketmq-client/src/consumer/rebalance_strategy.rs
  rocketmq-client/src/consumer/rebalance_strategy/allocate_message_queue_by_machine_room.rs
Labels: approved, auto merge, ready to review, waiting-review, AI review first

#1643 [ISSUE #1642]♻️Refactor AckMessageProcessor#process_request method signature🔥
  rocketmq-broker/src/processor/ack_message_processor.rs
Labels: refactor, auto merge, ready to review, waiting-review, AI review first

#1645 [ISSUE #1644]♻️Refactor PollingInfoProcessor#process_request method signature🔥
  rocketmq-broker/src/processor/polling_info_processor.rs
Labels: refactor, auto merge, ready to review, waiting-review, AI review first

#1647 [ISSUE #1646]♻️Refactor PeekMessageProcessor#process_request method signature🔥
  rocketmq-broker/src/processor/peek_message_processor.rs
Labels: refactor, auto merge, ready to review, waiting-review, AI review first

#1650 [Issue #1292] Rocketmq-client supports the AllocateMessageQueueStrategy algorithm-AllocateMachineRoomNearby
  rocketmq-client/src/consumer/rebalance_strategy.rs
  rocketmq-client/src/consumer/rebalance_strategy/allocate_message_queue_by_machine_room_nearby.rs
Labels: feature, approved, auto merge, ready to review, waiting-review, AI review first

#1652 [ISSUE #1649]🚀Implement ExtraInfoUtil for rust🔥
  rocketmq-common/src/common/key_builder.rs
  rocketmq-remoting/src/protocol/header.rs
  rocketmq-remoting/src/protocol/header/extra_info_util.rs
  rocketmq-remoting/src/remoting_error.rs
Labels: feature, auto merge, ready to review, waiting-review, AI review first

#1651 [Issue #1294] Rocketmq-client supports the AllocateMessageQueueStrategy algorithm-AllocateMessageQueueByConfig
  rocketmq-client/src/consumer/rebalance_strategy.rs
  rocketmq-client/src/consumer/rebalance_strategy/allocate_message_queue_by_config.rs
Labels: feature, approved, auto merge, ready to review, waiting-review, AI review first

#1654 [ISSUE #1648]🚀Add ConsumeRequest for ConsumeMessagePopConcurrentlyService🔥
  rocketmq-client/src/consumer/consumer_impl/consume_message_pop_concurrently_service.rs
Labels: enhancement, feature, wip, auto merge, ready to review, waiting-review, AI review first

#1656 [ISSUE #1655]🚀Implement ConsumeMessagePopConcurrentlyService#process_consume_result logic🔥
  rocketmq-client/src/consumer/consumer_impl/consume_message_pop_concurrently_service.rs
  rocketmq-client/src/consumer/consumer_impl/default_mq_push_consumer_impl.rs
Labels: feature, auto merge, ready to review, waiting-review, AI review first

#1660 [ISSUE #1659]🚀Add AckStatus enum🔥
  rocketmq-client/src/consumer.rs
  rocketmq-client/src/consumer/ack_status.rs
Labels: feature, auto merge, ready to review, waiting-review, AI review first

#1661 [ISSUE #1658]🚀Add AckResult struct🔥
  rocketmq-client/src/consumer.rs
  rocketmq-client/src/consumer/ack_result.rs
Labels: feature, auto merge, ready to review, waiting-review, AI review first

#1662 [ISSUE #1657]🚀Add AckCallback trait🔥
  rocketmq-client/src/consumer.rs
  rocketmq-client/src/consumer/ack_callback.rs
Labels: feature, auto merge, ready to review, waiting-review, AI review first

#1663 [ISSUE #1648]🚀Add ConsumeRequest for ConsumeMessagePopConcurrentlyService🔥
  rocketmq-client/src/consumer/consumer_impl/consume_message_pop_concurrently_service.rs
  rocketmq-client/src/consumer/consumer_impl/default_mq_push_consumer_impl.rs
Labels: enhancement, feature, wip, auto merge, ready to review, waiting-review, AI review first

#1665 [ISSUE #1664]🚀Add ChangeInvisibleTimeRequestHeader struct🔥
  rocketmq-remoting/src/protocol/header.rs
  rocketmq-remoting/src/protocol/header/change_invisible_time_request_header.rs
Labels: feature, auto merge, ready to review, waiting-review, AI review first

#1668 [ISSUE #1664]🚀Add ChangeInvisibleTimeResponseHeader struct🔥
  rocketmq-remoting/src/protocol/header.rs
  rocketmq-remoting/src/protocol/header/change_invisible_time_response_header.rs
Labels: feature, auto merge, ready to review, waiting-review, AI review first

#1669 [ISSUE #1666]🚀Implement MQClientAPIImpl#changeInvisibleTimeAsync method logic🔥
  rocketmq-client/src/consumer/ack_result.rs
  rocketmq-client/src/implementation/mq_client_api_impl.rs
  rocketmq-remoting/src/protocol/header.rs
Labels: feature, auto merge, ready to review, waiting-review, AI review first

#1672 [ISSUE #1670]🚀Implement DefaultMQPushConsumerImpl#change_pop_invisible_time_async method logic🔥
  rocketmq-client/src/consumer/consumer_impl/default_mq_push_consumer_impl.rs
  rocketmq-client/src/implementation/mq_client_api_impl.rs
Labels: feature, auto merge, ready to review, waiting-review, AI review first

#1673 [ISSUE #1671]⚡️Optimize MQClientInstance#find_broker_address_in_subscribe method signature🔥
  rocketmq-client/src/consumer/consumer_impl/pull_api_wrapper.rs
  rocketmq-client/src/consumer/consumer_impl/re_balance/rebalance_impl.rs
  rocketmq-client/src/consumer/consumer_impl/re_balance/rebalance_push_impl.rs
  rocketmq-client/src/consumer/store/remote_broker_offset_store.rs
  rocketmq-client/src/factory/mq_client_instance.rs
Labels: enhancement, auto merge, ready to review, waiting-review, AI review first

#1683 [ISSUE #1680]♻️Refactor ChangeInvisibleTimeProcessor handle logic🍻
  rocketmq-broker/src/processor/change_invisible_time_processor.rs
Labels: refactor, auto merge, ready to review, waiting-review, AI review first

#1682 [ISSUE #1679]🚀Add PopCheckPoint struct🍻
  rocketmq-store/src/lib.rs
  rocketmq-store/src/pop.rs
  rocketmq-store/src/pop/pop_check_point.rs
Labels: feature, auto merge, ready to review, waiting-review, AI review first

#1686 [ISSUE #1684]🧪Add unit test for PopAckConstants
  rocketmq-common/src/common/pop_ack_constants.rs
Labels: approved, auto merge, ready to review, testing, waiting-review, AI review first

#1688 [ISSUE #1687]♻️Refactor PopMessageProcessor method handle error
  rocketmq-broker/src/processor/pop_message_processor.rs
Labels: refactor, auto merge, ready to review, waiting-review, AI review first

#1690 [ISSUE #1681]🚀Implement ChangeInvisibleTimeProcessor logic🍻
  rocketmq-broker/src/broker_runtime.rs
  rocketmq-broker/src/processor.rs
  rocketmq-broker/src/processor/change_invisible_time_processor.rs
Labels: feature, auto merge, ready to review, waiting-review, AI review first

#1700 [ISSUE #1695]🍻Add EscapeBridge struct for rust🚀
  rocketmq-broker/src/failover.rs
  rocketmq-broker/src/failover/escape_bridge.rs
  rocketmq-broker/src/lib.rs
Labels: feature, rust, auto merge, ready to review, waiting-review, AI review first

#1702 [ISSUE #1696]🚀EscapeBridge supports putMessage🍻
  rocketmq-broker/src/failover/escape_bridge.rs
  rocketmq-common/src/common/broker/broker_config.rs
Labels: feature, auto merge, ready to review, waiting-review, AI review first

#1701 [ISSUE #1689]Adding inline for PutMessageResult methods
  rocketmq-store/src/base/message_result.rs
Labels: enhancement, auto merge, ready to review, waiting-review, AI review first, Difficulty level/Easy

#1706 [ISSUE #1705]♻️Refactor QueueFilter trait
  rocketmq-client/src/producer/producer_impl/queue_filter.rs
Labels: refactor, auto merge, ready to review, waiting-review, AI review first

#1707 [ISSUE #1703]⚡️ Optimize TopicPublishInfo some method logic🔥
  rocketmq-client/src/latency/mq_fault_strategy.rs
  rocketmq-client/src/producer/producer_impl/topic_publish_info.rs
Labels: enhancement, refactor, wip, auto merge, ready to review, waiting-review, AI review first, Difficulty level/Moderate

#1708 [ISSUE #1697]🚀EscapeBridge supports putMessageToRemoteBroker🔥
  rocketmq-broker/src/failover/escape_bridge.rs
  rocketmq-broker/src/out_api/broker_outer_api.rs
Labels: feature, auto merge, ready to review, waiting-review, AI review first

#1712 [ISSUE #1709]🚀Implement BrokerOuterAPI#send_message_to_specific_broker logic🔥
  rocketmq-broker/src/failover/escape_bridge.rs
  rocketmq-broker/src/out_api/broker_outer_api.rs
  rocketmq-remoting/src/protocol/header/message_operation_header/send_message_request_header_v2.rs
Labels: enhancement, feature, auto merge, ready to review, waiting-review, AI review first, Difficulty level/Moderate

#1713 [ISSUE #1698]🚀EscapeBridge supports asyncPutMessage
  rocketmq-broker/src/failover/escape_bridge.rs
Labels: feature, auto merge, ready to review, waiting-review, AI review first

#1715 [ISSUE #1699]🚀EscapeBridge supports putMessageToSpecificQueue
  rocketmq-broker/src/failover/escape_bridge.rs
Labels: feature, auto merge, ready to review, waiting-review, AI review first

#1717 [ISSUE #1714]⚡️Add #[inline] for SendResult struct methods
  rocketmq-client/src/producer/send_result.rs
Labels: enhancement, approved, auto merge, ready to review, waiting-review, AI review first, Difficulty level/Easy

#1719 [ISSUE #1718]📝Add rocektmq-rust icon
  README.md
  resources/Rocketmq-rust.png
Labels: documentation, auto merge, ready to review, waiting-review, AI review first

#1716 [ISSUE #1694]🚀Rocketmq-broker supports EscapeBridge functions🔥
  rocketmq-broker/src/broker_runtime.rs
  rocketmq-broker/src/failover/escape_bridge.rs
Labels: feature, auto merge, ready to review, waiting-review, AI review first

#1722 [ISSUE #1721]⚡️Optimize EscapeBridge struct logic
  rocketmq-broker/src/failover/escape_bridge.rs
Labels: enhancement, wip, auto merge, ready to review, waiting-review, AI review first

#1724 [ISSSUE #1723]🚀Add AckMsg struct🍻
  rocketmq-store/src/pop.rs
  rocketmq-store/src/pop/ack_msg.rs
Labels: feature, auto merge, ready to review, waiting-review, AI review first, Difficulty level/Easy

#1726 [ISSUE #1725]🚀Add BatchAckMsg struct for rust✨
  rocketmq-store/src/pop.rs
  rocketmq-store/src/pop/batch_ack_msg.rs
Labels: feature, auto merge, ready to review, waiting-review, AI review first, Difficulty level/Easy

#1728 [ISSUE #1727]🍻Add PopBufferMergeService struct for rust 🚀
  rocketmq-broker/src/processor.rs
  rocketmq-broker/src/processor/processor_service.rs
  rocketmq-broker/src/processor/processor_service/pop_buffer_merge_service.rs
Labels: feature, auto merge, ready to review, waiting-review, AI review first

#1731 [ISSUE #1729]🚀Implement PopMessageProcessor static Method
  rocketmq-broker/src/processor/pop_message_processor.rs
Labels: feature, auto merge, ready to review, waiting-review, AI review first

#1732 [ISSUE #1691]🍻Implement ChangeInvisibleTimeProcessor#ack_origin method🚀
  rocketmq-broker/src/broker_runtime.rs
  rocketmq-broker/src/processor/change_invisible_time_processor.rs
  rocketmq-broker/src/processor/processor_service/pop_buffer_merge_service.rs
  rocketmq-store/src/pop/ack_msg.rs
  rocketmq-store/src/pop/batch_ack_msg.rs
  rocketmq-store/src/stats/broker_stats_manager.rs
Labels: feature, auto merge, ready to review, waiting-review, AI review first, Difficulty level/Moderate

#1733 [ISSUE #1730]⚡️Optimize Replace String with CheetahString in PopCheckPoint
  rocketmq-broker/src/processor/pop_message_processor.rs
  rocketmq-store/src/pop/pop_check_point.rs
Labels: enhancement, approved, auto merge, ready to review, waiting-review, AI review first, Difficulty level/Easy

#1734 [ISSUE #1692]🍻Implement ChangeInvisibleTimeProcessor#append_check_point method🚀
  rocketmq-broker/src/processor/change_invisible_time_processor.rs
  rocketmq-common/src/common/broker/broker_config.rs
  rocketmq-store/src/pop/pop_check_point.rs
Labels: feature, auto merge, ready to review, waiting-review, AI review first, Difficulty level/Moderate

#1736 [ISSUE #1735]🚀Implement TimedLock function
  rocketmq-broker/src/processor/pop_message_processor.rs
Labels: enhancement, feature, auto merge, ready to review, waiting-review, AI review first, Difficulty level/Moderate

#1738 [ISSUE #1737]💥Implement QueueLockManager function🚀
  rocketmq-broker/src/processor/pop_message_processor.rs
Labels: feature, auto merge, ready to review, waiting-review, AI review first, Difficulty level/Moderate

#1740 [ISSUE #1693]🚀Implement ChangeInvisibleTimeProcessor#process_change_invisible_time_for_order method
  rocketmq-broker/src/broker_runtime.rs
  rocketmq-broker/src/offset/manager/consumer_order_info_manager.rs
  rocketmq-broker/src/processor/change_invisible_time_processor.rs
  rocketmq-broker/src/processor/pop_message_processor.rs
Labels: feature, auto merge, ready to review, waiting-review, AI review first, Difficulty level/Moderate

#1741 [ISSUE #1739]🚀Implement ConsumerOrderInfoManager#update_next_visible_time method logic
  rocketmq-broker/src/offset/manager/consumer_order_info_manager.rs
Labels: feature, auto merge, ready to review, waiting-review, AI review first, Difficulty level/Moderate

#1744 [ISSUE #1742]⚡️Enhancement OrderInfo struct add some methods
  rocketmq-broker/src/offset/manager/consumer_order_info_manager.rs
Labels: enhancement, auto merge, ready to review, waiting-review, AI review first

#1750 [ISSUE #1747]🤡Implement netty Timer for rust trait🚀
  rocketmq/src/lib.rs
  rocketmq/src/netty_rust.rs
  rocketmq/src/netty_rust/timeout.rs
  rocketmq/src/netty_rust/timer.rs
  rocketmq/src/netty_rust/timer_task.rs
Labels: feature, rust, auto merge, ready to review, waiting-review, AI review first, Difficulty level/Easy

#1751 [ISSUE #1746]🍻Implement netty Timeout for rust trait🤡
  rocketmq/src/netty_rust/timeout.rs
Labels: feature, rust, auto merge, ready to review, waiting-review, AI review first, Difficulty level/Easy

#1753 [ISSUE #1752]📝Update Timer trait doc
  rocketmq/src/netty_rust/timer.rs
Labels: documentation, auto merge, ready to review, waiting-review, AI review first

#1754 [ISSUE #1748]🚀Implement netty TimerTask for rust trait🔥
  rocketmq/src/netty_rust/timer_task.rs
Labels: feature, rust, auto merge, ready to review, waiting-review, AI review first, Difficulty level/Easy

#1761 [ISSUE #1759]🚀Implement netty HashedWheelTimeout for rust-1🔥
  rocketmq/src/lib.rs
  rocketmq/src/netty_rust.rs
  rocketmq/src/netty_rust/washed_wheel_timer.rs
Labels: feature, rust, auto merge, ready to review, waiting-review, AI review first, Difficulty level/Moderate

#1764 [ISSUE #1762]🚀Optimize ConsumerOrderInfoManager encode and decode🔥
  rocketmq-broker/src/offset/manager/consumer_order_info_manager.rs
Labels: enhancement, auto merge, ready to review, waiting-review, AI review first

#1765 [ISSUE #1763]🚀Implement ConsumerOrderInfoManager#auto_clean method function🔥
  rocketmq-broker/src/broker_runtime.rs
  rocketmq-broker/src/offset/manager/consumer_order_info_manager.rs
  rocketmq-broker/src/processor/change_invisible_time_processor.rs
  rocketmq-broker/src/subscription/manager/subscription_group_manager.rs
  rocketmq-common/src/common/config.rs
Labels: feature, rust, auto merge, ready to review, waiting-review, AI review first, Difficulty level/Moderate

#1767 [ISSUE #1766]⚡️Replace ConsumerOrderInfoWrapper String with CheetahString🔥
  rocketmq-broker/src/offset/manager/consumer_order_info_manager.rs
Labels: enhancement, auto merge, ready to review, waiting-review, AI review first

#1769 [ISSUE #1768]📝Add Doc for RebalanceService struct🔥
  rocketmq-client/src/consumer/consumer_impl/re_balance/rebalance_service.rs
Labels: documentation, auto merge, ready to review, waiting-review, AI review first

#1771 [ISSUE #1770]🤡Optimize MQConsumerInnerImpl struct method logic🔥
  rocketmq-client/src/consumer/consumer_impl/default_mq_push_consumer_impl.rs
  rocketmq-client/src/consumer/consumer_impl/re_balance/rebalance_service.rs
  rocketmq-client/src/consumer/mq_consumer_inner.rs
Labels: enhancement, rust, auto merge, ready to review, waiting-review, AI review first, Difficulty level/Easy

#1774 [ISSUE #1773]🤡Optimize RebalanceImpl#try_query_assignment method logic and simply code🔥
  rocketmq-client/src/consumer/consumer_impl/re_balance/rebalance_impl.rs
Labels: enhancement, auto merge, ready to review, waiting-review, AI review first

#1776 [ISSUE #1775]🤡Simply MQClientInstance#query_assignment method code and add doc for method🔥
  rocketmq-client/src/factory/mq_client_instance.rs
Labels: enhancement, auto merge, ready to review, waiting-review, AI review first

#1778 [ISSUE #1777]🤡Optimize RebalanceImpl#get_rebalance_result_from_broker method and add doc for method🔥
  rocketmq-client/src/consumer/consumer_impl/re_balance/rebalance_impl.rs
Labels: enhancement, auto merge, ready to review, waiting-review, AI review first

#1780 [ISSUE #1779]🤡Optimize RebalanceImpl#update_message_queue_assignment method🔥
  rocketmq-client/src/consumer/consumer_impl/re_balance/rebalance_impl.rs
Labels: enhancement, auto merge, ready to review, waiting-review, AI review first

#1782 [ISSUE #1781]🤡Optimize RebalancePushImpl#dispatch_pop_pull_request logic🔥
  rocketmq-client/src/consumer/consumer_impl/re_balance/rebalance_push_impl.rs
Labels: enhancement, auto merge, ready to review, waiting-review, AI review first

#1784 [ISSUE #1783]🤡Optimize RebalancePushImpl#dispatch_pull_request unwrap logic🔥
  rocketmq-client/src/consumer/consumer_impl/re_balance/rebalance_push_impl.rs
Labels: enhancement, auto merge, ready to review, waiting-review, AI review first

#1787 Adding #[inline] for MQConsumerInnerImpl methods
  rocketmq-client/src/consumer/mq_consumer_inner.rs
Labels: enhancement, approved, auto merge, ready to review, waiting-review, AI review first, Difficulty level/Easy

#1789 Adding #[inline] for PopRequest method
  rocketmq-client/src/consumer/consumer_impl/pop_request.rs
Labels: enhancement, approved, auto merge, ready to review, waiting-review, AI review first, Difficulty level/Easy

#1792 [ISSUE #1791]🤡Add PopStatus struct for rust🔥
  rocketmq-client/src/consumer.rs
  rocketmq-client/src/consumer/pop_status.rs
Labels: feature, rust, auto merge, ready to review, waiting-review, AI review first, Difficulty level/Easy

#1794 [ISSUE #1788]🤡Add PopCallback trait🔥
  rocketmq-client/src/consumer.rs
  rocketmq-client/src/consumer/pop_callback.rs
Labels: feature, rust, auto merge, ready to review, waiting-review, AI review first, Difficulty level/Easy

#1796 [ISSUE #1795]🤡Change PopCallback signature🔥
  rocketmq-client/src/consumer/pop_callback.rs
Labels: enhancement, auto merge, ready to review, waiting-review, AI review first

#1797 [ISSUE #1785]🤡Implement DefaultMQPushConsumerImpl#pop_message function🚀
  rocketmq-client/src/consumer/consumer_impl/consume_message_service.rs
  rocketmq-client/src/consumer/consumer_impl/default_mq_push_consumer_impl.rs
  rocketmq-client/src/consumer/consumer_impl/pop_process_queue.rs
  rocketmq-client/src/consumer/consumer_impl/pop_request.rs
  rocketmq-client/src/consumer/consumer_impl/pull_api_wrapper.rs
  rocketmq-client/src/consumer/pop_callback.rs
Labels: feature, auto merge, ready to review, waiting-review, AI review first

#1803 [ISSUE #1802]🤡Add PopMessageResponseHeader struct for rust🚀
  rocketmq-remoting/src/protocol/header.rs
  rocketmq-remoting/src/protocol/header/pop_message_response_header.rs
Labels: feature, rust, auto merge, ready to review, waiting-review, AI review first, Difficulty level/Easy

#1806 [ISSUE #1804]🚀Implement PullAPIWrapper#pop_async method logic
  rocketmq-client/src/consumer.rs
  rocketmq-client/src/consumer/consumer_impl/pull_api_wrapper.rs
  rocketmq-client/src/implementation/mq_client_api_impl.rs
Labels: feature, rust, auto merge, ready to review, waiting-review, AI review first

#1808 [ISSUE #1805]🚀Implement MQClientAPIImpl#pop_message_async method logic🍻
  rocketmq-client/src/implementation/mq_client_api_impl.rs
Labels: feature, auto merge, ready to review, waiting-review, AI review first

#1807 [ISSUE #1743]Remove useless import in escape_bridge.rs test mode
  rocketmq-broker/src/failover/escape_bridge.rs
Labels: enhancement, approved, auto merge, ready to review, testing, waiting-review, AI review first, Difficulty level/Easy

#1810 [ISSUE #1809]🍻Implement MQClientAPIImpl#process_pop_response method logic
  rocketmq-client/src/consumer/pop_result.rs
  rocketmq-client/src/implementation/mq_client_api_impl.rs
  rocketmq-remoting/src/protocol/header/pop_message_response_header.rs
Labels: feature, auto merge, ready to review, waiting-review, AI review first

#1814 [ISSUE #1811]🤡Implement DefaultMQPushConsumerImpl#process_pop_result method function🚀
  rocketmq-client/src/consumer/consumer_impl/default_mq_push_consumer_impl.rs
  rocketmq-client/src/consumer/pop_callback.rs
  rocketmq-client/src/consumer/pop_result.rs
  rocketmq-client/src/implementation/mq_client_api_impl.rs
Labels: feature, rust, auto merge, ready to review, waiting-review, AI review first

#1816 [ISSUE #1815]🚀Implement ConsumeMessagePopServiceGeneral#submit_pop_co…
  rocketmq-client/src/consumer/consumer_impl/consume_message_service.rs
Labels: feature, auto merge, ready to review, waiting-review, AI review first

#1819 [ISSUE #1817]🚀Implement ConsumeMessagePopConcurrentlyService#submit_pop_consume_request
  rocketmq-client/src/consumer/consumer_impl/consume_message_concurrently_service.rs
  rocketmq-client/src/consumer/consumer_impl/consume_message_orderly_service.rs
  rocketmq-client/src/consumer/consumer_impl/consume_message_pop_concurrently_service.rs
  rocketmq-client/src/consumer/consumer_impl/consume_message_pop_orderly_service.rs
  rocketmq-client/src/consumer/consumer_impl/consume_message_service.rs
Labels: feature, auto merge, ready to review, waiting-review, AI review first

#1821 [ISSUE #1820]Add unsupport attention for submit_pop_consume_request
  rocketmq-client/src/consumer/consumer_impl/consume_message_concurrently_service.rs
  rocketmq-client/src/consumer/consumer_impl/consume_message_orderly_service.rs
Labels: enhancement, auto merge, ready to review, waiting-review, AI review first

#1823 [ISSUE #1822] ConsumeMessageServiceTrait trait provides default implementations of some methods
  rocketmq-client/src/consumer/consumer_impl/consume_message_concurrently_service.rs
  rocketmq-client/src/consumer/consumer_impl/consume_message_orderly_service.rs
  rocketmq-client/src/consumer/consumer_impl/consume_message_pop_concurrently_service.rs
  rocketmq-client/src/consumer/consumer_impl/consume_message_pop_orderly_service.rs
  rocketmq-client/src/consumer/consumer_impl/consume_message_service.rs
Labels: enhancement, auto merge, ready to review, waiting-review, AI review first

#1824 [ISSUE #1818] Implement ConsumeMessagePopOrderlyService#submit_pop_consume_request
  rocketmq-client/src/consumer/consumer_impl/consume_message_pop_orderly_service.rs
  rocketmq-client/src/consumer/consumer_impl/pop_process_queue.rs
Labels: feature, auto merge, ready to review, waiting-review, AI review first

#1826 [ISSUE #1825]🧑‍💻Add AckMessageRequestHeader for rust
  rocketmq-remoting/src/protocol/header.rs
  rocketmq-remoting/src/protocol/header/ack_message_request_header.rs
Labels: feature, rust, auto merge, ready to review, waiting-review, AI review first, Difficulty level/Easy

#1827 [ISSUE #1813]🚀Implement DefaultMQPushConsumerImpl#ack_async method
  rocketmq-client/src/consumer/consumer_impl/default_mq_push_consumer_impl.rs
Labels: feature, wip, rust, auto merge, ready to review, waiting-review, AI review first

#1831 [ISSUE #1830]🐰Add BatchAck struct for rust🚀
  Cargo.lock
  rocketmq-remoting/Cargo.toml
  rocketmq-remoting/src/protocol/body.rs
  rocketmq-remoting/src/protocol/body/batch_ack.rs
Labels: feature, auto merge, ready to review, waiting-review, AI review first

#1832 [ISSUE #1829]🌽Add BatchAckMessageRequestBody struct for rust🚀
  rocketmq-remoting/src/protocol/body.rs
  rocketmq-remoting/src/protocol/body/batch_ack_message_request_body.rs
Labels: feature, rust, auto merge, ready to review, waiting-review, AI review first
