Repository mxsm/rocketmq-rust, pull requests merged in 2025-02, with the labels that each got.

#2462 [ISSUE #2461]📝Add Architecture doc💫
  rocketmq-doc/_data/navigation.yml
  rocketmq-doc/_docs/01-architecture.md
  rocketmq-doc/_docs/02-quick-start-guide.md
  rocketmq-doc/_pages/home.md
Labels: documentation📝, auto merge, ready to review, waiting-review, AI review first

#2464 [ISSUE #2463]🔨Update jekyll-gh-pages.yml action
  .github/workflows/jekyll-gh-pages.yml
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first

#2466 [ISSUE #2465]🔨Update jekyll-gh-pages.yml action
  .github/workflows/jekyll-gh-pages.yml
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first

#2468 [ISSUE #2467]🔨Update jekyll-gh-pages.yml action
  .github/workflows/jekyll-gh-pages.yml
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first

#2470 [ISSUE #2469]Update jekyll-gh-pages.yml
  .github/workflows/jekyll-gh-pages.yml
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first

#2472 [ISSUE #2471]📝Add what is rocketmq-rust doc💫
  rocketmq-doc/_data/navigation.yml
  rocketmq-doc/_docs/01-what-is-rocketmq-rust.md
Labels: documentation📝, auto merge, ready to review, waiting-review, AI review first

#2474 [ISSUE #2473]🔨Update Algolia crawler name
  .github/workflows/jekyll-gh-pages.yml
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first

#2476 [ISSUE #2475]📝Add Components doc💫
  rocketmq-doc/_data/navigation.yml
  rocketmq-doc/_docs/01-components.md
Labels: documentation📝, auto merge, ready to review, waiting-review, AI review first

#2478 [ISSUE #2477] Update jekyll-gh-pages.yml action
  .github/workflows/jekyll-gh-pages.yml
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first

#2480 [ISSUE #2479]📝Add Run RocketMQ Rust locally doc💫
  rocketmq-doc/_data/navigation.yml
  rocketmq-doc/_docs/01-run-rocketmq-rust-locally.md
Labels: documentation📝, auto merge, ready to review, waiting-review, AI review first

#2483 [ISSUE #2482]🔨Update jekyll-gh-pages.yml
  .github/workflows/jekyll-gh-pages.yml
Labels: bug🐛, auto merge, ready to review, waiting-review, AI review first

#2484 [ISSUE #2481]📝Add Run RocketMQ Rust with Docker doc💫
  rocketmq-doc/_data/navigation.yml
  rocketmq-doc/_docs/01-run-rocketmq-rust-docker.md
Labels: documentation📝, auto merge, ready to review, waiting-review, AI review first

#2486 Update jekyll-gh-pages.yml
  .github/workflows/jekyll-gh-pages.yml
Labels: auto merge, ready to review, waiting-review, AI review first

#2487 [ISSUE #2485]📝Add Run RocketMQ with Kubernetes doc💫
  rocketmq-doc/_data/navigation.yml
  rocketmq-doc/_docs/01-run-rocketmq-rust-k8s.md
Labels: documentation📝, auto merge, ready to review, waiting-review, AI review first

#2488 Update jekyll-gh-pages.yml
  .github/workflows/jekyll-gh-pages.yml
Labels: auto merge, ready to review, waiting-review, AI review first

#2490 [ISSUE #2489]📝Update algolia index name💫
  rocketmq-doc/_config.yml
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first

#2491 Update jekyll-gh-pages.yml
  .github/workflows/jekyll-gh-pages.yml
Labels: auto merge, ready to review, waiting-review, AI review first

#2492 Update jekyll-gh-pages.yml
  .github/workflows/jekyll-gh-pages.yml
Labels: auto merge, ready to review, waiting-review, AI review first

#2494 [ISSUE #2493]📝Add rocketmq-rust architecture💫
  README.md
  resources/architecture.excalidraw
  resources/architecture.png
Labels: documentation📝, auto merge, ready to review, waiting-review, AI review first

#2496 [ISSUE #2495]📝Add rocketmq-rust architecture to home page💫
  rocketmq-doc/_pages/home.md
  rocketmq-doc/assets/images/architecture.png
Labels: documentation📝, auto merge, ready to review, waiting-review, AI review first

#2498 [ISSUE #2497]📝Add What’s Rocketmq Rust doc💫
  rocketmq-doc/_docs/01-what-is-rocketmq-rust.md
  rocketmq-doc/_docs/zh/01-what-is-rocketmq-rust.md
Labels: documentation📝, auto merge, ready to review, waiting-review, AI review first

#2500 [ISSUE #2499]📝Update What’s Rocketmq Rust doc zh path💫
  rocketmq-doc/_docs/zh/01-what-is-rocketmq-rust.md
Labels: documentation📝, auto merge, ready to review, waiting-review, AI review first

#2502 [ISSUE #2501]📝Typo Contribute Guide doc💫
  rocketmq-doc/_docs/19-contribute-guide.md
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first

#2505 [ISSUE #2504]🔥Enhancement AckMessageProcessor ack_orderly💫
  rocketmq-broker/src/processor/ack_message_processor.rs
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first, rocketmq-broker crate

#2507 [ISSUE #2506]🔥Implement PopMessageProcessor notify_message_arriving method💫
  rocketmq-broker/src/processor/pop_message_processor.rs
Labels: feature🚀, auto merge, ready to review, waiting-review, AI review first, rocketmq-broker crate

#2509 [ISSUE #2508]🔥Fix PopLongPollingService notify_message_arriving is none unwrap💫
  rocketmq-broker/src/long_polling/long_polling_service/pop_long_polling_service.rs
Labels: bug🐛, auto merge, ready to review, waiting-review, AI review first

#2511 [ISSUE #2510]🔥Add Rocketmq Rust Components doc💫
  rocketmq-doc/_config.yml
  rocketmq-doc/_docs/01-components.md
  rocketmq-doc/_docs/02-components.md
  rocketmq-doc/_docs/zh/02-components.md
  rocketmq-doc/assets/js/mermaid.js
Labels: documentation📝, auto merge, ready to review, waiting-review, AI review first

#2517 [ISSUE #2513]🔥Add Release doc💫
  rocketmq-doc/_data/navigation.yml
  rocketmq-doc/_pages/release-notes.md
  rocketmq-doc/_posts/2024-01-28-release-v0.1.0.md
  rocketmq-doc/_posts/2024-06-05-release-v0.2.0.md
  rocketmq-doc/_posts/2024-11-17-release-v0.3.0.md
Labels: documentation📝, auto merge, ready to review, waiting-review, AI review first

#2520 [ISSUE #2519]🔥Add Roadmap doc💫
  rocketmq-doc/_data/navigation.yml
  rocketmq-doc/_docs/03-roadmap.md
  rocketmq-doc/assets/images/rocektmq-rust-roadmap.png
Labels: documentation📝, auto merge, ready to review, waiting-review, AI review first

#2522 [ISSUE #2521]🔥Add header image for posts💫
  rocketmq-doc/_config.yml
  rocketmq-doc/_pages/release-notes.md
  rocketmq-doc/_posts/2024-01-28-release-v0.1.0.md
  rocketmq-doc/_posts/2024-06-05-release-v0.2.0.md
  rocketmq-doc/_posts/2024-11-17-release-v0.3.0.md
  rocketmq-doc/assets/images/release-note.jpg
  rocketmq-doc/assets/images/release.jpg
Labels: documentation📝, auto merge, ready to review, waiting-review, AI review first

#2523 [ISSUE #2521]📝Update README.md🔥
  README.md
Labels: documentation📝, auto merge, ready to review, waiting-review, AI review first

#2525 [ISSUE #2524]📝Update website doc🔥
  rocketmq-doc/_docs/01-architecture.md
  rocketmq-doc/_docs/01-run-rocketmq-rust-docker.md
  rocketmq-doc/_docs/01-run-rocketmq-rust-k8s.md
  rocketmq-doc/_docs/01-run-rocketmq-rust-locally.md
  rocketmq-doc/_docs/01-what-is-rocketmq-rust.md
  rocketmq-doc/_docs/02-components.md
  rocketmq-doc/_docs/02-quick-start-guide.md
  rocketmq-doc/_docs/19-contribute-guide.md
Labels: documentation📝, auto merge, ready to review, waiting-review, AI review first

#2532 [ISSUE #2531]⚡️Optimize QueryAssignmentProcessor do_load_balance🚀
  rocketmq-broker/src/processor/query_assignment_processor.rs
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first

#2535 [ISSUE #2534]🚀Optimize PopMessageProcessor some code🔥
  rocketmq-broker/src/filter/consumer_filter_data.rs
  rocketmq-broker/src/filter/expression_message_filter.rs
  rocketmq-broker/src/processor/pop_message_processor.rs
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first

#2537 [ISSUE #2536]🚀 Implement ExpressionMessageFilter is_matched_by_commit_log method 🔥
  Cargo.lock
  rocketmq-broker/src/filter.rs
  rocketmq-broker/src/filter/expression_message_filter.rs
  rocketmq-broker/src/filter/message_evaluation_context.rs
  rocketmq-common/Cargo.toml
  rocketmq-common/src/common/message/message_decoder.rs
  rocketmq-filter/Cargo.toml
  rocketmq-filter/src/expression/evaluation_context.rs
  rocketmq-store/src/filter.rs
Labels: feature🚀, auto merge, ready to review, waiting-review, AI review first, rocketmq-broker crate

#2538 [ISSUE ##2527]Remove ClientManageProcessor unused code
  rocketmq-broker/src/processor/client_manage_processor.rs
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first, rocketmq-broker crate

#2540 [ISSUE #2539]🚀Replace DefaultMappedFile get_committed_position load with Ordering::Relaxed to Ordering::Acquire 🔥
  rocketmq-store/src/log_file/mapped_file/default_mapped_file_impl.rs
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first

#2543 [ISSUE #2542]🔨Update package_publish_workspace.sh🔥
  distribution/package_publish_workspace.sh
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first

#2545 [ISSUE #2544]🔨Update package_publish_workspace.bat 🔥
  distribution/package_publish_workspace.bat
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first

#2547 [ISSUE #2546]🔨Fix package_publish_workspace.bat error🔥
  distribution/package_publish_workspace.bat
Labels: bug🐛, auto merge, ready to review, waiting-review, AI review first

#2549 [ISSUE #2548]🚀 DefaultMQAdminExt add create instance method🚧
  rocketmq-tools/src/admin/default_mq_admin_ext.rs
  rocketmq-tools/src/admin/default_mq_admin_ext_impl.rs
Labels: feature🚀, auto merge, ready to review, waiting-review, AI review first, rocketmq-tools crate

#2551 [ISSUE #2550]🚀Implement DefaultMQAdminExt start method🔥
  Cargo.lock
  rocketmq-client/src/admin.rs
  rocketmq-client/src/admin/default_mq_admin_ext_impl.rs
  rocketmq-client/src/admin/mq_admin_ext_async.rs
  rocketmq-client/src/admin/mq_admin_ext_async_inner.rs
  rocketmq-client/src/base/client_config.rs
  rocketmq-client/src/common.rs
  rocketmq-client/src/common/admin_tool_result.rs
  rocketmq-client/src/common/admin_tools_result_code_enum.rs
  rocketmq-client/src/factory/mq_client_instance.rs
  rocketmq-client/src/implementation.rs
  rocketmq-client/src/lib.rs
  rocketmq-example/examples/consumer/pop_consumer.rs
  rocketmq-tools/Cargo.toml
  rocketmq-tools/src/admin.rs
  rocketmq-tools/src/admin/common.rs
  rocketmq-tools/src/admin/default_mq_admin_ext.rs
  rocketmq-tools/src/tools_error.rs
Labels: feature🚀, auto merge, ready to review, waiting-review, AI review first, rocketmq-tools crate

#2553 [ISSUE #2552]🚀Implement DefaultMQAdminExt shutdown method🔥
  rocketmq-client/src/admin/default_mq_admin_ext_impl.rs
  rocketmq-client/src/admin/mq_admin_ext_async.rs
  rocketmq-client/src/factory/mq_client_instance.rs
  rocketmq-tools/src/admin/default_mq_admin_ext.rs
Labels: feature🚀, auto merge, ready to review, waiting-review, AI review first, rocketmq-tools crate

#2555 [ISSUE #2554]🚀Fix pop consumer can't start🔥
  rocketmq-client/src/admin/default_mq_admin_ext_impl.rs
  rocketmq-example/examples/consumer/pop_consumer.rs
  rocketmq-tools/src/admin/default_mq_admin_ext.rs
Labels: bug🐛, auto merge, ready to review, waiting-review, AI review first

#2557 [ISSUE #2556]🚀Implement DefaultMQAdminExt examine_topic_route_info method🔥
  rocketmq-client/src/admin/default_mq_admin_ext_impl.rs
  rocketmq-client/src/admin/mq_admin_ext_async.rs
  rocketmq-example/examples/consumer/pop_consumer.rs
  rocketmq-tools/src/admin/default_mq_admin_ext.rs
Labels: feature🚀, auto merge, ready to review, waiting-review, AI review first

#2559 [ISSUE #2558]🚀Remove MQAdminExtInnerImpl start and shutdown🔥
  rocketmq-client/src/admin/mq_admin_ext_async_inner.rs
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first

#2562 [ISSUE #2561]🚀Update rocketmq-tools crate category🔥
  rocketmq-tools/Cargo.toml
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first

#2564 [ISSUE #2561]📝Update rocketmq-rust version to 0.5.0 for next develop🔥
  Cargo.lock
  Cargo.toml
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first

#2566 [ISSUE #2565]📝Add v0.4.0 release note doc🔥
  rocketmq-doc/_posts/2025-02-16-release-v0.4.0.md
Labels: documentation📝, auto merge, ready to review, waiting-review, AI review first

#2568 [ISSUE #2567]📝Update Release note latest version🔥
  rocketmq-doc/_pages/release-notes.md
Labels: documentation📝, auto merge, ready to review, waiting-review, AI review first

#2570 [ISSUE #2569]📝Update relase v0.5.0 doc🔥
  rocketmq-doc/_posts/2025-02-16-release-v0.4.0.md
Labels: documentation📝, auto merge, ready to review, waiting-review, AI review first

#2574 [ISSUE #2573]Optimize package script
  distribution/package_publish_workspace.bat
  distribution/package_publish_workspace.sh
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first

#2575 [ISSUE #2503 ] RemotingCommand some methods add #[inline]
  rocketmq-remoting/src/protocol/remoting_command.rs
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first, Difficulty level/Easy, rocketmq-remoting crate

#2577 [ISSUE #2576]⚡️Optimize QueueLockManager shutdown🔥
  rocketmq-broker/src/processor/pop_message_processor.rs
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first

#2581 [ISSUE #2580]🚀TrackType implement Serialize and Deserialize
  Cargo.lock
  rocketmq-tools/Cargo.toml
  rocketmq-tools/src/admin/api/track_type.rs
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first

#2585 [Enhancement⚡️] Remove SendMessageProcessor useless code #2584
  rocketmq-broker/src/broker_runtime.rs
  rocketmq-broker/src/processor/send_message_processor.rs
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first, rocketmq-broker crate

#2587 [ISSUE #2586]🔨Update automerge.yml
  .github/workflows/automerge.yml
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first

#2591 [ISSUE #2582] MessageTrack supports Serialize and Deserialize
  rocketmq-tools/src/admin/api/message_track.rs
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first, rocketmq-tools crate

#2590 [ISSUE #1675]Optimize MessageListenerOrderly#consume_message method signature
  rocketmq-client/src/consumer/consumer_impl/consume_message_orderly_service.rs
  rocketmq-client/src/consumer/consumer_impl/consume_message_pop_orderly_service.rs
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first

#2599 [ISSUE #2598]🚀Optimize PopMessageProcessor pop_msg_from_queue🔥
  rocketmq-broker/src/processor/pop_message_processor.rs
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first, rocketmq-broker crate

#2602 [ISSUE #2601]🚀Optimize PopReviveService log print🔥
  rocketmq-broker/src/processor/processor_service/pop_revive_service.rs
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first

#2603 [ISSUE #2600]🐛QueryAssignmentProcessor request code not correct🔥
  rocketmq-broker/src/processor.rs
Labels: bug🐛, auto merge, ready to review, waiting-review, AI review first

#2605 [ISSUE #2604] Remove AdminBrokerProcessor unused code
  rocketmq-broker/src/processor/admin_broker_processor.rs
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first, rocketmq-broker crate

#2611 [ISSUE #2583] Optimize order_count_info String capacity
  rocketmq-broker/src/processor/pop_message_processor.rs
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first, rocketmq-broker crate

#2615 [ISSUE #2614]🐛Fix ConsumerGroupInfo#update_subscription deadlock
  rocketmq-broker/src/client/consumer_group_info.rs
Labels: bug🐛, auto merge, ready to review, waiting-review, AI review first

#2617 [ISSUE #2616]🚀Add Level for log setting🔥
  rocketmq-common/src/log.rs
Labels: feature🚀, auto merge, ready to review, waiting-review, AI review first

#2620 [ISSUE #2619]📝Add Contribute Guide website link🔥
  README.md
Labels: documentation📝, auto merge, ready to review, waiting-review, AI review first

#2621 [ISSUE #2618]🐛Fix PopMessageRequestHeader#is_timeout_too_much attempt to subtract with overflow🔥
  rocketmq-remoting/src/protocol/header/pop_message_request_header.rs
Labels: bug🐛, auto merge, ready to review, waiting-review, AI review first, rocketmq-remoting crate

#2623 [ISSUE #2622]💫Change MessageStoreConfig timer_wheel_enable default value from true to false🔥
  rocketmq-store/src/config/message_store_config.rs
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first
