Repository mxsm/rocketmq-rust, pull requests merged in 2025-09, with the labels that each got.

#3925 [ISSUE #3924]🚀Implement flow control for reject requests in request processor
  rocketmq-remoting/src/remoting_server/server.rs
Labels: feature🚀, auto merge, ready to review, waiting-review, AI review first

#3928 #3884: Refactor zone_name method to return an Option reference
  rocketmq-remoting/src/protocol/route/route_data_view.rs
Labels: refactor♻️, auto merge, ready to review, waiting-review, AI review first

#3930 #3912: Refactor ConfigManager::encode method
  rocketmq-broker/src/filter/manager/consumer_filter_manager.rs
  rocketmq-common/src/common/config_manager.rs
Labels: refactor♻️, auto merge, ready to review, waiting-review, AI review first, Difficulty level/Easy

#3941 [ISSUE #3940]📚 Add "Best practice" section to navigation
  rocketmq-doc/_data/navigation.yml
Labels: documentation📝, auto merge, ready to review, waiting-review, AI review first

#3942 [ISSUE #3939]📚 Added Chinese and en documentation on best practices for Broker naming
  rocketmq-doc/_data/navigation.yml
  rocketmq-doc/_docs/07-01-broker-naming.md
  rocketmq-doc/_docs/zh/07-01-broker-naming.md
Labels: documentation📝, wip, auto merge, ready to review, waiting-review, AI review first

#3953 [ISSUE #3952]🚀Implement BrokerPreOnlineService and integrate with BrokerRuntime lifecycle
  rocketmq-broker/src/broker/broker_pre_online_service.rs
  rocketmq-broker/src/broker_runtime.rs
Labels: feature🚀, auto merge, ready to review, waiting-review, AI review first

#3959 [ISSUE #3957]🚀BrokerConfig: add compatible_with_old_name_srv flag with default true
  rocketmq-common/src/common/broker/broker_config.rs
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first

#3962 [ISSUE #3961]🚀Add constructor for BrokerPreOnlineService and integrate with BrokerRuntime
  rocketmq-broker/src/broker/broker_pre_online_service.rs
  rocketmq-broker/src/broker_runtime.rs
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first

#3964 [ISSUE #3963]🚀Broker pre-online: master HA handshake loop, min-broker selection, and HA addr helper
  rocketmq-broker/src/broker/broker_pre_online_service.rs
  rocketmq-broker/src/broker_runtime.rs
  rocketmq-broker/src/out_api/broker_outer_api.rs
Labels: feature🚀, auto merge, ready to review, waiting-review, AI review first

#3966 [ISSUE #3965]🚀Add ExchangeHAInfoRequestHeader to remoting protocol
  rocketmq-remoting/src/protocol/header.rs
  rocketmq-remoting/src/protocol/header/exchange_ha_info_request_header.rs
Labels: feature🚀, auto merge, ready to review, waiting-review, AI review first

#3972 [ISSUE #3970]⚡️Broker pre-online HA handshake, HA metadata exchange, optional HA service, and remoting helper
  rocketmq-broker/src/broker/broker_pre_online_service.rs
  rocketmq-broker/src/out_api/broker_outer_api.rs
  rocketmq-store/src/ha.rs
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first

#3975 [ISSUE #3974]🚀Implement PartialOrd and Ord traits for DataVersion; enhance equality comparison logic
  rocketmq-remoting/src/protocol.rs
Labels: feature🚀, auto merge, ready to review, waiting-review, AI review first

#3979 AdminBrokerProcessor. NotifyMinBrokerIdChange preliminary implementation of functions
  rocketmq-broker/src/processor/admin_broker_processor.rs
  rocketmq-broker/src/processor/admin_broker_processor/notify_min_broker_id_handler.rs
Labels: feature🚀, auto merge, ready to review, waiting-review, AI review first

#3986 [ISSUE #3985]🍻Make HAConnection::remote_address return owned String and wire remote SocketAddr through HA layer
  rocketmq-store/src/ha/auto_switch/auto_switch_ha_connection.rs
  rocketmq-store/src/ha/default_ha_connection.rs
  rocketmq-store/src/ha/default_ha_service.rs
  rocketmq-store/src/ha/general_ha_connection.rs
  rocketmq-store/src/ha/ha_connection.rs
Labels: refactor♻️, auto merge, ready to review, waiting-review, AI review first

#3988 [ISSUE #3968]🍻 Make HAService::put_group_connection_state_request async and awaitable; update broker pre-online handshake flow
  rocketmq-broker/src/broker/broker_pre_online_service.rs
  rocketmq-store/src/ha/auto_switch/auto_switch_ha_service.rs
  rocketmq-store/src/ha/default_ha_service.rs
  rocketmq-store/src/ha/general_ha_service.rs
  rocketmq-store/src/ha/ha_service.rs
Labels: feature🚀, refactor♻️, auto merge, ready to review, waiting-review, AI review first, Difficulty level/Hard

#3994 [ISSUE #3993]📝Add configuration files for broker master and slave settings
  distribution/config/broker/1m-1s-async-one-machine/broker-master.toml
  distribution/config/broker/1m-1s-async-one-machine/broker-slave.toml
Labels: documentation📝, auto merge, ready to review, waiting-review, AI review first

#3998 [ISSUE #3997]⚡️Improve logging for commit log loading with distinct success and failure messages
  rocketmq-store/src/log_file/commit_log.rs
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first

#4005 [ISSUE #4004]📝Update doc website url to https://rocketmqrust.com in README
  README.md
Labels: documentation📝, auto merge, ready to review, waiting-review, AI review first

#4007 [ISSUE #4006]♻️Refactor: Use &mut RemotingCommand in RequestProcessor API for in-place mutation & reduced cloning
  rocketmq-broker/src/long_polling/long_polling_service/pop_long_polling_service.rs
  rocketmq-broker/src/long_polling/pop_request.rs
  rocketmq-broker/src/processor.rs
  rocketmq-broker/src/processor/ack_message_processor.rs
  rocketmq-broker/src/processor/admin_broker_processor.rs
  rocketmq-broker/src/processor/admin_broker_processor/batch_mq_handler.rs
  rocketmq-broker/src/processor/admin_broker_processor/broker_config_request_handler.rs
  rocketmq-broker/src/processor/admin_broker_processor/consumer_request_handler.rs
  rocketmq-broker/src/processor/admin_broker_processor/notify_min_broker_id_handler.rs
  rocketmq-broker/src/processor/admin_broker_processor/offset_request_handler.rs
  rocketmq-broker/src/processor/admin_broker_processor/subscription_group_handler.rs
  rocketmq-broker/src/processor/admin_broker_processor/topic_request_handler.rs
  rocketmq-broker/src/processor/change_invisible_time_processor.rs
  rocketmq-broker/src/processor/client_manage_processor.rs
  rocketmq-broker/src/processor/consumer_manage_processor.rs
  rocketmq-broker/src/processor/default_pull_message_result_handler.rs
  rocketmq-broker/src/processor/end_transaction_processor.rs
  rocketmq-broker/src/processor/notification_processor.rs
  rocketmq-broker/src/processor/peek_message_processor.rs
  rocketmq-broker/src/processor/polling_info_processor.rs
  rocketmq-broker/src/processor/pop_message_processor.rs
  rocketmq-broker/src/processor/pull_message_processor.rs
  rocketmq-broker/src/processor/pull_message_result_handler.rs
  rocketmq-broker/src/processor/query_assignment_processor.rs
  rocketmq-broker/src/processor/query_message_processor.rs
  rocketmq-broker/src/processor/reply_message_processor.rs
  rocketmq-broker/src/processor/send_message_processor.rs
  rocketmq-client/src/implementation/client_remoting_processor.rs
  rocketmq-namesrv/src/processor.rs
  rocketmq-namesrv/src/processor/client_request_processor.rs
  rocketmq-namesrv/src/processor/default_request_processor.rs
  rocketmq-remoting/src/clients/client.rs
  rocketmq-remoting/src/remoting_server/server.rs
  rocketmq-remoting/src/request_processor/default_request_processor.rs
  rocketmq-remoting/src/runtime/processor.rs
Labels: auto merge, ready to review, waiting-review, AI review first, refactor

#4034 Exchange broker ha info
  rocketmq-broker/src/processor/admin_broker_processor.rs
  rocketmq-broker/src/processor/admin_broker_processor/notify_min_broker_id_handler.rs
  rocketmq-broker/src/processor/admin_broker_processor/update_broker_ha_handler.rs
  rocketmq-remoting/src/protocol/header.rs
  rocketmq-remoting/src/protocol/header/exchange_ha_info_response_header.rs
Labels: feature🚀, approved, auto merge, ready to review, waiting-review, AI review first

#4039 [ISSUE #4038]🚀Add page_size dependency and enhance memory management in TransientStorePool
  Cargo.lock
  rocketmq-error/src/lib.rs
  rocketmq-store/Cargo.toml
  rocketmq-store/src/base/transient_store_pool.rs
  rocketmq-store/src/message_store/local_file_message_store.rs
  rocketmq-store/src/utils.rs
  rocketmq-store/src/utils/ffi.rs
Labels: feature🚀, auto merge, ready to review, waiting-review, AI review first

#4042 perf: inline functions of broker_bootstrap.rs
  rocketmq-broker/src/broker_bootstrap.rs
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first, Difficulty level/Easy

#4044 refactor: Simplying default configuration in NamesrvConfig
  rocketmq-common/src/common/namesrv/namesrv_config.rs
Labels: refactor♻️, auto merge, ready to review, waiting-review, AI review first

#4049 [ISSUE #4048]🚀Add broker heartbeat interval configuration and scheduling
  rocketmq-broker/src/broker_runtime.rs
  rocketmq-common/src/common/broker/broker_config.rs
Labels: feature🚀, auto merge, ready to review, waiting-review, AI review first

#4053 [ISSUE #4052]🚀Implement minimum broker ID and address tracking in broker runtime
  rocketmq-broker/src/broker_runtime.rs
  rocketmq-remoting/src/protocol/body/broker_body/broker_member_group.rs
Labels: feature🚀, auto merge, ready to review, waiting-review, AI review first

#4061 [ISSUE #4060]⚡️Enhance broker runtime with locking mechanism and refactor sync methods
  rocketmq-broker/src/broker_runtime.rs
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first

#4065 [ISSUE #4064] Refactor error handling in ackAsync for queue ID and offset retrieval
  rocketmq-client/src/consumer/consumer_impl/default_mq_push_consumer_impl.rs
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first

#4066 test: added config test case for ServerConfig
  rocketmq-broker/src/broker_runtime.rs
  rocketmq-common/src/common/server/config.rs
Labels: enhancement⚡️, auto merge, ready to review, testing, waiting-review, AI review first, Difficulty level/Easy, testing🧪

#4070 [ISSUE #4069]♻️Refactor scheduled task execution in broker runtime to use task manager
  rocketmq-broker/src/broker_runtime.rs
Labels: refactor♻️, auto merge, ready to review, waiting-review, AI review first

#4071 [ISSUE #3917]🐛Update GetAllSubscriptionGroupConfig to GetAllMessageRequestMode
  rocketmq-broker/src/out_api/broker_outer_api.rs
Labels: bug🐛, auto merge, ready to review, waiting-review, AI review first, Difficulty level/Easy

#4073 [ISSUE #4072]♻️Refactor broker registration task to use scheduled task manager
  rocketmq-broker/src/broker_runtime.rs
Labels: refactor♻️, auto merge, ready to review, waiting-review, AI review first

#4076 [ISSUE #4075]🚀Implement Broker on_master_offline
  rocketmq-broker/src/broker_runtime.rs
  rocketmq-broker/src/slave/slave_synchronize.rs
Labels: feature🚀, auto merge, ready to review, waiting-review, AI review first

#4074 [ISSUE #3992]♻️Refactor event listener initialization to handle None case for channel_event_listener
  rocketmq-remoting/src/remoting_server/server.rs
Labels: refactor♻️, auto merge, ready to review, waiting-review, AI review first

#4086 [ISSUE #3793]⚡️Remove unused trait-variant workspace dependency from Cargo.toml
  Cargo.lock
  rocketmq/Cargo.toml
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first, Difficulty level/Easy

#4091 [ISSUE #4092]♻️Clean up existing clippy warnings of bool_assert_comparison and assertions_on_constant
  rocketmq-broker/src/client/consumer_group_event.rs
  rocketmq-broker/src/topic/manager/topic_queue_mapping_manager.rs
  rocketmq-common/src/common/attribute/bool_attribute.rs
  rocketmq-common/src/common/config.rs
  rocketmq-common/src/common/namesrv/namesrv_config.rs
  rocketmq-common/src/utils/cleanup_policy_utils.rs
  rocketmq-common/src/utils/queue_type_utils.rs
  rocketmq-common/src/utils/util_all.rs
  rocketmq-remoting/src/protocol/body/topic_info_wrapper/topic_config_wrapper.rs
  rocketmq-remoting/src/protocol/header/create_topic_request_header.rs
  rocketmq-remoting/src/protocol/header/message_operation_header/send_message_request_header.rs
  rocketmq-remoting/src/protocol/header/message_operation_header/send_message_request_header_v2.rs
  rocketmq-remoting/src/protocol/header/reply_message_request_header.rs
  rocketmq-remoting/src/protocol/namespace_util.rs
  rocketmq-store/src/ha/ha_connection_state_notification_request.rs
  rocketmq-store/src/store/running_flags.rs
Labels: refactor♻️, auto merge, ready to review, waiting-review, AI review first

#4095 [ISSUE #4096]♻️Clean up existing clippy warnings of clone_on_copy and needless_borrow
  rocketmq-client/src/consumer/rebalance_strategy/allocate_message_queue_by_config.rs
  rocketmq-client/src/consumer/rebalance_strategy/allocate_message_queue_by_machine_room.rs
  rocketmq-client/src/consumer/rebalance_strategy/allocate_message_queue_by_machine_room_nearby.rs
  rocketmq-remoting/src/protocol/body/consume_message_directly_result.rs
  rocketmq-remoting/src/protocol/body/consume_status.rs
  rocketmq-store/src/base/get_message_result.rs
  rocketmq-store/src/base/store_enum.rs
  rocketmq-store/src/config/flush_disk_type.rs
Labels: refactor♻️, auto merge, ready to review, waiting-review, AI review first

#4097 [ISSUE #4099]♻️Clean up existing clippy warnings of vec_init_then_push, redundant_closure and useless_conversion
  rocketmq-broker/src/broker_path_config_helper.rs
  rocketmq-client/examples/batch/callback_batch_producer.rs
  rocketmq-client/examples/batch/simple_batch_producer.rs
  rocketmq-example/examples/consumer/pop_consumer.rs
  rocketmq-store/benches/delivery.rs
Labels: refactor♻️, auto merge, ready to review, waiting-review, AI review first

#4102 [ISSUE #4088]⚡️Add inline annotations to delay level table accessors
  rocketmq-store/src/message_store/local_file_message_store.rs
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first, Difficulty level/Easy
