Repository mxsm/rocketmq-rust, pull requests merged in 2025-08, with the labels that each got.

#3651 Removed unnecessary code from DefaultHAService
  rocketmq-store/src/ha/default_ha_service.rs
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first, Difficulty level/Easy

#3652 Add links to contributor and license icons
  README.md
Labels: documentation📝, auto merge, ready to review, waiting-review, AI review first

#3657 [ISSUE #3656]✨Implement notification mechanism and synchronization improvements for GroupTransferService
  rocketmq-store/src/ha/group_transfer_service.rs
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first

#3662 [ISSUE #3387]Refactor RpcRequestHeader with derive marco RequestHeaderCodec
  rocketmq-remoting/src/rpc/rpc_request_header.rs
Labels: refactor♻️, auto merge, ready to review, waiting-review, AI review first, Difficulty level/Easy, rocketmq-remoting crate

#3661 [ISSUE #3402]Refactor HeartbeatRequestHeader with derive marco RequestHeaderCodec
  rocketmq-remoting/src/protocol/header/heartbeat_request_header.rs
Labels: refactor♻️, auto merge, ready to review, waiting-review, AI review first, Difficulty level/Easy, rocketmq-remoting crate

#3665 Refactor EndTransactionRequestHeader with derive marco RequestHeaderCodec
  rocketmq-remoting/src/protocol/header/end_transaction_request_header.rs
Labels: refactor♻️, auto merge, ready to review, waiting-review, AI review first, Difficulty level/Easy, rocketmq-remoting crate

#3669 [ISSUE #3668]♻️Restructure DefaultHAClient with Inner struct pattern for improved memory management
  rocketmq-store/src/ha/default_ha_client.rs
Labels: refactor♻️, auto merge, ready to review, waiting-review, AI review first

#3672 [ISSUE #3664]Refactor is_time_to_report_offset to remove async and improve performance
  rocketmq-store/src/ha/default_ha_client.rs
Labels: refactor♻️, auto merge, ready to review, waiting-review, AI review first, Difficulty level/Easy

#3677 [ISSUE #2903]Enhancement⚡️ Add #[inline] for store_path_config_helper methods
  rocketmq-store/src/config/store_path_config_helper.rs
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first

#3679 Refactor CreateTopicRequestHeader
  rocketmq-remoting/src/protocol/header/create_topic_request_header.rs
Labels: refactor♻️, auto merge, ready to review, waiting-review, AI review first, Difficulty level/Easy, rocketmq-remoting crate

#3683 Refactor GetTopicStatsRequestHeader
  rocketmq-remoting/src/protocol/header/get_topic_stats_request_header.rs
Labels: refactor♻️, auto merge, ready to review, waiting-review, AI review first, Difficulty level/Easy, rocketmq-remoting crate

#3682 Refactor LockBatchMqRequestHeader
  rocketmq-remoting/src/protocol/header/lock_batch_mq_request_header.rs
Labels: refactor♻️, auto merge, ready to review, waiting-review, AI review first, Difficulty level/Easy, rocketmq-remoting crate

#3674 [ISSUE #3407]Refactor QueryConsumerOffsetRequestHeader with derive marco RequestHeaderCodec
  rocketmq-remoting/src/protocol/header/query_consumer_offset_request_header.rs
Labels: refactor♻️, auto merge, ready to review, waiting-review, AI review first, Difficulty level/Easy, rocketmq-remoting crate

#3685 Refactor DeleteTopicRequestHeader
  rocketmq-remoting/src/protocol/header/delete_topic_request_header.rs
Labels: refactor♻️, auto merge, ready to review, waiting-review, AI review first, Difficulty level/Easy, rocketmq-remoting crate

#3686 [ISSUE #3398]Refactor GetMetaDataResponseHeader with derive marco RequestHeaderCodec
  rocketmq-remoting/src/protocol/header/get_meta_data_response_header.rs
Labels: refactor♻️, auto merge, ready to review, waiting-review, AI review first, Difficulty level/Easy, rocketmq-remoting crate

#3689 [ISSUE #3688]Remove zerocopy and zerocopy-derive useless crate from rocketmq-store crate Cargo.toml
  Cargo.lock
  rocketmq-store/Cargo.toml
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first, Difficulty level/Easy

#3693 Remove duration_constructors_lite feature
  rocketmq-broker/src/lib.rs
  rocketmq-remoting/src/lib.rs
Labels: bug🐛, auto merge, ready to review, waiting-review, AI review first

#3691 Refactor GetTopicConfigRequestHeader
  rocketmq-remoting/src/protocol/header/get_topic_config_request_header.rs
Labels: refactor♻️, auto merge, ready to review, waiting-review, AI review first, Difficulty level/Easy, rocketmq-remoting crate

#3695 [ISSUE #3694]♻️Move service handle out of Inner and make HAClient::start idempotent
  rocketmq-store/src/ha/default_ha_client.rs
Labels: refactor♻️, auto merge, ready to review, waiting-review, AI review first

#3707 [ISSUE #3696]error[E0275]: overflow evaluating the requirement
  rocketmq-client/src/admin/mq_admin_ext_async.rs
  rocketmq-client/src/consumer/mq_consumer.rs
  rocketmq-client/src/consumer/mq_push_consumer.rs
  rocketmq-client/src/factory/mq_client_instance.rs
  rocketmq-client/src/implementation/mq_client_api_impl.rs
  rocketmq-client/src/lib.rs
  rocketmq-client/src/producer/mq_producer.rs
Labels: bug🐛, auto merge, ready to review, waiting-review, AI review first

#3710 [ISSUE #3709]♻️Narrow BrokerData equality to broker_name + broker_addrs
  rocketmq-remoting/src/protocol/route/route_data_view.rs
Labels: auto merge, ready to review, waiting-review, AI review first

#3711 Refactor MessageExt to add inline attribute
  rocketmq-common/src/common/message/message_ext.rs
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first

#3712 Refactor RemotingSysResponseCode method with inline attribute
  rocketmq-remoting/src/code/response_code.rs
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first

#3722 [ISSUE #3721]♻️Resilient topic route retrieval & decoding error handling in client
  rocketmq-client/src/factory/mq_client_instance.rs
  rocketmq-client/src/implementation/mq_client_api_impl.rs
Labels: auto merge, ready to review, waiting-review, AI review first

#3723 Refactor ElectMasterResponseHeader
  rocketmq-remoting/src/protocol/header/elect_master_response_header.rs
Labels: refactor♻️, auto merge, ready to review, waiting-review, AI review first, Difficulty level/Easy, rocketmq-remoting crate

#3725 [ISSUE #3724]♻️HA client state machine extraction & loop simplification
  rocketmq-store/src/ha/default_ha_client.rs
Labels: auto merge, ready to review, waiting-review, AI review first

#3727 [ISSUE #3726]♻️ HA client concurrent reader/writer split, atomic timestamp arcs & error channel propagation
  Cargo.lock
  rocketmq-store/Cargo.toml
  rocketmq-store/src/ha/default_ha_client.rs
Labels: auto merge, ready to review, waiting-review, AI review first

#3728 Replace init_logger() with init_logger_with_level()
  rocketmq-namesrv/src/bin/namesrv_bootstrap_server.rs
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first, Difficulty level/Easy, rocketmq-namesrv crate

#3730 [ISSUE #3729]📝Update main loop comment for clarity in HA client connection handling
  rocketmq-store/src/ha/default_ha_client.rs
Labels: documentation📝, auto merge, ready to review, waiting-review, AI review first

#3734 [ISSUE #3733]🐛Fix commit log append offset calculation in HA client
  rocketmq-store/src/ha/default_ha_client.rs
Labels: refactor♻️, auto merge, ready to review, waiting-review, AI review first

#3737 [ISSUE #3736]♻️Refactor GeneralHAClient to use enum for HA client management
  rocketmq-store/src/ha/general_ha_client.rs
Labels: refactor♻️, auto merge, ready to review, waiting-review, AI review first

#3739 refactor: Replace manual impls in GetMinOffsetRequestHeader with RequestHeaderCodec
  rocketmq-remoting/src/protocol/header/get_min_offset_request_header.rs
Labels: refactor♻️, auto merge, ready to review, waiting-review, AI review first, Difficulty level/Easy, rocketmq-remoting crate

#3742 [ISSUE #3741]📝Add configuration files for nameserver settings in RocketMQ
  distribution/config/nameserver/namesrv.conf
  distribution/config/nameserver/namesrv.toml
Labels: documentation📝, auto merge, ready to review, waiting-review, AI review first

#3740 refactor: Replace manual impls in GetMaxOffsetRequestHeader with RequestHeaderCodec
  rocketmq-remoting/src/protocol/header/get_max_offset_request_header.rs
Labels: refactor♻️, auto merge, ready to review, waiting-review, AI review first, Difficulty level/Easy, rocketmq-remoting crate

#3746 [ISSUE #3745]📝Update broker configuration with enhanced settings and new parameters
  distribution/config/broker/broker.toml
Labels: documentation📝, auto merge, ready to review, waiting-review, AI review first

#3767 [ISSUE #3766]📝Add initial broker-simple.toml configuration file with core settings
  distribution/config/broker/broker-simple.toml
Labels: documentation📝, auto merge, ready to review, waiting-review, AI review first

#3769 [ISSUE #3768]📝Refactor broker-simple.toml to reorganize Broker Identity section
  distribution/config/broker/broker-simple.toml
Labels: documentation📝, auto merge, ready to review, waiting-review, AI review first

#3781 [ISSUE #3780]📝Update to Version 0.7.0 for Next-Stage Development
  Cargo.lock
  Cargo.toml
Labels: documentation📝, auto merge, ready to review, waiting-review, AI review first

#3786 feat: Introduce #[inline] for Builder methods
  rocketmq-broker/src/broker_bootstrap.rs
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first

#3795 [ISSUE #3794]✨Add fixed-rate and fixed-delay task scheduling methods to ScheduledTaskManager
  rocketmq/src/schedule.rs
Labels: auto merge, ready to review, waiting-review, AI review first

#3797 [ISSUE #3796]✨Implement asynchronous fixed-rate, fixed-delay, and fixed-rate-no-overlap task scheduling methods in ScheduledTaskManager
  rocketmq/src/lib.rs
  rocketmq/src/schedule.rs
Labels: auto merge, ready to review, waiting-review, AI review first

#3803 [ISSUE #3802]♻️Refactor QueueTypeUtils to accept Option references directly for improved clarity and performance
  rocketmq-broker/src/processor/send_message_processor.rs
  rocketmq-broker/src/util/hook_utils.rs
  rocketmq-common/src/utils/queue_type_utils.rs
  rocketmq-store/src/log_file/commit_log.rs
  rocketmq-store/src/message_store/local_file_message_store.rs
  rocketmq-store/src/queue/local_file_consume_queue_store.rs
Labels: auto merge, ready to review, waiting-review, AI review first

#3805 [ISSUE #3804]Add slave synchronization scaffolding and update MessageStore HA API
  rocketmq-broker/src/broker_runtime.rs
  rocketmq-broker/src/lib.rs
  rocketmq-broker/src/slave.rs
  rocketmq-broker/src/slave/slave_synchronize.rs
  rocketmq-store/src/base/message_store.rs
  rocketmq-store/src/message_store/local_file_message_store.rs
Labels: auto merge, ready to review, waiting-review, AI review first, area/broker, area/store, needs-triage

#3824 refactor: return Option<&String>> on consumer_group
  rocketmq-client/src/hook/filter_message_context.rs
Labels: refactor♻️, auto merge, ready to review, waiting-review, AI review first, Difficulty level/Easy

#3830 [ISSUE #3827]♻️Consolidate server config: use BrokerConfig.broker_server_config across BrokerRuntime/Bootstrap
  rocketmq-broker/src/broker_bootstrap.rs
  rocketmq-broker/src/broker_runtime.rs
  rocketmq-remoting/src/remoting_server/server.rs
Labels: refactor♻️, auto merge, ready to review, waiting-review, AI review first

#3828 Add startup logo
  rocketmq-namesrv/src/bin/namesrv_bootstrap_server.rs
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first

#3838 [ISSUE #3837]🐛HA client didn’t refresh last_read_timestamp on reads, causing premature housekeeping disconnects
  rocketmq-store/src/ha/default_ha_client.rs
Labels: bug🐛, auto merge, ready to review, waiting-review, AI review first, Difficulty level/Easy

#3840 [ISSUE #3839]♻️Refactor DefaultHAService initialization to accept GeneralHAService as a parameter
  rocketmq-store/src/ha/default_ha_service.rs
  rocketmq-store/src/ha/general_ha_service.rs
Labels: refactor♻️, auto merge, ready to review, waiting-review, AI review first

#3845 #3826: Refactor Make is_compaction take Option<&TopicConfig> instead …
  rocketmq-common/src/utils/cleanup_policy_utils.rs
Labels: refactor♻️, auto merge, ready to review, waiting-review, AI review first, Difficulty level/Easy

#3847 [ISSUE #3846]⚡️Integrate StoreStatsService hooks and CQ checkpoint updates; prepare multi-dispatch LMQ path
  rocketmq-store/src/base/store_stats_service.rs
  rocketmq-store/src/message_store/local_file_message_store.rs
  rocketmq-store/src/queue/single_consume_queue.rs
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first

#3842 refactor: make ConsumeMessageDirectlyResult::remark return Option<&CheetahString>
  rocketmq-remoting/src/protocol/body/consume_message_directly_result.rs
Labels: refactor♻️, auto merge, ready to review, waiting-review, AI review first, Difficulty level/Easy

#3867 [ISSUE #3866]⚡️Update message handling in content_show.rs for improved clarity and type safety
  rocketmq-cli/src/content_show.rs
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first

#3881 [ISSUE #3880]♻️Simplify DataVersion counter from Arc<AtomicI64> to AtomicI64 in remoting protocol
  rocketmq-remoting/src/protocol.rs
Labels: refactor♻️, auto merge, ready to review, waiting-review, AI review first

#3886 [ISSUE #3885]♻️Make RemotingCommand::body() ergonomic (Option<&Bytes>) and update call sites
  rocketmq-broker/src/processor/send_message_processor.rs
  rocketmq-namesrv/src/processor/default_request_processor.rs
  rocketmq-remoting/src/protocol/remoting_command.rs
  rocketmq-remoting/src/rpc/rpc_client_impl.rs
Labels: auto merge, ready to review, waiting-review, AI review first, refactor

#3888 [ISSUE #3887]✨Add ConsumerOffsetSerializeWrapper protocol and export module
  rocketmq-remoting/src/protocol/body.rs
  rocketmq-remoting/src/protocol/body/consumer_offset_serialize_wrapper.rs
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first

#3890 [ISSUE #3889]✨Normalize ConsumerOffsetSerializeWrapper JSON field casing and add accessors
  rocketmq-remoting/src/protocol/body/consumer_offset_serialize_wrapper.rs
Labels: auto merge, ready to review, waiting-review, AI review first, refactor

#3892 [ISSUE #3891]✨Implement master→slave consumer offset sync and add BrokerOuterAPI.get_all_consumer_offset
  rocketmq-broker/src/offset/manager/consumer_offset_manager.rs
  rocketmq-broker/src/out_api/broker_outer_api.rs
  rocketmq-broker/src/slave/slave_synchronize.rs
  rocketmq-remoting/src/protocol/body/consumer_offset_serialize_wrapper.rs
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first

#3894 [ISSUE #3893]✨Implement master→slave delay offset sync and add BrokerOuterAPI.get_delay_offset⚡️
  rocketmq-broker/src/out_api/broker_outer_api.rs
  rocketmq-broker/src/slave/slave_synchronize.rs
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first

#3901 [ISSUE #3900]🚀Add MessageRequestModeSerializeWrapper protocol and export module
  rocketmq-remoting/src/protocol/body.rs
  rocketmq-remoting/src/protocol/body/message_request_mode_serialize_wrapper.rs
Labels: auto merge, ready to review, waiting-review, AI review first, enhancement

#3907 [ISSUE #3906]🚀Add broker handler for GetAllDelayOffset to expose delay offset data
  rocketmq-broker/src/processor/admin_broker_processor.rs
  rocketmq-broker/src/processor/admin_broker_processor/offset_request_handler.rs
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first

#3911 [ISSUE #3908]♻️Unify JSON error handling: replace JsonError with feature-gated SerdeJsonError and simplify conversions
  Cargo.lock
  rocketmq-common/Cargo.toml
  rocketmq-common/src/utils/parse_config_file.rs
  rocketmq-error/Cargo.toml
  rocketmq-error/src/lib.rs
Labels: refactor♻️, auto merge, ready to review, waiting-review, AI review first

#3914 [ISSUE #3913]⚡️Expose GetAllSubscriptionGroupConfig via admin broker processor
  rocketmq-broker/src/processor/admin_broker_processor.rs
  rocketmq-broker/src/processor/admin_broker_processor/offset_request_handler.rs
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first
