Repository mxsm/rocketmq-rust, pull requests merged in 2025-06, with the labels that each got.

#3359 [ISSUE #3358]🚀transactional message service with internal check implementation and message handling improvements💫
  rocketmq-broker/src/broker_runtime.rs
  rocketmq-broker/src/transaction/queue/default_transactional_message_check_listener.rs
  rocketmq-broker/src/transaction/queue/default_transactional_message_service.rs
  rocketmq-broker/src/transaction/queue/get_result.rs
  rocketmq-broker/src/transaction/transactional_message_check_listener.rs
  rocketmq-broker/src/transaction/transactional_message_service.rs
  rocketmq-store/src/config/message_store_config.rs
Labels: feature🚀, auto merge, ready to review, waiting-review, AI review first

#3356 [ISSUE #3317]🚀Implement UpdateNamesrvConfigCommand for name server tool
  rocketmq-client/src/admin/default_mq_admin_ext_impl.rs
  rocketmq-client/src/admin/mq_admin_ext_async.rs
  rocketmq-client/src/implementation/mq_client_api_impl.rs
  rocketmq-client/src/lib.rs
  rocketmq-common/src/common/mix_all.rs
  rocketmq-remoting/src/protocol/body/ha_runtime_info.rs
  rocketmq-remoting/src/protocol/header.rs
  rocketmq-remoting/src/protocol/header/empty_header.rs
  rocketmq-tools/src/admin/default_mq_admin_ext.rs
  rocketmq-tools/src/commands/namesrv_commands.rs
  rocketmq-tools/src/commands/namesrv_commands/update_namesrv_config.rs
Labels: feature🚀, auto merge, ready to review, waiting-review, AI review first, Difficulty level/Moderate, rocketmq-tools crate

#3360 [ISSUE #3313]🚀Implement AddWritePermSubCommand for name server tool
  rocketmq-client/src/admin/default_mq_admin_ext_impl.rs
  rocketmq-client/src/implementation/mq_client_api_impl.rs
  rocketmq-remoting/src/protocol/header/namesrv/perm_broker_header.rs
  rocketmq-tools/src/admin/default_mq_admin_ext.rs
  rocketmq-tools/src/commands/namesrv_commands.rs
  rocketmq-tools/src/commands/namesrv_commands/add_write_perm_sub_command.rs
Labels: feature🚀, auto merge, ready to review, waiting-review, AI review first, Difficulty level/Moderate, rocketmq-tools crate

#3361 [ISSUE ##3318]🚀Implement WipeWritePermSubCommand for name server tool
  rocketmq-client/src/admin/default_mq_admin_ext_impl.rs
  rocketmq-client/src/implementation/mq_client_api_impl.rs
  rocketmq-remoting/src/protocol/header/namesrv/perm_broker_header.rs
  rocketmq-tools/src/admin/default_mq_admin_ext.rs
  rocketmq-tools/src/commands/namesrv_commands.rs
  rocketmq-tools/src/commands/namesrv_commands/wipe_write_perm_sub_command.rs
Labels: feature🚀, auto merge, ready to review, waiting-review, AI review first, Difficulty level/Moderate

#3363 [ISSUE #3362]🚀Add ServiceError enumeration and service task macro implementation💫
  Cargo.lock
  rocketmq-error/src/lib.rs
  rocketmq/Cargo.toml
  rocketmq/src/lib.rs
  rocketmq/src/task.rs
  rocketmq/src/task/service_task.rs
Labels: feature🚀, auto merge, ready to review, waiting-review, AI review first

#3371 [ISSUE #3370]⚡️Update minimum supported Rust version to 1.85.0
  .clippy.toml
  Cargo.toml
  README.md
  rocketmq-broker/Cargo.toml
  rocketmq-broker/src/failover/escape_bridge.rs
  rocketmq-broker/src/processor/pop_message_processor.rs
  rocketmq-broker/src/topic/manager/topic_route_info_manager.rs
  rocketmq-cli/Cargo.toml
  rocketmq-client/Cargo.toml
  rocketmq-client/src/consumer/pop_callback.rs
  rocketmq-client/src/consumer/pull_callback.rs
  rocketmq-common/Cargo.toml
  rocketmq-error/Cargo.toml
  rocketmq-example/Cargo.toml
  rocketmq-filter/Cargo.toml
  rocketmq-macros/Cargo.toml
  rocketmq-namesrv/Cargo.toml
  rocketmq-remoting/Cargo.toml
  rocketmq-runtime/Cargo.toml
  rocketmq-store/Cargo.toml
  rocketmq-tools/Cargo.toml
  rocketmq-tui/Cargo.toml
  rocketmq/Cargo.toml
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first

#3373 [ISSUE #3372]📝Update README.md
  README.md
Labels: documentation📝, auto merge, ready to review, waiting-review, AI review first

#3375 [ISSUE #3374]🚀Implement a scheduled task dispatcher
  Cargo.lock
  rocketmq/Cargo.toml
  rocketmq/examples/advanced_usage.rs
  rocketmq/examples/basic_usage.rs
  rocketmq/src/lib.rs
  rocketmq/src/schedule.rs
  rocketmq/src/schedule/executor.rs
  rocketmq/src/schedule/scheduler.rs
  rocketmq/src/schedule/task.rs
  rocketmq/src/schedule/trigger.rs
Labels: feature🚀, auto merge, ready to review, waiting-review, AI review first

#3383 [ISSUE #3382]♻️Refactor ServiceTask trait to enhance service logic implementation and provide default behavior for on_wait_end
  rocketmq/src/task/service_task.rs
Labels: refactor♻️, auto merge, ready to review, waiting-review, AI review first

#3385 [ISSUE #3384]♻️Refactor service task structures and rename for clarity
  rocketmq-broker/src/transaction/transactional_message_check_service.rs
  rocketmq/src/task.rs
  rocketmq/src/task/service_task.rs
Labels: refactor♻️, auto merge, ready to review, waiting-review, AI review first

#3417 [ISSUE #3416]🚀Add methods for managing message body in message structures
  rocketmq-common/src/common/message.rs
  rocketmq-common/src/common/message/message_batch.rs
  rocketmq-common/src/common/message/message_client_ext.rs
  rocketmq-common/src/common/message/message_ext.rs
  rocketmq-common/src/common/message/message_ext_broker_inner.rs
  rocketmq-common/src/common/message/message_single.rs
Labels: feature🚀, auto merge, ready to review, waiting-review, AI review first

#3419 [ISSUE #3418]♻️Refactor end_message_transaction function to accept mutable reference and improve message handling
  rocketmq-broker/src/processor/end_transaction_processor.rs
Labels: refactor♻️, auto merge, ready to review, waiting-review, AI review first

#3421 [ISSUE #3420]♻️Refactor make_op_message_inner function to accept ownership of Message and simplify message handling
  rocketmq-broker/src/transaction/queue/transactional_message_bridge.rs
Labels: refactor♻️, auto merge, ready to review, waiting-review, AI review first

#3425 [ISSUE #3424]🚀Add transaction_op_batch_interval to BrokerConfig and refactor related services for improved transaction handling
  rocketmq-broker/src/broker_runtime.rs
  rocketmq-broker/src/transaction/queue/default_transactional_message_service.rs
  rocketmq-broker/src/transaction/queue/transactional_op_batch_service.rs
  rocketmq-common/src/common/broker/broker_config.rs
Labels: feature🚀, auto merge, ready to review, waiting-review, AI review first

#3427 [ISSUE #3426]♻️Refactor transactional message service to use WeakArcMut for improved memory management
  rocketmq-broker/src/broker_runtime.rs
  rocketmq-broker/src/transaction/queue/default_transactional_message_service.rs
  rocketmq-broker/src/transaction/queue/transactional_op_batch_service.rs
Labels: refactor♻️, auto merge, ready to review, waiting-review, AI review first

#3429 [ISSUE #3428]♻️Refactor DefaultTransactionalMessageCheckListener to simplify structure and enhance message handling
  rocketmq-broker/src/transaction/queue/default_transactional_message_check_listener.rs
  rocketmq-broker/src/transaction/transactional_message_check_listener.rs
Labels: refactor♻️, auto merge, ready to review, waiting-review, AI review first

#3431 [ISSUE #3430]♻️Refactor resolve_half_msg method for improved error handling and clarity
  rocketmq-broker/src/transaction/queue/default_transactional_message_check_listener.rs
  rocketmq-broker/src/transaction/queue/default_transactional_message_service.rs
Labels: refactor♻️, auto merge, ready to review, waiting-review, AI review first

#3437 [ISSUE #3436]⚡️Improve message handling to simplify topic length retrieval and improve clarity
  rocketmq-common/src/common/message.rs
  rocketmq-common/src/common/message/message_decoder.rs
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first

#3439 [ISSUE #3438]⚡️Enhancement message handling in transactional_message_bridge for improved clarity and error handling
  rocketmq-broker/src/transaction/queue/transactional_message_bridge.rs
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first

#3443 [ISSUE #3442]📝Clarify message property configuration in end_transaction_processor
  rocketmq-broker/src/processor/end_transaction_processor.rs
Labels: documentation📝, approved, auto merge, AI review first

#3445 [ISSUE #3444]📝Enhance documentation for fill_op_remove_map function with detailed argument and return descriptions
  rocketmq-broker/src/transaction/queue/default_transactional_message_service.rs
Labels: documentation📝, approved, auto merge, AI review first

#3462 [ISSUE #3461]🚀Refactor shutdown methods to be asynchronous for improved performance and responsiveness✨
  rocketmq-broker/src/broker_runtime.rs
  rocketmq-broker/src/transaction/queue/default_transactional_message_service.rs
  rocketmq-broker/src/transaction/queue/transactional_op_batch_service.rs
  rocketmq-broker/src/transaction/transactional_message_service.rs
Labels: refactor♻️, auto merge, ready to review, waiting-review, AI review first

#3465 [ISSUE #3464]📝Update comments in get_message_result.rs for clarity on offsets and buffer size
  rocketmq-store/src/base/get_message_result.rs
Labels: documentation📝, auto merge, ready to review, waiting-review, AI review first

#3467 [ISSUE #3466]♻️Refactor offset handling in default_transactional_message_service.rs for improved clarity and performance🚀
  rocketmq-broker/src/transaction/queue/default_transactional_message_service.rs
  rocketmq-broker/src/transaction/transactional_message_check_listener.rs
Labels: refactor♻️, auto merge, ready to review, waiting-review, AI review first

#3471 [ISSUE #3470]🚀Enhance HAConnectionState with additional methods for state management and transitions✨
  rocketmq-store/src/ha/ha_connection_state.rs
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first

#3473 [ISSUE #3472]🚀Add FlowMonitor for tracking data transfer metrics and flow control management✨
  rocketmq-store/src/config/message_store_config.rs
  rocketmq-store/src/ha.rs
  rocketmq-store/src/ha/flow_monitor.rs
Labels: feature🚀, auto merge, ready to review, waiting-review, AI review first

#3480 [ISSUE #3406]♻️Refactor PullMessageResponseHeader with derive marco RequestHeaderCodec
  rocketmq-remoting/src/protocol/header/pull_message_response_header.rs
Labels: refactor♻️, auto merge, ready to review, waiting-review, AI review first, Difficulty level/Easy, rocketmq-remoting crate

#3483 [ISSUE #3390] ♻️Refactor GetConsumerListByGroupRequestHeader with derive marco RequestHeaderCodec
  rocketmq-remoting/src/protocol/header/get_consumer_listby_group_request_header.rs
Labels: refactor♻️, auto merge, ready to review, waiting-review, AI review first, Difficulty level/Easy, rocketmq-remoting crate

#3488 [ISSUE #3485]⚡️Optimize DefaultHAConnection WriteSocketService to improve data transfer handling and buffer management
  rocketmq-store/src/ha/default_ha_connection.rs
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first

#3492 [ISSUE #3491]🚀Add group_commit_request module to log_file for enhanced commit handling✨
  rocketmq-store/src/log_file.rs
  rocketmq-store/src/log_file/group_commit_request.rs
Labels: feature🚀, auto merge, ready to review, waiting-review, AI review first

#3497 [ISSUE #3412]♻️Refactor UnlockBatchMqRequestHeader with derive marco RequestHeaderCodec
  rocketmq-client/src/implementation/mq_client_api_impl.rs
  rocketmq-remoting/src/protocol/header/unlock_batch_mq_request_header.rs
Labels: refactor♻️, auto merge, ready to review, waiting-review, AI review first, Difficulty level/Easy, rocketmq-remoting crate

#3500 [ISSUE #3499]🚀Implement DefaultHAClient for comprehensive master-slave replication✨
  rocketmq-store/src/ha.rs
  rocketmq-store/src/ha/default_ha_client.rs
  rocketmq-store/src/ha/flow_monitor.rs
Labels: feature🚀, auto merge, ready to review, waiting-review, AI review first

#3513 [ISSUE #3512]🚀Async High Availability (HA) Service Architecture Enhancement ✨
  rocketmq-broker/src/broker_runtime.rs
  rocketmq-store/src/base/message_store.rs
  rocketmq-store/src/config/message_store_config.rs
  rocketmq-store/src/ha/auto_switch/auto_switch_ha_service.rs
  rocketmq-store/src/ha/default_ha_client.rs
  rocketmq-store/src/ha/default_ha_connection.rs
  rocketmq-store/src/ha/default_ha_service.rs
  rocketmq-store/src/ha/general_ha_client.rs
  rocketmq-store/src/ha/general_ha_connection.rs
  rocketmq-store/src/ha/general_ha_service.rs
  rocketmq-store/src/ha/group_transfer_service.rs
  rocketmq-store/src/ha/ha_connection_state_notification_service.rs
  rocketmq-store/src/ha/ha_service.rs
  rocketmq-store/src/message_store/local_file_message_store.rs
Labels: auto merge, ready to review, waiting-review, AI review first

#3516 [ISSUE #3515]🐛Memory Safety Issue in DefaultHAClient master_address Field Implementation
  rocketmq-store/src/ha/auto_switch/auto_switch_ha_client.rs
  rocketmq-store/src/ha/default_ha_client.rs
  rocketmq-store/src/ha/default_ha_service.rs
  rocketmq-store/src/ha/general_ha_client.rs
  rocketmq-store/src/ha/general_ha_service.rs
  rocketmq-store/src/ha/ha_client.rs
Labels: auto merge, ready to review, waiting-review, AI review first

#3522 [ISSUE #3521]⚡️Increase buffer capacity for Framed connection to 1 MB in new Connection implementation
  rocketmq-remoting/src/connection.rs
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first

#3524 [ISSUE #3523]⚡️Increase buffer size to 8 KB in Connection implementation
  rocketmq-remoting/src/connection.rs
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first

#3530 [ISSUE #3529]♻️Refactor HAConnection start method to use match statement for cleaner connection handling
  rocketmq-store/src/ha/general_ha_connection.rs
Labels: refactor♻️, auto merge, ready to review, waiting-review, AI review first

#3543 [ISSUE #3487] Optimize connection buffer handling to use split method
  rocketmq-remoting/src/connection.rs
Labels: auto merge, ready to review, waiting-review, AI review first
