Repository mxsm/rocketmq-rust, pull requests merged in 2025-03, with the labels that each got.

#2625 [ISSUE #2610] Remove ReplyMessageProcessor useless code
  rocketmq-broker/src/broker_runtime.rs
  rocketmq-broker/src/processor/reply_message_processor.rs
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first

#2627 [ISSUE #2626]🐛Fix PopMessageProcessor#process error acording to Java code🔥
  rocketmq-broker/src/processor/pop_message_processor.rs
Labels: bug🐛, auto merge, ready to review, waiting-review, AI review first

#2628 [ISSUE #2624]🚀Implement PopMessageProcessor#append_check_point method🔥
  rocketmq-broker/src/processor/pop_message_processor.rs
  rocketmq-broker/src/processor/processor_service/pop_buffer_merge_service.rs
Labels: feature🚀, auto merge, ready to review, waiting-review, AI review first, rocketmq-broker crate

#2634 [ISSUE #2633]🚀ArcMut implements Debug trait🔥
  rocketmq/src/arc_mut.rs
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first

#2636 [ISSUE #2635]📝Update README.md🔥
  README.md
Labels: documentation📝, auto merge, ready to review, waiting-review, AI review first

#2637 [ISSUE #2630]🚀Implement PopBufferMergeService#add_ck method🔥
  rocketmq-broker/src/processor/processor_service/pop_buffer_merge_service.rs
  rocketmq-common/src/common/broker/broker_config.rs
Labels: feature🚀, auto merge, ready to review, waiting-review, AI review first

#2638 [ISSUE #2631]🚀Implement PopBufferMergeService#add_ck_just_offset method🔥
  rocketmq-broker/src/processor/pop_message_processor.rs
  rocketmq-broker/src/processor/processor_service/pop_buffer_merge_service.rs
Labels: feature🚀, auto merge, ready to review, waiting-review, AI review first

#2639 [ISSUE #2609]🚀Update the version number of the website's homepage to the latest🔥
  rocketmq-doc/_pages/home.md
Labels: documentation📝, auto merge, ready to review, waiting-review, AI review first

#2648 [ISSUE #2647]⚡️optimize cargo clippy -- -D warnings error
  rocketmq-broker/src/lib.rs
  rocketmq-client/src/lib.rs
  rocketmq-namesrv/src/lib.rs
  rocketmq-remoting/src/protocol/body/topic_info_wrapper/topic_config_wrapper.rs
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first

#2652 [ISSUE #2651]🐛Request PopMessage return not response header🔥
  rocketmq-broker/src/processor/pop_message_processor.rs
  rocketmq-remoting/src/protocol/header/extra_info_util.rs
Labels: bug🐛, auto merge, ready to review, waiting-review, AI review first

#2654 [ISSUE #2653]⚡️Remove EscapeBridge useless attributes🍻
  rocketmq-broker/src/failover/escape_bridge.rs
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first

#2655 [ISSUE #2632] PopCheckPointWrapper method add #[inline]
  rocketmq-broker/src/processor/processor_service/pop_buffer_merge_service.rs
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first, rocketmq-broker crate

#2658 [ISSUE #2657] 🐛PopMessageProcessor#pop_msg_from_queue's atomic_rest_n…
  rocketmq-broker/src/processor/pop_message_processor.rs
Labels: bug🐛, auto merge, ready to review, waiting-review, AI review first

#2661 [ISSUE #2660]⚡️Optimize PopMessageResponseHeader return value
  rocketmq-broker/src/processor/pop_message_processor.rs
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first

#2663 [ISSUE #2662]⚡️Remove PopMessageProcessor#append_check_point comments🍻
  rocketmq-broker/src/processor/pop_message_processor.rs
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first

#2667 [ISSUE #2665]⚡️PopBufferMergeService#scan attempt to subtract with overflow🍻
  rocketmq-broker/src/processor/processor_service/pop_buffer_merge_service.rs
  rocketmq-common/src/common/broker/broker_config.rs
Labels: bug🐛, auto merge, ready to review, waiting-review, AI review first

#2669 [ISSUE #2668]🐛PopBufferMergeService start wait time incorrect🍻
  rocketmq-broker/src/processor/processor_service/pop_buffer_merge_service.rs
Labels: bug🐛, auto merge, ready to review, waiting-review, AI review first

#2671 [ISSUE #2670]🚀Implement PopBufferMergeService#scanCommitOffset method🍻
  rocketmq-broker/src/processor/pop_message_processor.rs
  rocketmq-broker/src/processor/processor_service/pop_buffer_merge_service.rs
Labels: feature🚀, auto merge, ready to review, waiting-review, AI review first

#2677 [ISSUE #2676]🐛Fix PopBufferMergeService#is_ck_done_for_finish logic not correct
  rocketmq-broker/src/processor/processor_service/pop_buffer_merge_service.rs
Labels: bug🐛, auto merge, ready to review, waiting-review, AI review first

#2679 [ISSUE #2678]🐛Fix PopBufferMergeService#put_offset_queue logic not correct
  rocketmq-broker/src/processor/processor_service/pop_buffer_merge_service.rs
Labels: bug🐛, auto merge, ready to review, waiting-review, AI review first

#2681 [ISSUE #2680]🐛Fix set PopRequest message_filter some times is none
  rocketmq-broker/src/long_polling/long_polling_service/pop_long_polling_service.rs
  rocketmq-broker/src/long_polling/pop_request.rs
Labels: bug🐛, auto merge, ready to review, waiting-review, AI review first

#2684 [ISSUE #2683]🚀Implement PopLongPollingService#clean_unused_resource method
  rocketmq-broker/src/long_polling/long_polling_service/pop_long_polling_service.rs
Labels: feature🚀, auto merge, ready to review, waiting-review, AI review first

#2686 [ISSUE #2685]📝Update Rocketmq Rust Roadmap🍻
  rocketmq-doc/_docs/03-roadmap.md
Labels: documentation📝, auto merge, ready to review, waiting-review, AI review first

#2688 [ISSUE #2687]⚡️Remove PopBufferMergeService print debug log🍻
  rocketmq-broker/src/processor/processor_service/pop_buffer_merge_service.rs
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first

#2692 [ISSUE #2691]⚡️Optimize PopLongPollingService#start method logic🍻
  rocketmq-broker/src/long_polling/long_polling_service/pop_long_polling_service.rs
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first

#2696 [ISSUE #2695]🚀Channel adds is_ok methods
  rocketmq-remoting/src/net/channel.rs
Labels: feature🚀, auto merge, ready to review, waiting-review, AI review first

#2698 [ISSUE #2697]⚡️Optimize PopLongPollingService#poll_remoting_commands methods
  rocketmq-broker/src/long_polling/long_polling_service/pop_long_polling_service.rs
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first

#2700 [ISSUE #2699]🚀Implement PopLongPollingService#notifyMessageArrivingWithRetryTopic method acording to Java
  rocketmq-broker/src/long_polling/long_polling_service/pop_long_polling_service.rs
Labels: feature🚀, auto merge, ready to review, waiting-review, AI review first

#2702 [ISSUE #2701]Optimize PopLongPollingService#polling method
  rocketmq-broker/src/long_polling/long_polling_service/pop_long_polling_service.rs
  rocketmq-broker/src/long_polling/pop_request.rs
  rocketmq-broker/src/processor/pop_message_processor.rs
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first

#2709 [ISSUE #2708]🐛Fix Ack append message topic not correct
  rocketmq-broker/src/processor/ack_message_processor.rs
Labels: bug🐛, auto merge, ready to review, waiting-review, AI review first

#2713 [ISSUE #2710]♻️Refactor ReputMessageService
  rocketmq-store/src/message_store/default_message_store.rs
Labels: refactor♻️, auto merge, ready to review, waiting-review, AI review first

#2715 [ISSUE #2714]🚀NotifyMessageArrivingListener add pop message arriving notification
  rocketmq-broker/src/broker_runtime.rs
  rocketmq-broker/src/long_polling/notify_message_arriving_listener.rs
  rocketmq-broker/src/processor/notification_processor.rs
  rocketmq-broker/src/processor/pop_message_processor.rs
Labels: feature🚀, auto merge, ready to review, waiting-review, AI review first

#2719 [ISSUE #2718]Fix PopRequest#complete return value not correct
  rocketmq-broker/src/long_polling/pop_request.rs
Labels: bug🐛, auto merge, ready to review, waiting-review, AI review first

#2721 [ISSUE #2720]Add comments for PopMessageProcessor
  rocketmq-broker/src/processor/pop_message_processor.rs
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first

#2726 [ISSUE #2725]♻️Refactor MessageStore trait
  Cargo.lock
  rocketmq-store/Cargo.toml
  rocketmq-store/src/base/message_store.rs
  rocketmq-store/src/lib.rs
  rocketmq-store/src/store_error.rs
Labels: refactor♻️, auto merge, ready to review, waiting-review, AI review first

#2728 [ISSUE #2723]🚀Stepped message delay implementation🍻
  rocketmq-broker/src/broker_runtime.rs
  rocketmq-broker/src/schedule/delay_offset_serialize_wrapper.rs
  rocketmq-broker/src/schedule/schedule_message_service.rs
  rocketmq-broker/src/util/hook_utils.rs
  rocketmq-common/src/common/broker/broker_config.rs
  rocketmq-common/src/common/running/running_stats.rs
  rocketmq-store/src/config/message_store_config.rs
  rocketmq-store/src/log_file.rs
  rocketmq-store/src/log_file/commit_log.rs
  rocketmq-store/src/message_store/default_message_store.rs
  rocketmq-store/src/queue.rs
  rocketmq-store/src/queue/batch_consume_queue.rs
  rocketmq-store/src/queue/single_consume_queue.rs
Labels: feature🚀, auto merge, ready to review, waiting-review, AI review first

#2730 [ISSUE #2729]🚀Refactor LocalFileMessageStore-1🍻
  rocketmq-store/src/base/message_store.rs
  rocketmq-store/src/log_file/commit_log.rs
  rocketmq-store/src/message_store.rs
  rocketmq-store/src/message_store/local_file_message_store.rs
Labels: refactor♻️, auto merge, ready to review, waiting-review, AI review first

#2738 [ISSUE #2731]🚀Add HAError
  rocketmq-store/src/store_error.rs
Labels: feature🚀, auto merge, ready to review, waiting-review, AI review first

#2741 [ISSUE #2733]🚀Add HAConnectionStateNotificationRequest
  rocketmq-store/src/ha.rs
  rocketmq-store/src/ha/ha_connection_state_notification_request.rs
Labels: feature🚀, auto merge, ready to review, waiting-review, AI review first

#2742 [ISSUE #2735]🚀Add HAClient
  rocketmq-store/src/ha.rs
  rocketmq-store/src/ha/ha_client.rs
Labels: feature🚀, auto merge, ready to review, waiting-review, AI review first

#2743 [ISSUE #2736]🚀Add HAConnection
  rocketmq-store/src/ha.rs
  rocketmq-store/src/ha/ha_connection.rs
Labels: feature🚀, auto merge, ready to review, waiting-review, AI review first

#2744 [ISSUE #2737]🚀Add HAService
  Cargo.lock
  rocketmq-store/Cargo.toml
  rocketmq-store/src/ha.rs
  rocketmq-store/src/ha/ha_service.rs
Labels: feature🚀, auto merge, ready to review, waiting-review, AI review first

#2746 [ISSUE #2745]🚀Add GeneralHAService to wrapper DefaultHAService
  rocketmq-store/src/ha.rs
  rocketmq-store/src/ha/default_ha_service.rs
  rocketmq-store/src/ha/general_ha_service.rs
  rocketmq-store/src/ha/ha_service.rs
Labels: feature🚀, auto merge, ready to review, waiting-review, AI review first

#2748 [ISSUE #2747]♻️Refactor LocalFileMessageStore start method🍻
  rocketmq-store/src/base/allocate_mapped_file_service.rs
  rocketmq-store/src/base/store_stats_service.rs
  rocketmq-store/src/config/message_store_config.rs
  rocketmq-store/src/index/index_service.rs
  rocketmq-store/src/message_store/local_file_message_store.rs
Labels: refactor♻️, auto merge, ready to review, waiting-review, AI review first

#2750 [ISSUE #2749]♻️Refactor LocalFileMessageStore shutdown method🍻
  rocketmq-store/src/base/allocate_mapped_file_service.rs
  rocketmq-store/src/base/store_stats_service.rs
  rocketmq-store/src/config/message_store_config.rs
  rocketmq-store/src/index/index_service.rs
  rocketmq-store/src/kv/compaction_service.rs
  rocketmq-store/src/message_store/local_file_message_store.rs
Labels: refactor♻️, auto merge, ready to review, waiting-review, AI review first

#2754 [ISSUE #2753]🚀Implement LocalFileMessageStore destroy method🍻
  rocketmq-store/src/base/message_store.rs
  rocketmq-store/src/log_file/commit_log.rs
  rocketmq-store/src/message_store/local_file_message_store.rs
Labels: feature🚀, auto merge, ready to review, waiting-review, AI review first

#2757 [ISSUE #2755]♻️Refactor LocalFileMessage put message
  rocketmq-store/src/base/message_store.rs
  rocketmq-store/src/message_store/local_file_message_store.rs
Labels: refactor♻️, auto merge, ready to review, waiting-review, AI review first

#2759 [ISSUE #2758]♻️Refactor LocalFileMessage put batch messages
  rocketmq-store/src/message_store/local_file_message_store.rs
Labels: refactor♻️, auto merge, ready to review, waiting-review, AI review first

#2761 [ISSUE #2760]♻️Refactor LocalFileMessageStore get message
  rocketmq-store/src/base/message_store.rs
  rocketmq-store/src/message_store/local_file_message_store.rs
Labels: refactor♻️, auto merge, ready to review, waiting-review, AI review first

#2763 [ISSUE #2762]♻️Refactor LocalFileMessageStore get queue offset
  rocketmq-store/src/base/message_store.rs
  rocketmq-store/src/message_store/local_file_message_store.rs
Labels: refactor♻️, auto merge, ready to review, waiting-review, AI review first

#2765 [ISSUE #2764]♻️Refactor LocalFileMessageStore look message by offset
  rocketmq-store/src/base/message_store.rs
  rocketmq-store/src/message_store/local_file_message_store.rs
Labels: refactor♻️, auto merge, ready to review, waiting-review, AI review first

#2769 [ISSUE #2768]🚀Implement LocalFileMessageStore get runtime info method
  rocketmq-store/src/base/message_store.rs
  rocketmq-store/src/base/store_stats_service.rs
  rocketmq-store/src/message_store/local_file_message_store.rs
  rocketmq-store/src/timer/timer_message_store.rs
Labels: feature🚀, auto merge, ready to review, waiting-review, AI review first

#2771 [ISSUE #2770]🚀Implement earlist message time
  rocketmq-store/src/base/message_store.rs
  rocketmq-store/src/message_store/local_file_message_store.rs
Labels: feature🚀, auto merge, ready to review, waiting-review, AI review first

#2773 [ISSUE #2772]🚀Implement LocalFileMessageStore get commit log data
  rocketmq-store/src/base/message_store.rs
  rocketmq-store/src/log_file/commit_log.rs
  rocketmq-store/src/message_store/local_file_message_store.rs
Labels: feature🚀, auto merge, ready to review, waiting-review, AI review first

#2775 [ISSUE #2774]🚀Implement append_to_commit_log and execute_delete_files_manually methods
  rocketmq-store/src/log_file/commit_log.rs
  rocketmq-store/src/message_store/local_file_message_store.rs
Labels: feature🚀, auto merge, ready to review, waiting-review, AI review first

#2777 [ISSUE #2776]🚀Refactor LocalFileMessageStore methods🍻
  rocketmq-store/src/base/message_store.rs
  rocketmq-store/src/message_store/local_file_message_store.rs
Labels: refactor♻️, auto merge, ready to review, waiting-review, AI review first

#2779 [ISSUE #2778]🚀Replace DefaultMessageStore with LocalFileMessageStore🍻
  rocketmq-broker/src/broker_runtime.rs
  rocketmq-broker/src/failover/escape_bridge.rs
  rocketmq-broker/src/hook/check_before_put_message.rs
  rocketmq-broker/src/long_polling/long_polling_service/pop_long_polling_service.rs
  rocketmq-broker/src/long_polling/long_polling_service/pull_request_hold_service.rs
  rocketmq-broker/src/long_polling/notify_message_arriving_listener.rs
  rocketmq-broker/src/offset/manager/consumer_offset_manager.rs
  rocketmq-broker/src/offset/manager/consumer_order_info_manager.rs
  rocketmq-broker/src/out_api/broker_outer_api.rs
  rocketmq-broker/src/processor.rs
  rocketmq-broker/src/processor/ack_message_processor.rs
  rocketmq-broker/src/processor/admin_broker_processor.rs
  rocketmq-broker/src/processor/admin_broker_processor/batch_mq_handler.rs
  rocketmq-broker/src/processor/admin_broker_processor/broker_config_request_handler.rs
  rocketmq-broker/src/processor/admin_broker_processor/consumer_request_handler.rs
  rocketmq-broker/src/processor/admin_broker_processor/offset_request_handler.rs
  rocketmq-broker/src/processor/admin_broker_processor/topic_request_handler.rs
  rocketmq-broker/src/processor/change_invisible_time_processor.rs
  rocketmq-broker/src/processor/client_manage_processor.rs
  rocketmq-broker/src/processor/consumer_manage_processor.rs
  rocketmq-broker/src/processor/default_pull_message_result_handler.rs
  rocketmq-broker/src/processor/end_transaction_processor.rs
  rocketmq-broker/src/processor/pop_message_processor.rs
  rocketmq-broker/src/processor/processor_service/pop_buffer_merge_service.rs
  rocketmq-broker/src/processor/processor_service/pop_revive_service.rs
  rocketmq-broker/src/processor/pull_message_processor.rs
  rocketmq-broker/src/processor/query_assignment_processor.rs
  rocketmq-broker/src/processor/query_message_processor.rs
  rocketmq-broker/src/processor/reply_message_processor.rs
  rocketmq-broker/src/processor/send_message_processor.rs
  rocketmq-broker/src/schedule/schedule_message_service.rs
  rocketmq-broker/src/subscription/manager/subscription_group_manager.rs
  rocketmq-broker/src/topic/manager/topic_config_manager.rs
  rocketmq-broker/src/topic/manager/topic_route_info_manager.rs
  rocketmq-broker/src/transaction/queue/default_transactional_message_check_listener.rs
  rocketmq-broker/src/transaction/queue/default_transactional_message_service.rs
  rocketmq-broker/src/transaction/queue/transactional_message_bridge.rs
  rocketmq-broker/src/util/hook_utils.rs
  rocketmq-store/src/base/message_store.rs
  rocketmq-store/src/ha/default_ha_service.rs
  rocketmq-store/src/ha/general_ha_service.rs
  rocketmq-store/src/ha/ha_service.rs
  rocketmq-store/src/log_file.rs
  rocketmq-store/src/log_file/commit_log.rs
  rocketmq-store/src/message_store/default_message_store.rs
  rocketmq-store/src/message_store/local_file_message_store.rs
  rocketmq-store/src/queue/local_file_consume_queue_store.rs
  rocketmq-store/src/stats/broker_stats.rs
  rocketmq-store/src/timer/timer_message_store.rs
Labels: refactor♻️, auto merge, ready to review, waiting-review, AI review first

#2781 [ISSUE #2780] fix typo. borker -> broker
  README.md
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first

#2783 [ISSUE #2782]🔨Update automerge.yml
  .github/workflows/automerge.yml
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first

#2785 [ISSUE #2784]🚀Rename ReferenceResourceImpl to ReferenceResourceCounter🍻
  rocketmq-store/src/log_file/mapped_file.rs
  rocketmq-store/src/log_file/mapped_file/default_mapped_file_impl.rs
  rocketmq-store/src/log_file/mapped_file/reference_resource_counter.rs
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first

#2787 [ISSUE #2786]🚀Refactor ReferenceResourceCounter🍻
  rocketmq-store/src/log_file/mapped_file/reference_resource_counter.rs
Labels: refactor♻️, auto merge, ready to review, waiting-review, AI review first

#2792 [ISSUE #2791]🚀Optimize client_metadata cargo clippy -- -D warnings🍻
  rocketmq-remoting/src/rpc/client_metadata.rs
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first

#2789 [ISSUE #2788]🚀Optimize DefaultMappedFile ReferenceResourceCounter hold and release🍻
  rocketmq-store/src/log_file/mapped_file/default_mapped_file_impl.rs
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first

#2793 [ISSUE #2790]🚀Implement ScheduleMessageService#load method🍻
  rocketmq-broker/src/schedule/schedule_message_service.rs
  rocketmq-broker/src/topic/manager/topic_config_manager.rs
  rocketmq-common/src/common/config_manager.rs
  rocketmq-store/src/base/message_store.rs
  rocketmq-store/src/message_store/local_file_message_store.rs
Labels: feature🚀, auto merge, ready to review, waiting-review, AI review first

#2796 [ISSUE #2795]🐛Fix ScheduleMessageService start eq not correct🍻
  rocketmq-broker/src/schedule/schedule_message_service.rs
Labels: bug🐛, auto merge, ready to review, waiting-review, AI review first

#2797 [ISSUE #2727]🚀Stepped message delay implementation-2🍻
  rocketmq-broker/src/schedule/schedule_message_service.rs
Labels: feature🚀, auto merge, ready to review, waiting-review, AI review first

#2800 [ISSUE #2799]🚀Implement LocalFileMessageStore#find_consume_queue🍻
  rocketmq-store/src/message_store/local_file_message_store.rs
Labels: feature🚀, auto merge, ready to review, waiting-review, AI review first

#2804 [ISSUE #2803]📝Add code comments for ScheduleMessageService 🍻
  rocketmq-broker/src/schedule/schedule_message_service.rs
Labels: documentation📝, auto merge, ready to review, waiting-review, AI review first

#2806 [ISSUE #2805]📝Replace MessageStore methods &str parameters with &CheetahString🍻
  rocketmq-store/src/base/message_store.rs
  rocketmq-store/src/message_store/local_file_message_store.rs
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first

#2809 [ISSUE #2808]⚡️Replace PutResultProcess attributes String with CheetahString🍻
  rocketmq-broker/src/schedule/schedule_message_service.rs
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first

#2811 [ISSUE #2810]⚡️BrokerRuntimeInner add some unchecked methods for Option attributes🍻
  rocketmq-broker/src/broker_runtime.rs
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first

#2812 [ISSUE #2807]🚀Implement ScheduleMessageService#message_time_up method🍻
  rocketmq-broker/src/schedule/schedule_message_service.rs
Labels: feature🚀, auto merge, ready to review, waiting-review, AI review first

#2818 [ISSUE #2817]📝Add Architecture pitcture for doc🍻
  rocketmq-doc/_docs/01-architecture.md
Labels: documentation📝, auto merge, ready to review, waiting-review, AI review first

#2822 [ISSUE #2820]📝Add Architecture en doc
  rocketmq-doc/_docs/01-architecture.md
Labels: documentation📝, auto merge, ready to review, waiting-review, AI review first

#2824 [ISSUE #2823]🚀Add BrokerAttachedPlugin trait
  rocketmq-broker/src/lib.rs
  rocketmq-broker/src/plugin.rs
  rocketmq-broker/src/plugin/broker_attached_plugin.rs
Labels: feature🚀, auto merge, ready to review, waiting-review, AI review first

#2825 [ISSUE #2814]🚀Implement BrokerRuntime#changeSpecialServiceStatus method
  rocketmq-broker/src/broker_runtime.rs
  rocketmq-broker/src/processor/ack_message_processor.rs
Labels: feature🚀, auto merge, ready to review, waiting-review, AI review first

#2826 [ISSUE #2815]🚀Implement BrokerRuntime changeScheduleServiceStatus method
  rocketmq-broker/src/broker_runtime.rs
  rocketmq-store/src/timer/timer_message_store.rs
Labels: feature🚀, auto merge, ready to review, waiting-review, AI review first

#2829 [ISSUE #2828]🚀Implement AckMessageProcessor#set_pop_revive_service_st…
  rocketmq-broker/src/processor/ack_message_processor.rs
  rocketmq-broker/src/processor/processor_service/pop_revive_service.rs
Labels: feature🚀, auto merge, ready to review, waiting-review, AI review first

#2827 [ISSUE #2816]🚀Implement BrokerRuntime changeTransactionCheckServiceSt…
  rocketmq-broker/src/broker_runtime.rs
  rocketmq-broker/src/transaction/transactional_message_check_service.rs
Labels: feature🚀, auto merge, ready to review, waiting-review, AI review first

#2834 [ISSUE #2833]🐛Fix MessageStoreConfig flush_delay_offset_interval value is zero
  rocketmq-store/src/config/message_store_config.rs
Labels: bug🐛, auto merge, ready to review, waiting-review, AI review first

#2837 [ISSUE #2835]🚀Implement LocalFileMessageStore#get_message_store_config method
  rocketmq-store/src/base/message_store.rs
  rocketmq-store/src/message_store/local_file_message_store.rs
Labels: feature🚀, auto merge, ready to review, waiting-review, AI review first

#2844 [ISSUE #2843]🚀Add build.rs for rocketmq-broker crate
  rocketmq-broker/build.rs
Labels: feature🚀, auto merge, ready to review, waiting-review, AI review first

#2847 [ISSUE #2846]⚡️Optimize PutMessageHook#execute_before_put_message method signature
  rocketmq-broker/src/hook/batch_check_before_put_message.rs
  rocketmq-broker/src/hook/check_before_put_message.rs
  rocketmq-store/src/hook/put_message_hook.rs
  rocketmq-store/src/message_store/default_message_store.rs
  rocketmq-store/src/message_store/local_file_message_store.rs
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first

#2849 [ISSUE #2848]⚡️Optimize PutMessageHook#execute_before_put_message
  rocketmq-broker/src/hook/batch_check_before_put_message.rs
  rocketmq-broker/src/hook/check_before_put_message.rs
  rocketmq-store/src/hook/put_message_hook.rs
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first

#2851 [ISSUE #2850]⚡️Optimize HookUtils some methods
  rocketmq-broker/src/util/hook_utils.rs
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first

#2852 [ISSUE #2845]🚀Add ScheduleMessageHook struct
  rocketmq-broker/src/hook.rs
  rocketmq-broker/src/hook/schedule_message_hook.rs
Labels: feature🚀, auto merge, ready to review, waiting-review, AI review first

#2858 [ISSUE #2857]♻️Refactor PutResultProcess
  rocketmq-broker/src/schedule/schedule_message_service.rs
Labels: refactor♻️, auto merge, ready to review, waiting-review, AI review first

#2860 [ISSUE #2859]🚀Implement PutResultProcess#then_process method
  rocketmq-broker/src/schedule/schedule_message_service.rs
Labels: feature🚀, auto merge, ready to review, waiting-review, AI review first

#2866 [ISSUE #2865]🚀Add StringUtils#parse_delay_level method
  rocketmq-common/src/utils/string_utils.rs
Labels: feature🚀, auto merge, ready to review, waiting-review, AI review first

#2867 [ISSUE #2863]🚀Implement handle Timing message in CommitLog#check_message_and_return_size method
  rocketmq-broker/src/broker_runtime.rs
  rocketmq-store/src/log_file/commit_log.rs
  rocketmq-store/src/message_store/default_message_store.rs
  rocketmq-store/src/message_store/local_file_message_store.rs
Labels: feature🚀, auto merge, ready to review, waiting-review, AI review first

#2873 [ISSUE #2872]🐛Fix Rebuild Properties not correct
  rocketmq-store/src/log_file/commit_log.rs
Labels: bug🐛, auto merge, ready to review, waiting-review, AI review first

#2877 [ISSUE #2875]⚡️Optimize RouteInfoManager#register_broker
  rocketmq-namesrv/src/route/route_info_manager.rs
  rocketmq-remoting/src/protocol/route/route_data_view.rs
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first

#2879 [ISSUE #2876]⚡️Add #[inline] to ArcMut methods
  CHANGELOG.md
  rocketmq/src/arc_mut.rs
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first

#2881 [ISSUE #2861]📝Add doc for IndexHeader 💫
  rocketmq-store/src/index/index_header.rs
Labels: documentation📝, auto merge, ready to review, waiting-review, AI review first

#2885 [ISSUE #2884]♻️Refactor IndexHeader
  rocketmq-store/src/index/index_header.rs
Labels: refactor♻️, auto merge, ready to review, waiting-review, AI review first

#2887 [ISSUE #2886]⚡️Remove some #[inline] from IndexFile methods
  rocketmq-store/src/index/index_file.rs
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first

#2891 [ISSUE #2890]🐛Key hash code abs may with panic
  rocketmq-store/src/index/index_file.rs
Labels: bug🐛, auto merge, ready to review, waiting-review, AI review first

#2893 [ISSUE #2892]⚡️Replace IndexHeader wite data method append_message_offset_length
  rocketmq-store/src/index/index_header.rs
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first

#2894 [ISSUE #2871]🐛Reput Message to build index error
  rocketmq-store/src/index/index_file.rs
Labels: bug🐛, auto merge, ready to review, waiting-review, AI review first

#2896 [ISSUE #2895]🚀MappedFile add get_slice method
  rocketmq-store/src/log_file/mapped_file.rs
  rocketmq-store/src/log_file/mapped_file/default_mapped_file_impl.rs
Labels: feature🚀, auto merge, ready to review, waiting-review, AI review first

#2898 [ISSUE #2897]♻️Refactor IndexFile#select_phy_offset method
  rocketmq-store/src/index/index_file.rs
Labels: refactor♻️, auto merge, ready to review, waiting-review, AI review first

#2900 [ISSUE #2899]⚡️Optimize util_all#time_millis_to_human_string method
  rocketmq-common/src/utils/util_all.rs
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first

#2902 [ISSUE #2901]🧪Add test case for time_millis_to_human_string3
  rocketmq-common/src/utils/util_all.rs
Labels: auto merge, ready to review, waiting-review, AI review first, testing🧪

#2905 [ISSUE #2904]📝Add Namesrv config 💫
  distribution/config/namesrv.conf
  distribution/config/namesrv.toml
Labels: feature🚀, auto merge, ready to review, waiting-review, AI review first

#2908 [ISSUE #2907]🚀Implement IndexService shutdown💫
  rocketmq-store/src/index/index_service.rs
Labels: feature🚀, auto merge, ready to review, waiting-review, AI review first

#2910 [ISSUE #2909]🚀Optimize IndexService load💫
  rocketmq-store/src/index/index_service.rs
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first

#2912 [ISSUE #2911]⚡️Remove IndexService some methods #[inline]💫
  rocketmq-store/src/index/index_service.rs
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first

#2914 [ISSUE #2913]⚡️Optimize get_total_size method💫
  rocketmq-store/src/index/index_service.rs
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first

#2916 [ISSUE #2915]🚀Complete the IndexService delete_expired_file method💫
  rocketmq-store/src/index/index_service.rs
Labels: feature🚀, auto merge, ready to review, waiting-review, AI review first

#2919 [ISSUE #2918]🚀Optimize IndexService query_offset💫
  rocketmq-store/src/index/index_service.rs
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first

#2921 [ISSUE #2920]🚀Optimize IndexService build_index and others methods💫
  rocketmq-store/src/index/index_service.rs
  rocketmq-store/src/message_store/default_message_store.rs
  rocketmq-store/src/message_store/local_file_message_store.rs
Labels: enhancement⚡️, feature🚀, auto merge, ready to review, waiting-review, AI review first

#2923 [ISSUE #2922]🚀Optimize Name server config file parse💫
  rocketmq-common/src/utils/env_utils.rs
  rocketmq-namesrv/src/bin/namesrv_bootstrap_server.rs
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first

#2927 [ISSUE #2926]🐛Fix EnvUtils::put_property test case error💫
  rocketmq-common/src/utils/env_utils.rs
Labels: bug🐛, auto merge, ready to review, waiting-review, AI review first

#2925 [ISSUE #2924]📝Update rocketmq namesrv start command help print💫
  README.md
  rocketmq-namesrv/README.md
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first

#2929 [ISSUE #2928]⚡️Optimize namesrv parse config error print
  rocketmq-namesrv/src/bin/namesrv_bootstrap_server.rs
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first

#2931 [ISSUE #2930]⚡️Optimize DefaultRequestProcessor#put_kv_config method
  rocketmq-namesrv/src/processor/default_request_processor.rs
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first

#2938 [ISSUE #2937]⚡️Add the PopReviveService log print decision💫
  rocketmq-broker/src/processor/processor_service/pop_revive_service.rs
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first

#2940 [ISSUE #2939]✨Implement LocalFileMessageStore#get_broker_stats_manager💫
  rocketmq-store/src/message_store/local_file_message_store.rs
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first
