Repository mxsm/rocketmq-rust, pull requests merged in 2025-05, with the labels that each got.

#3176 [ISSUE #3166]📝Update README.md
  README.md
Labels: documentation📝, auto merge, ready to review, waiting-review, AI review first

#3178 [ISSUE #3177]🚀Implement NotificationProcessor start and shutdown
  rocketmq-broker/src/processor/notification_processor.rs
Labels: feature🚀, auto merge, ready to review, waiting-review, AI review first

#3180 [ISSUE #3179]⚡️Optimize ScheduleMessageService
  rocketmq-broker/src/schedule/schedule_message_service.rs
  rocketmq-broker/src/util/hook_utils.rs
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first

#3182 [ISSUE #3181]⚡️Remove BrokerRuntime useless code
  rocketmq-broker/src/broker_runtime.rs
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first

#3184 [ISSUE #3183]🚀Implement LocalFileMessageStore get_dispatcher_list and add_dispatcher methods
  rocketmq-store/src/base/message_store.rs
  rocketmq-store/src/log_file/commit_log.rs
  rocketmq-store/src/message_store/local_file_message_store.rs
Labels: feature🚀, auto merge, ready to review, waiting-review, AI review first

#3189 [ISSUE #3187]🚀Implement CommitLogDispatcherCalcBitMap
  rocketmq-broker/src/filter.rs
  rocketmq-broker/src/filter/commit_log_dispatcher_calc_bit_map.rs
  rocketmq-broker/src/filter/consumer_filter_data.rs
  rocketmq-broker/src/filter/expression_message_filter.rs
  rocketmq-broker/src/filter/manager/consumer_filter_manager.rs
  rocketmq-broker/src/filter/message_evaluation_context.rs
  rocketmq-common/src/common/broker/broker_config.rs
  rocketmq-filter/src/expression.rs
  rocketmq-filter/src/utils.rs
  rocketmq-filter/src/utils/bits_array.rs
  rocketmq-filter/src/utils/bloom_filter.rs
  rocketmq-store/src/base.rs
  rocketmq-store/src/base/commit_log_dispatcher.rs
  rocketmq-store/src/index/index_dispatch.rs
  rocketmq-store/src/log_file/commit_log.rs
  rocketmq-store/src/message_store/local_file_message_store.rs
  rocketmq-store/src/queue/build_consume_queue.rs
Labels: feature🚀, auto merge, ready to review, waiting-review, AI review first

#3191 [ISSUE #3190]🚀BrokerRutime message store add CommitLogDispatcherCalcBitMap
  rocketmq-broker/src/broker_bootstrap.rs
  rocketmq-broker/src/broker_runtime.rs
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first

#3193 [ISSUE #3192]🚀Replace MessageStoreConfig and ServerConfig with Arc in BrokerRuntime
  rocketmq-broker/src/broker_bootstrap.rs
  rocketmq-broker/src/broker_runtime.rs
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first

#3197 [ISSUE #3196]🚀Implement ConsumeQueueStore recover_concurrently
  Cargo.lock
  rocketmq-store/Cargo.toml
  rocketmq-store/src/queue/local_file_consume_queue_store.rs
Labels: feature🚀, auto merge, ready to review, waiting-review, AI review first

#3199 [ISSUE #3198]🚀Implement ConsumeQueueStore#check_self
  rocketmq-store/src/message_store/local_file_message_store.rs
  rocketmq-store/src/queue/local_file_consume_queue_store.rs
Labels: feature🚀, auto merge, ready to review, waiting-review, AI review first

#3201 [ISSUE #3200]🚀Add Slot struct for Timer message
  rocketmq-store/src/timer.rs
  rocketmq-store/src/timer/slot.rs
Labels: feature🚀, auto merge, ready to review, waiting-review, AI review first

#3203 [ISSUE #3202]🚀Optimize SendMessageProcessor code
  rocketmq-broker/src/processor/send_message_processor.rs
  rocketmq-broker/src/topic/manager/topic_queue_mapping_manager.rs
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first

#3205 [ISSUE #3204]🚀Optimize ValidateTopicResult add take_remark method
  rocketmq-broker/src/processor/send_message_processor.rs
  rocketmq-broker/src/topic/manager/topic_config_manager.rs
  rocketmq-common/src/common/broker/broker_config.rs
  rocketmq-common/src/common/topic.rs
  rocketmq-remoting/src/protocol/remoting_command.rs
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first

#3207 [ISSUE #3204]⚡️Remove use lazy_static::lazy_static in TopicAttributes
  rocketmq-common/src/common/attribute/topic_attributes.rs
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first

#3209 [ISSUE #3208]⚡️Optimize TopicValidator
  rocketmq-common/src/common/topic.rs
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first

#3210 [ISSUE #3018]⚡️Add #[inline] for PermName's methods
  rocketmq-common/src/common/constant.rs
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first, Difficulty level/Easy

#3212 [ISSUE #3211]⚡️Optimize TopicConfigManager#init method
  rocketmq-broker/src/broker_runtime.rs
  rocketmq-broker/src/topic/manager/topic_config_manager.rs
  rocketmq-common/src/common/topic.rs
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first

#3213 [ISSUE #2704]⚡️Optimize broker_bootstrap_server log init
  Cargo.lock
  rocketmq-broker/src/bin/broker_bootstrap_server.rs
  rocketmq-broker/src/processor/query_assignment_processor.rs
  rocketmq-broker/src/util/hook_utils.rs
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first

#3214 [ISSUE #2932]♻️Refactor WipeWritePermOfBrokerResponseHeader with derive marco RequestHeaderCodec
  rocketmq-remoting/src/protocol/header/namesrv/perm_broker_header.rs
Labels: refactor♻️, auto merge, ready to review, waiting-review, AI review first, Difficulty level/Easy

#3217 [ISSUE #3215]⚡️Implement BrokerRuntime#register_increment_broker_data
  rocketmq-broker/src/broker_runtime.rs
Labels: feature🚀, auto merge, ready to review, waiting-review, AI review first

#3218 [ISSUE #2933]♻️Refactor AddWritePermOfBrokerRequestHeader with derive marco RequestHeaderCodec
  rocketmq-remoting/src/protocol/header/namesrv/perm_broker_header.rs
Labels: refactor♻️, auto merge, ready to review, waiting-review, AI review first, Difficulty level/Easy

#3219 [ISSUE #3216]⚡️Implement BrokerRuntime#register_increment_broker_data
  rocketmq-broker/src/broker_runtime.rs
  rocketmq-broker/src/topic/manager/topic_config_manager.rs
Labels: feature🚀, auto merge, ready to review, waiting-review, AI review first

#3223 [ISSUE #3222]⚡️Add rocketmq-rust logo
  resources/logo.png
Labels: documentation📝, auto merge, ready to review, waiting-review, AI review first

#3225 [ISSUE #3224]⚡️Add rocketmq-rust logo
  resources/logo.png
Labels: documentation📝, auto merge, ready to review, waiting-review, AI review first

#3226 [ISSUE #3221]📝Update README.md
  README.md
Labels: documentation📝, auto merge, ready to review, waiting-review, AI review first

#3228 [ISSUE #3227]♻️Refactor SendMessageProcessor handle_put_message_result
  rocketmq-broker/src/processor/send_message_processor.rs
  rocketmq-remoting/src/connection.rs
  rocketmq-remoting/src/runtime/connection_handler_context.rs
Labels: refactor♻️, auto merge, ready to review, waiting-review, AI review first

#3238 [ISSUE #3237]⚡️Optimize SendMessageProcessor send_message
  rocketmq-broker/src/processor/send_message_processor.rs
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first

#3242 [ISSUE #3241]📝Update READM.md
  README.md
Labels: documentation📝, auto merge, ready to review, waiting-review, AI review first

#3244 [ISSUE #3243]📝Update README.md
  README.md
Labels: documentation📝, auto merge, ready to review, waiting-review, AI review first

#3240 [ISSUE #2794]Improve KVConfigManager perfermance with DashHashp
  Cargo.lock
  rocketmq-namesrv/Cargo.toml
  rocketmq-namesrv/src/kvconfig.rs
  rocketmq-namesrv/src/kvconfig/kvconfig_mananger.rs
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first

#3247 [ISSUE #3246]⚡️Optimize MessageExtEncoder performance
  rocketmq-common/src/common/message/message_ext_broker_inner.rs
  rocketmq-store/src/log_file/commit_log.rs
  rocketmq-store/src/message_encoder/message_ext_encoder.rs
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first

#3249 [ISSUE #3248]📝Add DeepWiki badge
  README.md
Labels: documentation📝, auto merge, ready to review, waiting-review, AI review first

#3251 [ISSUE #3250]⚡️Replace MessageIdSupplier Box with Arc
  rocketmq-store/src/base/append_message_callback.rs
  rocketmq-store/src/base/message_result.rs
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first

#3253 [ISSUE #3252]🐛Fix DefaultMappedFile Dangling Reference issue
  rocketmq-store/src/log_file/mapped_file/default_mapped_file_impl.rs
Labels: bug🐛, auto merge, ready to review, waiting-review, AI review first

#3255 [ISSUE #3254]⚡️Optimize ArcMut
  rocketmq/src/arc_mut.rs
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first

#3257 [ISSUE #3256]⚡️Optimize PutMessageThreadLocal performance
  rocketmq-store/src/log_file/commit_log.rs
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first

#3259 [ISSUE #3258]⚡️Optimize TopicQueueLock
  rocketmq-store/src/base/topic_queue_lock.rs
  rocketmq-store/src/log_file/commit_log.rs
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first

#3261 [ISSUE #3260]📝Remove Associate Milestone action
  .github/workflows/associate_milestone_issue.yml
  .github/workflows/associate_milestone_pr.yml
Labels: documentation📝, auto merge, ready to review, waiting-review, AI review first

#3265 [ISSUE #3264]🚀RequestCode enum add more request code
  rocketmq-remoting/src/code/request_code.rs
Labels: feature🚀, auto merge, ready to review, waiting-review, AI review first

#3268 [ISSUE #3267]♻️Refactor PutMessageHook trait
  rocketmq-broker/src/hook/batch_check_before_put_message.rs
  rocketmq-broker/src/hook/check_before_put_message.rs
  rocketmq-broker/src/hook/schedule_message_hook.rs
  rocketmq-broker/src/util/hook_utils.rs
  rocketmq-store/src/hook/put_message_hook.rs
Labels: refactor♻️, auto merge, ready to review, waiting-review, AI review first

#3273 [ISSUE #3269]⚡️Optimize use of unstable library feature duration_constructors_lite
  rocketmq-broker/src/filter/manager/consumer_filter_manager.rs
  rocketmq-broker/src/lib.rs
  rocketmq-remoting/src/lib.rs
  rocketmq-remoting/src/protocol/subscription/exponential_retry_policy.rs
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first, Difficulty level/Easy

#3245 [Feature🚀] Implement NotificationProcessor acording to Java code
  rocketmq-broker/src/long_polling/long_polling_service/pop_long_polling_service.rs
  rocketmq-broker/src/processor/notification_processor.rs
  rocketmq-remoting/src/net/channel.rs
  rocketmq-remoting/src/remoting_server/server.rs
Labels: feature🚀, auto merge, ready to review, waiting-review, AI review first, Difficulty level/Moderate, rocketmq-broker crate

#3275 [Doc📝] Documentation Related ：Update Feature list in rocketmq-broker README.md
  rocketmq-broker/README.md
Labels: documentation📝, auto merge, ready to review, waiting-review, AI review first

#3276 [ISSUE #3279]📝Documentation Related ：Update Feature list in rocketmq-broker README.md
  rocketmq-broker/README.md
Labels: documentation📝, auto merge, ready to review, waiting-review, AI review first

#3281 [ISSUE #3280]⚡️Fix cargo clippy -- -D warnings error
  rocketmq-broker/src/filter/expression_message_filter.rs
  rocketmq-broker/src/long_polling/long_polling_service/pop_long_polling_service.rs
  rocketmq-broker/src/processor/pull_message_processor.rs
  rocketmq-client/src/consumer/consumer_impl/consume_message_concurrently_service.rs
  rocketmq-client/src/consumer/consumer_impl/consume_message_orderly_service.rs
  rocketmq-client/src/consumer/consumer_impl/consume_message_pop_concurrently_service.rs
  rocketmq-client/src/consumer/consumer_impl/default_mq_push_consumer_impl.rs
  rocketmq-client/src/consumer/consumer_impl/re_balance/rebalance_impl.rs
  rocketmq-client/src/factory/mq_client_instance.rs
  rocketmq-client/src/implementation/mq_client_api_impl.rs
  rocketmq-client/src/producer/default_mq_producer.rs
  rocketmq-common/src/common/message/message_batch.rs
  rocketmq-namesrv/src/route/route_info_manager.rs
  rocketmq-store/src/consume_queue/mapped_file_queue.rs
  rocketmq-store/src/log_file/commit_log.rs
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first

#3283 [ISSUE #3282]⚡️Add Release Notes for Version 0.5.0
  distribution/package_publish_workspace.bat
  rocketmq-doc/_docs/03-roadmap.md
  rocketmq-doc/_pages/home.md
  rocketmq-doc/_pages/release-notes.md
  rocketmq-doc/_posts/2025-05-19-release-v0.5.0.md
Labels: documentation📝, auto merge, ready to review, waiting-review, AI review first

#3285 [ISSUE #3284]📝Update to Version 0.6.0 for Next-Stage Development
  Cargo.lock
  Cargo.toml
Labels: feature🚀, auto merge, ready to review, waiting-review, AI review first

#3289 [ISSUE #3288]📝Update package_publish_workspace script
  distribution/package_publish_workspace.bat
  distribution/package_publish_workspace.sh
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first

#3297 [ISSUE #3296]⚡️Optimize rocketmq-example crate Cargo.toml
  rocketmq-example/Cargo.toml
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first

#3299 [ISSUE #3298]Remove dead code from the LocalFileMessageStore
  rocketmq-store/src/message_store/local_file_message_store.rs
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first, Difficulty level/Easy

#3301 [ISSUE #3300]⚡️Optimize CommitLog put_message and put_messages methods signature
  rocketmq-store/src/log_file/commit_log.rs
  rocketmq-store/src/message_store/local_file_message_store.rs
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first

#3303 [ISSUE #3302]⚡️Remove LocalFileMessageStore useless code
  rocketmq-store/src/message_store/local_file_message_store.rs
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first

#3306 [ISSUE #3305]🚀CommitLog put messages add unlockMappedFile logic
  rocketmq-store/src/base/message_store.rs
  rocketmq-store/src/log_file/commit_log.rs
  rocketmq-store/src/message_store/local_file_message_store.rs
Labels: feature🚀, auto merge, ready to review, waiting-review, AI review first

#3311 [ISSUE #3310]🚀Add the second-level command show
  Cargo.lock
  rocketmq-tools/Cargo.toml
  rocketmq-tools/src/bin/rocketmq_admin_cli.rs
  rocketmq-tools/src/commands.rs
  rocketmq-tools/src/rocketmq_cli.rs
Labels: feature🚀, auto merge, ready to review, waiting-review, AI review first

#3324 [ISSUE #3323]🚀Change common arg namesrvAddr required to false💫
  rocketmq-tools/src/commands.rs
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first

#3326 [ISSUE #3325]⚡️Change CommandExecute#execute as async
  rocketmq-tools/src/admin/default_mq_admin_ext.rs
  rocketmq-tools/src/bin/rocketmq_admin_cli.rs
  rocketmq-tools/src/commands.rs
  rocketmq-tools/src/commands/namesrv_commands.rs
  rocketmq-tools/src/commands/namesrv_commands/get_namesrv_config_command.rs
  rocketmq-tools/src/commands/topic_commands.rs
  rocketmq-tools/src/commands/topic_commands/allocate_mq_sub_command.rs
  rocketmq-tools/src/rocketmq_cli.rs
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first

#3329 [ISSUE #3328]🐛Fix MQClientInstance start fetch_name_server_addr error💫
  rocketmq-client/src/implementation/mq_client_api_impl.rs
  rocketmq-common/Cargo.toml
  rocketmq-common/src/common/namesrv/default_top_addressing.rs
  rocketmq-common/src/utils/http_tiny_client.rs
Labels: bug🐛, auto merge, ready to review, waiting-review, AI review first

#3331 [ISSUE #3330]⚡️Unify the JSON data format returned by GET_NAMESRV_CONFIG in Rust and Java versions💫
  rocketmq-common/src/common/namesrv/namesrv_config.rs
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first

#3293 [ISSUE #3295]add updateAndSubscripGroup func
  rocketmq-broker/src/processor/admin_broker_processor.rs
  rocketmq-broker/src/processor/admin_broker_processor/subscription_group_handler.rs
  rocketmq-broker/src/subscription/manager/subscription_group_manager.rs
  rocketmq-common/src/common/attribute.rs
  rocketmq-common/src/common/attribute/subscription_group_attributes.rs
  rocketmq-common/src/utils/file_utils.rs
  rocketmq-error/src/lib.rs
Labels: feature🚀, auto merge, ready to review, waiting-review, AI review first

#3333 [ISSUE #3315]🚀Implement GetNamesrvConfigCommand for name server tool💫
  Cargo.lock
  rocketmq-client/src/admin/default_mq_admin_ext_impl.rs
  rocketmq-client/src/implementation/mq_client_api_impl.rs
  rocketmq-tools/Cargo.toml
  rocketmq-tools/src/commands/namesrv_commands/get_namesrv_config_command.rs
Labels: feature🚀, auto merge, ready to review, waiting-review, AI review first

#3338 [ISSUE #3337]📝Add TransactionalMessageBridge#parse_half_message_inner💫
  rocketmq-broker/src/transaction/queue/transactional_message_bridge.rs
Labels: documentation📝, auto merge, ready to review, waiting-review, AI review first

#3339 [ISSUE #3335 ]Remove useless code from TransactionalMessageBridge
  rocketmq-broker/src/transaction/queue/transactional_message_bridge.rs
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first, Difficulty level/Easy

#3351 [ISSUE #3316]🚀Implement UpdateKvConfigCommand for name server tool
  rocketmq-client/src/admin/default_mq_admin_ext_impl.rs
  rocketmq-client/src/base/client_config.rs
  rocketmq-client/src/implementation/mq_client_api_impl.rs
  rocketmq-tools/src/admin/default_mq_admin_ext.rs
  rocketmq-tools/src/commands/namesrv_commands.rs
  rocketmq-tools/src/commands/namesrv_commands/update_kv_config_command.rs
Labels: feature🚀, auto merge, ready to review, waiting-review, AI review first, Difficulty level/Moderate, rocketmq-tools crate

#3353 [ISSUE #3352]🚀Add Transaction Producer documentation and update navigation structure💫
  rocketmq-doc/_data/navigation.yml
  rocketmq-doc/_docs/01-transaction-producer.md
Labels: documentation📝, auto merge, ready to review, waiting-review, AI review first
