Repository mxsm/rocketmq-rust, pull requests merged in 2025-01, with the labels that each got.

#1985 [ISSUE #1984]♻️Develop SearchInputWidget for tui🚀
  rocketmq-tui/src/rocketmq_tui_app.rs
  rocketmq-tui/src/ui.rs
  rocketmq-tui/src/ui/search_input_widget.rs
Labels: feature, auto merge, ready to review, waiting-review, AI review first, rocketmq-tui crate

#1988 [ISSUE #1987]⚡️Remove useless crate from cargo.toml🚀
  Cargo.toml
Labels: enhancement, auto merge, ready to review, waiting-review, AI review first

#1990 [ISSUE #1989]⚡️Add strum crate🚀
  Cargo.toml
Labels: feature, auto merge, ready to review, waiting-review, AI review first

#1993 [ISSUE #1992]🍻Implement PopMessageProcessor#get_init_offset method logic🚀
  rocketmq-broker/src/offset/manager/consumer_offset_manager.rs
  rocketmq-broker/src/processor/ack_message_processor.rs
  rocketmq-broker/src/processor/consumer_manage_processor.rs
  rocketmq-broker/src/processor/default_pull_message_result_handler.rs
  rocketmq-broker/src/processor/pop_message_processor.rs
  rocketmq-broker/src/transaction/queue/transactional_message_bridge.rs
  rocketmq-common/src/common/broker/broker_config.rs
Labels: feature, auto merge, ready to review, waiting-review, AI review first, rocketmq-broker crate

#1995 [ISSUE #1994]🔨Update Github workflow action
  .github/reviewers.yml
Labels: documentation, auto merge, ready to review, waiting-review, AI review first

#1999 [ISSUE #1998]🔨Update Github workflow action
  .github/reviewers.yml
Labels: documentation, auto merge, ready to review, waiting-review, AI review first

#1997 [ISSUE #1996]🍻Implement PopMessageProcessor#reset_pop_offset method logic🚀
  rocketmq-broker/src/offset/manager/consumer_order_info_manager.rs
  rocketmq-broker/src/processor/pop_message_processor.rs
  rocketmq-broker/src/processor/processor_service/pop_buffer_merge_service.rs
Labels: feature, wip, rust, auto merge, ready to review, waiting-review, AI review first, rocketmq-broker crate

#2001 [ISSUE #2000]🍻Implement PopMessageProcessor#queue_lock_manager🚀
  rocketmq-broker/src/processor/pop_message_processor.rs
Labels: enhancement, auto merge, ready to review, waiting-review, AI review first

#2003 [ISSUE #2002]🍻Add DataConverter for rust 🚀
  rocketmq-common/src/utils.rs
  rocketmq-common/src/utils/data_converter.rs
Labels: feature, auto merge, ready to review, waiting-review, AI review first, Difficulty level/Easy, rocketmq-common crate

#2006 [ISSUE #2005]🍻Add PopCheckPointWrapper for PopBufferMergeService 🚀
  rocketmq-broker/src/processor/processor_service/pop_buffer_merge_service.rs
Labels: feature, rust, auto merge, ready to review, waiting-review, AI review first, rocketmq-broker crate

#2008 [ISSUE #2007]🍻Add QueueWithTime for PopBufferMergeService 🚀
  rocketmq-broker/src/processor/processor_service/pop_buffer_merge_service.rs
Labels: feature, auto merge, ready to review, waiting-review, AI review first, rocketmq-broker crate

#2010 [ISSUE #2009]🔨Add Auto Approve Pull Requests workflow
  .github/workflows/auto_approve_pull_requests.yml
Labels: feature, auto merge, ready to review, waiting-review, AI review first

#2012 [ISSUE #2011]🐛Fix Add Auto Approve Pull Requests workflow token error
  .github/workflows/auto_approve_pull_requests.yml
Labels: bug, auto merge, ready to review, waiting-review, AI review first

#2014 [ISSUE #2013]🔨Optimize Auto Approve Pull Requests workflow
  .github/workflows/auto_approve_pull_requests.yml
Labels: enhancement, auto merge, ready to review, waiting-review, AI review first

#2017 [ISSUE #2016]🔨Optimize Auto Approve Pull Requests
  .github/workflows/auto_approve_pull_requests.yml
Labels: enhancement, auto merge, ready to review, waiting-review, AI review first

#2019 [ISSUE #2018]🔨Optimize Auto Approve Pull Requests
  .github/workflows/auto_approve_pull_requests.yml
Labels: auto merge, ready to review, waiting-review, AI review first

#2021 [ISSUE #2020]🔨Optimize Auto Approve Pull Requests
  .github/workflows/auto_approve_pull_requests.yml
Labels: enhancement, auto merge, ready to review, waiting-review, AI review first

#2015 [ISSUE #1685] Add Channel's method #[inline]
  rocketmq-remoting/src/net/channel.rs
Labels: enhancement, approved, auto merge, ready to review, waiting-review, AI review first, Difficulty level/Easy

#2022 [ISSUE #2004]🍻Implement PopBufferMergeService-1 🚀
  rocketmq-broker/src/broker_runtime.rs
  rocketmq-broker/src/processor/ack_message_processor.rs
  rocketmq-broker/src/processor/change_invisible_time_processor.rs
  rocketmq-broker/src/processor/pop_message_processor.rs
  rocketmq-broker/src/processor/processor_service/pop_buffer_merge_service.rs
Labels: feature, auto merge, ready to review, waiting-review, AI review first, rocketmq-broker crate

#2027 [ISSUE #2026]♿️AckMessage extends std::fmt::Display
  rocketmq-store/src/pop.rs
Labels: enhancement, auto merge, ready to review, waiting-review, AI review first

#2028 [ISSUE #2025]⚗️Implement PopBufferMergeService#add_ack🚀
  rocketmq-broker/src/processor/pop_message_processor.rs
  rocketmq-broker/src/processor/processor_service/pop_buffer_merge_service.rs
  rocketmq-common/src/common/broker/broker_config.rs
Labels: feature, auto merge, ready to review, waiting-review, AI review first, Difficulty level/Easy, rocketmq-broker crate

#2030 [ISSUE #2029]💫Implement PopBufferMergeService#get_latest_offset
  rocketmq-broker/src/processor/processor_service/pop_buffer_merge_service.rs
Labels: feature, auto merge, ready to review, waiting-review, AI review first, rocketmq-broker crate

#2032 [ISSUE #2031]🚀Implement PopBufferMergeService#clear_offset_queue💫
  rocketmq-broker/src/processor/pop_message_processor.rs
  rocketmq-broker/src/processor/processor_service/pop_buffer_merge_service.rs
Labels: feature, auto merge, ready to review, waiting-review, AI review first, rocketmq-broker crate

#2034 [ISSUE #2033]💫Move BrokerRole from store to common crate
  rocketmq-common/src/common/broker.rs
  rocketmq-common/src/common/broker/broker_role.rs
Labels: enhancement, auto merge, ready to review, waiting-review, AI review first

#2039 [ISSUE #2037]Adding #[inline] for BatchConsumeQueue methods.
  rocketmq-store/src/queue/batch_consume_queue.rs
Labels: enhancement, auto merge, ready to review, waiting-review, AI review first

#2040 [ISSUE #2038]💫Implement PopBufferMergeService#start
  rocketmq-broker/src/processor/processor_service/pop_buffer_merge_service.rs
  rocketmq-common/src/common/broker/broker_config.rs
Labels: feature, auto merge, ready to review, waiting-review, AI review first

#2042 [ISSUE #2041]💫 Remove BrokerRole from rocketmq-store crate🚀
  rocketmq-broker/src/processor/default_pull_message_result_handler.rs
  rocketmq-broker/src/processor/end_transaction_processor.rs
  rocketmq-broker/src/util/hook_utils.rs
  rocketmq-store/src/config.rs
  rocketmq-store/src/config/broker_role.rs
  rocketmq-store/src/config/message_store_config.rs
  rocketmq-store/src/log_file/commit_log.rs
  rocketmq-store/src/message_store/default_message_store.rs
  rocketmq-store/src/queue/single_consume_queue.rs
Labels: enhancement, auto merge, ready to review, waiting-review, AI review first

#2044 [ISSUE #2035] Add Apache License for broker.rs and compression.rs
  rocketmq-common/src/common/broker.rs
  rocketmq-common/src/common/compression.rs
Labels: enhancement, auto merge, ready to review, waiting-review, AI review first, Difficulty level/Easy, rocketmq-common crate

#2045 [ISSUE #2043]💫Implement PopBufferMergeService#scan🚀
  rocketmq-broker/src/processor/processor_service/pop_buffer_merge_service.rs
  rocketmq-common/src/common/broker/broker_config.rs
Labels: feature, auto merge, ready to review, waiting-review, AI review first, rocketmq-broker crate

#2048 [ISSUE #2047]🧐Implement PopMessageProcessor#buildCkMsg🚀
  rocketmq-broker/src/broker_runtime.rs
  rocketmq-broker/src/processor/pop_message_processor.rs
Labels: feature, auto merge, ready to review, waiting-review, AI review first

#2049 [ISSUE #2046]💫Implement PopBufferMergeService#putCkToStore🧑‍💻
  rocketmq-broker/src/broker_runtime.rs
  rocketmq-broker/src/processor/pop_message_processor.rs
  rocketmq-broker/src/processor/processor_service/pop_buffer_merge_service.rs
Labels: feature, auto merge, ready to review, waiting-review, AI review first

#2051 [ISSUE #2050]💫Implement PopBufferMergeService#is_ck_done_for_finish
  rocketmq-broker/src/processor/processor_service/pop_buffer_merge_service.rs
Labels: feature, auto merge, ready to review, waiting-review, AI review first

#2053 [ISSUE #2052]💫Implement PopBufferMergeService#putAckToStore🚀
  rocketmq-broker/src/processor/processor_service/pop_buffer_merge_service.rs
Labels: feature, auto merge, ready to review, waiting-review, AI review first

#2055 [ISSUE #2054]💫Optimize auto approve pull requests github action
  .github/workflows/auto_approve_pull_requests.yml
Labels: enhancement, auto merge, ready to review, waiting-review, AI review first

#2057 [ISSUE #2056]💫Implement PopBufferMergeService#putBatchAckToStore for rust
  rocketmq-broker/src/processor/processor_service/pop_buffer_merge_service.rs
Labels: feature, rust, auto merge, ready to review, waiting-review, AI review first, Difficulty level/Easy, rocketmq-broker crate

#2059 [ISSUE #2058]💫Implement PopBufferMergeService scan_garbage and get_offset_total_size📸
  rocketmq-broker/src/processor/pop_message_processor.rs
  rocketmq-broker/src/processor/processor_service/pop_buffer_merge_service.rs
Labels: feature, auto merge, ready to review, waiting-review, AI review first, rocketmq-broker crate

#2061 [ISSUE #2060]Adding #[inline] for ConsumeQueueStore methods
  rocketmq-store/src/queue/local_file_consume_queue_store.rs
Labels: enhancement, approved, auto merge, ready to review, waiting-review, AI review first

#2063 [ISSUE #2062] Adding #[inline] for QueueOffsetOperator methods
  rocketmq-store/src/queue/queue_offset_operator.rs
Labels: enhancement, approved, auto merge, ready to review, waiting-review, AI review first

#2067 [ISSUE #2064]Adding #[inline] for ConsumeQueue methods
  rocketmq-store/src/queue/single_consume_queue.rs
Labels: enhancement, approved, auto merge, ready to review, waiting-review, AI review first

#2070 [ISSUE #2069]💫Optimize auto approve pull requests github action
  .github/workflows/auto_approve_pull_requests.yml
Labels: enhancement, approved, auto merge, ready to review, waiting-review, AI review first

#2072 [ISSUE #2065]💫Implement PopReviveService-1🚀
  rocketmq-broker/src/processor/processor_service/pop_revive_service.rs
Labels: feature, auto merge, ready to review, waiting-review, AI review first, Difficulty level/Moderate, rocketmq-broker crate

#2074 [ISSUE #2073]💫Implement PopReviveService#reviveRetry🚀
  rocketmq-broker/src/processor/processor_service/pop_revive_service.rs
Labels: feature, auto merge, ready to review, waiting-review, AI review first

#2077 [ISSUE #2076]💫Implement PopReviveService#getMessage🚀
  rocketmq-broker/src/processor/processor_service/pop_revive_service.rs
Labels: feature, auto merge, ready to review, waiting-review, AI review first

#2078 [ISSUE #2075]💫Implement PopReviveService#getReviveMessage🚀
  rocketmq-broker/src/processor/processor_service/pop_revive_service.rs
Labels: feature, auto merge, ready to review, waiting-review, AI review first

#2080 [ISSUE #2079]💫Add HAConnectionRuntimeInfo for rust🚀
  rocketmq-remoting/src/protocol/body.rs
  rocketmq-remoting/src/protocol/body/ha_connection_runtime_info.rs
Labels: feature, auto merge, ready to review, waiting-review, AI review first

#2082 [ISSUE #2081]💫Add HAClientRuntimeInfo for rust🚀
  rocketmq-remoting/src/protocol/body.rs
  rocketmq-remoting/src/protocol/body/ha_client_runtime_info.rs
Labels: feature, auto merge, ready to review, waiting-review, AI review first

#2084 [ISSUE #1382]💫Add HAClientRuntimeInfo for rust🚀
  rocketmq-remoting/src/protocol/body.rs
  rocketmq-remoting/src/protocol/body/ha_runtime_info.rs
Labels: feature, auto merge, ready to review, waiting-review, AI review first

#2086 [ISSUE #2085]💫Implement PopReviveService#start🚀
  rocketmq-broker/src/processor/processor_service/pop_revive_service.rs
  rocketmq-common/src/common/broker/broker_config.rs
  rocketmq-store/src/log_file.rs
  rocketmq-store/src/message_store/default_message_store.rs
Labels: feature, auto merge, ready to review, waiting-review, AI review first

#2088 [ISSUE #2087]🐛Fix ReferenceResource#hold not correct
  rocketmq-store/src/log_file/mapped_file/default_mapped_file_impl.rs
Labels: bug, auto merge, ready to review, waiting-review, AI review first

#2089 [ISSUE #2071]💫Implement PopReviveService-2⚗️
  rocketmq-broker/src/processor/processor_service/pop_revive_service.rs
  rocketmq-common/src/common/broker/broker_config.rs
  rocketmq-store/src/timer/timer_message_store.rs
Labels: feature, auto merge, ready to review, waiting-review, AI review first

#2092 [ISSUE #2091] Adding #[inline] for BrokerStatsManager methods
  rocketmq-store/src/stats/broker_stats_manager.rs
Labels: enhancement, auto merge, ready to review, waiting-review, AI review first

#2093 [ISSUE #2090]💫Implement PopReviveService#mergeAndRevive⚗️
  rocketmq-broker/src/processor/processor_service/pop_revive_service.rs
Labels: feature, auto merge, ready to review, waiting-review, AI review first

#2095 [ISSUE #2094]💫Implement PopReviveService#rePutCK⚗️
  rocketmq-broker/src/processor/processor_service/pop_revive_service.rs
  rocketmq-common/src/common/broker/broker_config.rs
  rocketmq-store/src/pop/pop_check_point.rs
Labels: feature, auto merge, ready to review, waiting-review, AI review first

#2098 [ISSUE #2097]💫Implement EscapeBridge#getMessageAsync⚗️
  Cargo.lock
  rocketmq-broker/Cargo.toml
  rocketmq-broker/src/failover/escape_bridge.rs
  rocketmq-broker/src/out_api/broker_outer_api.rs
Labels: feature, auto merge, ready to review, waiting-review, AI review first, rocketmq-broker crate

#2100 [ISSUE #2099]💫Refactor ReferenceResource⚗️
  rocketmq-store/src/log_file/mapped_file.rs
  rocketmq-store/src/log_file/mapped_file/reference_resource.rs
  rocketmq-store/src/log_file/mapped_file/reference_resource_impl.rs
Labels: feature, auto merge, ready to review, waiting-review, AI review first, rocketmq-store crate

#2102 [ISSUE #2101]♻️Refactor DefaultMappedFile💫
  rocketmq-store/src/log_file/mapped_file.rs
  rocketmq-store/src/log_file/mapped_file/default_mapped_file_impl.rs
Labels: refactor, auto merge, ready to review, waiting-review, AI review first

#2104 [ISSUE #2103]💫Add BrokerInner for BrokerRuntime🚀
  rocketmq-broker/src/broker_runtime.rs
  rocketmq-store/src/stats/broker_stats.rs
Labels: feature, auto merge, ready to review, waiting-review, AI review first, rocketmq-broker crate

#2106 [ISSUE #2105]💫Add NameServerRuntimeInner for NameServerRuntime 🚀
  rocketmq-namesrv/src/bootstrap.rs
Labels: feature, auto merge, ready to review, waiting-review, AI review first, rocketmq-namesrv crate

#2110 [ISSUE #2109]💫Refactor name server crate with NameServerRuntimeInner♻️
  rocketmq-namesrv/src/bootstrap.rs
  rocketmq-namesrv/src/kvconfig/kvconfig_mananger.rs
  rocketmq-namesrv/src/processor/client_request_processor.rs
  rocketmq-namesrv/src/processor/default_request_processor.rs
  rocketmq-namesrv/src/route/route_info_manager.rs
  rocketmq-remoting/src/runtime/config/client_config.rs
Labels: refactor, auto merge, ready to review, waiting-review, AI review first, rocketmq-namesrv crate

#2112 [ISSUE #2111]🏗️BrokerInner add mut methods⚡️
  rocketmq-broker/src/broker_runtime.rs
Labels: enhancement, auto merge, ready to review, waiting-review, AI review first, rocketmq-broker crate

#2114 [ISSUE #2113]💫Implement BrokerOuterAPI#pullMessageFromSpecificBrokerAsync🥅
  rocketmq-broker/src/out_api/broker_outer_api.rs
  rocketmq-client/src/lib.rs
Labels: feature, rust, auto merge, ready to review, waiting-review, AI review first, rocketmq-broker crate

#2118 [Issue 2117] Fix unused warnings in RocketMQ examples
  rocketmq-client/examples/transaction/transaction_producer.rs
  rocketmq-common/src/common/message/message_client_id_setter.rs
Labels: documentation, auto merge, ready to review, waiting-review, AI review first

#2120 [ISSUE #2119]💫Add ConsumeQueueData for rust
  rocketmq-remoting/src/protocol/body.rs
  rocketmq-remoting/src/protocol/body/consume_queue_data.rs
Labels: feature, auto merge, ready to review, waiting-review, AI review first

#2121 [ISSUE #1380]💫Add QueryConsumeQueueResponseBody
  rocketmq-remoting/src/protocol/body.rs
  rocketmq-remoting/src/protocol/body/query_consume_queue_response_body.rs
Labels: feature, auto merge, ready to review, waiting-review, AI review first

#2116 [ISSUE #2115]Allow unused imports in ordermessage_consumer file
  rocketmq-client/examples/ordermessage/ordermessage_consumer.rs
Labels: bug, approved, auto merge, ready to review, waiting-review, AI review first

#2127 [ISSUE #2126]💫Optimize RegisterBrokerBody filter_server_list Vec<String> with Vec<CheetahString>🍻
  rocketmq-broker/src/out_api/broker_outer_api.rs
  rocketmq-namesrv/src/processor/default_request_processor.rs
  rocketmq-namesrv/src/route/route_info_manager.rs
  rocketmq-remoting/src/protocol/body/broker_body/register_broker_body.rs
Labels: enhancement, auto merge, ready to review, waiting-review, AI review first, Difficulty level/Easy, rocketmq-namesrv crate

#2131 [ISSUE #2130]📝Add doc for RouteInfoManager🍻
  rocketmq-namesrv/src/route/route_info_manager.rs
Labels: documentation📝, auto merge, ready to review, waiting-review, AI review first

#2133 [ISSUE #1512]♻️Refactor PutKVConfigRequestHeader with derive marco RequestHeaderCodec
  rocketmq-remoting/src/protocol/header/namesrv/kv_config_header.rs
Labels: enhancement, refactor, auto merge, ready to review, waiting-review, AI review first, Difficulty level/Easy

#2136 [ISSUE #2134]🐛Fix get_kv_config return code not correct
  rocketmq-namesrv/src/processor/default_request_processor.rs
Labels: bug🐛, auto merge, ready to review, waiting-review, AI review first

#2137 [ISSUE #2135]📝Update Issues template
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/doc.yml
  .github/ISSUE_TEMPLATE/enhancement_request.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/ISSUE_TEMPLATE/refactor.yml
  .github/ISSUE_TEMPLATE/unit_test.yml
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first

#2139 [ISSUE #1514]♻️Refactor GetKVConfigResponseHeader with derive marco R…
  rocketmq-remoting/src/protocol/header/namesrv/kv_config_header.rs
Labels: enhancement⚡️, refactor♻️, auto merge, ready to review, waiting-review, AI review first, Difficulty level/Easy

#2140 [ISSUE #1515]♻️Refactor DeleteKVConfigRequestHeader with derive marco RequestHeaderCodec
  rocketmq-remoting/src/protocol/header/namesrv/kv_config_header.rs
Labels: enhancement⚡️, refactor♻️, auto merge, ready to review, waiting-review, AI review first, Difficulty level/Easy

#2142 [ISSUE #2141]♻️Refactor QueryDataVersionRequestHeader with derive marco RequestHeaderCodec
  rocketmq-remoting/src/protocol/header/namesrv/query_data_version_header.rs
Labels: refactor♻️, auto merge, ready to review, waiting-review, AI review first

#2144 [ISSUE #2143]♻️Refactor QueryDataVersionResponseHeader with derive marco RequestHeaderCodec
  rocketmq-remoting/src/protocol/header/namesrv/query_data_version_header.rs
Labels: refactor♻️, auto merge, ready to review, waiting-review, AI review first

#2146 [ISSUE #2145]💫Optimize DefaultRequestProcessor check_sum_crc32 method
  rocketmq-namesrv/src/processor/default_request_processor.rs
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first, rocketmq-namesrv crate

#2148 [ISSUE #2147]💫Optimize DefaultRequestProcessor extract_register_topic_config_from_request
  rocketmq-namesrv/src/processor/default_request_processor.rs
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first, rocketmq-namesrv crate

#2150 [ISSUE #2149]♻️Refactor RegisterBrokerRequestHeader with derive marco RequestHeaderCodec
  rocketmq-remoting/src/protocol/header/namesrv/register_broker_header.rs
Labels: auto merge, ready to review, waiting-review, AI review first

#2152 [ISSUE #2151]♻️Refactor RegisterBrokerResponseHeader with derive marco RequestHeaderCodec
  rocketmq-remoting/src/protocol/header/namesrv/register_broker_header.rs
Labels: refactor♻️, auto merge, ready to review, waiting-review, AI review first, rocketmq-namesrv crate

#2154 [ISSUE #2153]⚡️Reduce memory copy in process_register_broker method🔥
  rocketmq-namesrv/src/processor/default_request_processor.rs
  rocketmq-remoting/src/protocol/body/query_consume_queue_response_body.rs
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first, rocketmq-namesrv crate

#2156 [ISSUE #2155]♻️Refactor WipeWritePermOfBrokerRequestHeader with derive marco RequestHeaderCodec
  rocketmq-remoting/src/protocol/header/namesrv/perm_broker_header.rs
Labels: refactor♻️, auto merge, ready to review, waiting-review, AI review first

#2158 [ISSUE #2157]🔨Update auto approve pull requests wait time
  .github/workflows/auto_approve_pull_requests.yml
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first

#2162 [ISSUE #2161]🚀Implement BatchUnregistrationService💫
  rocketmq-namesrv/src/route.rs
  rocketmq-namesrv/src/route/batch_unregistration_service.rs
Labels: feature🚀, auto merge, ready to review, waiting-review, AI review first, rocketmq-namesrv crate

#2164 [ISSUE #2163]⚡️Nameserver supports batch broker unregistration
  rocketmq-namesrv/src/processor/default_request_processor.rs
  rocketmq-namesrv/src/route/route_info_manager.rs
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first, rocketmq-namesrv crate

#2165 [ISSUE #1516]♻️Refactor GetKVListByNamespaceRequestHeader with derive marco RequestHeaderCodec
  rocketmq-remoting/src/protocol/header/namesrv/kv_config_header.rs
Labels: enhancement⚡️, refactor♻️, auto merge, ready to review, waiting-review, AI review first, Difficulty level/Easy

#2167 [ISSUE #2166]♻️Refactor DeleteTopicFromNamesrvRequestHeader and RegisterTopicRequestHeader with derive marco RequestHeaderCodec
  rocketmq-remoting/src/protocol/header/namesrv/topic_operation_header.rs
Labels: refactor♻️, auto merge, ready to review, waiting-review, AI review first

#2169 [ISSUE #2168]♻️Refactor GetTopicsByClusterRequestHeader and TopicRequestHeader with derive marco RequestHeaderCodec
  rocketmq-remoting/src/protocol/header/namesrv/topic_operation_header.rs
Labels: refactor♻️, auto merge, ready to review, waiting-review, AI review first

#2171 [ISSUE #2170]🐛Fix BatchUnregistrationService not started when Name server start
  rocketmq-namesrv/src/route/batch_unregistration_service.rs
  rocketmq-namesrv/src/route/route_info_manager.rs
Labels: bug🐛, auto merge, ready to review, waiting-review, AI review first

#2173 [ISSUE #2172]🤡Implement name server graceful shutdown⚡️
  rocketmq-namesrv/src/bootstrap.rs
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first, rocketmq-namesrv crate

#2176 [ISSUE #2174]♻️Refactor remoting graceful shutdown
  rocketmq-remoting/src/remoting_server/server.rs
Labels: refactor♻️, auto merge, ready to review, waiting-review, AI review first, rocketmq-remoting crate

#2178 [ISSUE #2177]⚡️Optimize name server graceful shutdown
  rocketmq-namesrv/src/bootstrap.rs
  rocketmq-namesrv/src/route/batch_unregistration_service.rs
  rocketmq-namesrv/src/route/route_info_manager.rs
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first

#2180 [ISSUE #2179]💫Optimize RouteInfoManager#un_register_broker method🍻
  rocketmq-namesrv/src/route/route_info_manager.rs
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first, rocketmq-namesrv crate

#2182 [ISSUE #2181]💫Optimize RouteInfoManager#clean_topic_by_un_register_requests🍻
  rocketmq-namesrv/src/route/route_info_manager.rs
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first, rocketmq-namesrv crate

#2185 [ISSUE #2184]⚡️Optimize RouteInfoManager#choose_broker_addrs_to_notify
  rocketmq-namesrv/src/route/route_info_manager.rs
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first, rocketmq-namesrv crate

#2187 [ISSUE #2186]♻️Refactor MQClientManager💫
  rocketmq-client/src/consumer/consumer_impl/default_mq_push_consumer_impl.rs
  rocketmq-client/src/implementation/mq_client_manager.rs
  rocketmq-client/src/producer/producer_impl/default_mq_producer_impl.rs
Labels: refactor♻️, auto merge, ready to review, waiting-review, AI review first, rocketmq-client crate

#2189 [ISSUE #2188]💫Remove SyncUnsafeCellWrapper from mmapped_file🍻
  rocketmq-store/src/log_file/mapped_file/default_mapped_file_impl.rs
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first, rocketmq-store crate

#2191 [ISSUE #2190]💫Add MappedFileRefactor trait🍻
  rocketmq-store/src/log_file/mapped_file.rs
Labels: refactor♻️, auto merge, ready to review, waiting-review, AI review first, rocketmq-store crate

#2198 [ISSUE #2197]💫Replace MappedFile#is_full Ordering::Relaxed with Ordering::Acquire🍻
  rocketmq-store/src/log_file/mapped_file.rs
  rocketmq-store/src/log_file/mapped_file/default_mapped_file_impl.rs
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first

#2200 [ISSUE #2199]💫Implement MappedFile append_message_bytes and append_message_with_offset🍻
  rocketmq-store/src/log_file/mapped_file.rs
  rocketmq-store/src/log_file/mapped_file/default_mapped_file_impl.rs
Labels: feature🚀, auto merge, ready to review, waiting-review, AI review first

#2202 [ISSUE #2201]💫Optimize DefaultMappedFile#flush🍻
  rocketmq-store/src/log_file/mapped_file.rs
  rocketmq-store/src/log_file/mapped_file/default_mapped_file_impl.rs
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first

#2206 [ISSUE #2205]🐛Fix stats_item.rs cargo clippy -- -D warnings error🍻
  rocketmq-common/src/common/stats/stats_item.rs
Labels: bug🐛, auto merge, ready to review, waiting-review, AI review first

#2204 [ISSUE #2203]💫Implement select_mapped_buffer and select_mapped_buffer_with_position method🍻
  rocketmq-store/src/log_file/commit_log.rs
  rocketmq-store/src/log_file/mapped_file.rs
  rocketmq-store/src/log_file/mapped_file/default_mapped_file_impl.rs
  rocketmq-store/src/queue/single_consume_queue.rs
Labels: feature🚀, auto merge, ready to review, waiting-review, AI review first

#2208 [ISSUE #2207]🚸Add Default trait for SelectMappedBufferResult🍻
  rocketmq-store/src/base/select_result.rs
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first

#2210 [ISSUE #2209]🚸Implement DefaultMappedFile#get_mapped_byte_buffer🍻
  rocketmq-store/src/log_file/mapped_file.rs
  rocketmq-store/src/log_file/mapped_file/default_mapped_file_impl.rs
Labels: feature🚀, auto merge, ready to review, waiting-review, AI review first

#2212 [ISSUE #2211]🚨Implement DefaultMappedFile get_last_modified_timestamp and slice_byte_buffer🍻
  rocketmq-store/src/consume_queue/mapped_file_queue.rs
  rocketmq-store/src/log_file/mapped_file.rs
  rocketmq-store/src/log_file/mapped_file/default_mapped_file_impl.rs
Labels: feature🚀, auto merge, ready to review, waiting-review, AI review first

#2214 [ISSUE #2213]🚨Refactor DefaultMappedFile#get_data🍻
  rocketmq-store/src/log_file/mapped_file.rs
  rocketmq-store/src/log_file/mapped_file/default_mapped_file_impl.rs
Labels: refactor♻️, auto merge, ready to review, waiting-review, AI review first

#2216 [ISSUE #2215]🚨Implement DefaultMappedFile#destroy🍻
  rocketmq-store/src/index/index_file.rs
  rocketmq-store/src/log_file/mapped_file.rs
  rocketmq-store/src/log_file/mapped_file/default_mapped_file_impl.rs
Labels: feature🚀, auto merge, ready to review, waiting-review, AI review first

#2218 [ISSUE #2217]💫Refactor Broker crate with BrokerRuntimeInner♻️
  rocketmq-broker/src/broker_runtime.rs
  rocketmq-broker/src/failover/escape_bridge.rs
  rocketmq-broker/src/filter/manager/consumer_filter_manager.rs
  rocketmq-broker/src/long_polling/long_polling_service/pull_request_hold_service.rs
  rocketmq-broker/src/long_polling/notify_message_arriving_listener.rs
  rocketmq-broker/src/offset/manager/consumer_order_info_manager.rs
  rocketmq-broker/src/out_api.rs
  rocketmq-broker/src/out_api/broker_outer_api.rs
  rocketmq-broker/src/processor.rs
  rocketmq-broker/src/processor/ack_message_processor.rs
  rocketmq-broker/src/processor/admin_broker_processor.rs
  rocketmq-broker/src/processor/admin_broker_processor/batch_mq_handler.rs
  rocketmq-broker/src/processor/admin_broker_processor/broker_config_request_handler.rs
  rocketmq-broker/src/processor/admin_broker_processor/consumer_request_handler.rs
  rocketmq-broker/src/processor/admin_broker_processor/offset_request_handler.rs
  rocketmq-broker/src/processor/admin_broker_processor/topic_request_handler.rs
  rocketmq-broker/src/processor/change_invisible_time_processor.rs
  rocketmq-broker/src/processor/client_manage_processor.rs
  rocketmq-broker/src/processor/consumer_manage_processor.rs
  rocketmq-broker/src/processor/default_pull_message_result_handler.rs
  rocketmq-broker/src/processor/end_transaction_processor.rs
  rocketmq-broker/src/processor/pop_message_processor.rs
  rocketmq-broker/src/processor/processor_service/pop_buffer_merge_service.rs
  rocketmq-broker/src/processor/processor_service/pop_revive_service.rs
  rocketmq-broker/src/processor/pull_message_processor.rs
  rocketmq-broker/src/processor/query_assignment_processor.rs
  rocketmq-broker/src/processor/query_message_processor.rs
  rocketmq-broker/src/processor/reply_message_processor.rs
  rocketmq-broker/src/processor/send_message_processor.rs
  rocketmq-broker/src/subscription/manager/subscription_group_manager.rs
  rocketmq-broker/src/topic/manager/topic_config_manager.rs
  rocketmq-broker/src/topic/manager/topic_route_info_manager.rs
  rocketmq-broker/src/transaction/queue/default_transactional_message_check_listener.rs
  rocketmq-broker/src/transaction/queue/default_transactional_message_service.rs
  rocketmq-broker/src/transaction/queue/transactional_message_bridge.rs
  rocketmq-common/src/common/statistics/state_getter.rs
  rocketmq-store/src/log_file/mapped_file/default_mapped_file_impl.rs
Labels: refactor♻️, rust, auto merge, ready to review, waiting-review, AI review first, rocketmq-broker crate

#2219 [ISSUE #2129]💫Remove KVConfigManager #[derive(Clone)]🧑‍💻
  rocketmq-namesrv/src/kvconfig/kvconfig_mananger.rs
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first, rocketmq-broker crate

#2220 [ISSUE #2128]💫Remove RouteInfoManager #[derive(Clone)]🧑‍💻
  rocketmq-namesrv/src/route/route_info_manager.rs
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first, rocketmq-namesrv crate

#2222 [ISSUE #2221]💫Optimize BrokerRuntimeInner#register_increment_broker_data🧑‍💻
  rocketmq-broker/src/broker_runtime.rs
  rocketmq-broker/src/processor/admin_broker_processor/topic_request_handler.rs
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first

#2224 [ISSUE #2223]💫Remove BrokerRuntime unused code and enhancement code🧑‍💻
  rocketmq-broker/src/broker_runtime.rs
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first

#2226 [ISSUE #2225]📌Remove BrokerRuntime #[derive(Clone)] ⚡️
  rocketmq-broker/src/broker_runtime.rs
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first, rocketmq-broker crate

#2228 [ISSUE #2227]💫Implement broker graceful shutdown🧑‍💻
  rocketmq-broker/src/broker_bootstrap.rs
  rocketmq-broker/src/broker_runtime.rs
Labels: feature🚀, auto merge, ready to review, waiting-review, AI review first, rocketmq-broker crate

#2231 [ISSUE #2230]💫Implement BrokerOuterAPI#unregisterBrokerAll🧑‍💻
  rocketmq-broker/src/out_api/broker_outer_api.rs
Labels: feature🚀, auto merge, ready to review, waiting-review, AI review first, rocketmq-broker crate

#2233 [ISSUE #2232]🐛Fix Boker shutdown maybe register again
  rocketmq-broker/src/broker_runtime.rs
Labels: bug🐛, auto merge, ready to review, waiting-review, AI review first

#2235 [ISSUE #2234]⚡️Optimize BrokerRuntimeInner register_broker_all method paramters🦺
  rocketmq-broker/src/broker_runtime.rs
  rocketmq-common/src/common/broker/broker_config.rs
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first

#2237 [ISSUE #2236]💫BrokerRuntime implement unregister broker🚀
  rocketmq-broker/src/broker_runtime.rs
Labels: feature🚀, auto merge, ready to review, waiting-review, AI review first, rocketmq-broker crate

#2239 [ISSUE #2238]💫Change the default value of total_replicas from 0 to 1 in the message_store_config🧑‍💻
  rocketmq-store/src/config/message_store_config.rs
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first, rocketmq-broker crate

#2248 [ISSUE #2247]🚀 TopicQueueMappingCleanService and BroadcastOffsetManager add shutdown method
  rocketmq-broker/src/offset/manager/broadcast_offset_manager.rs
  rocketmq-broker/src/topic/topic_queue_mapping_clean_service.rs
Labels: feature🚀, auto merge, ready to review, waiting-review, AI review first

#2246 [ISSUE #2245]🚀TimerMessageStore add shutdown method
  rocketmq-store/src/timer/timer_message_store.rs
Labels: feature🚀, auto merge, ready to review, waiting-review, AI review first

#2244 [ISSUE #2243]🚀ReplicasManager add shutdown method
  rocketmq-broker/src/controller/replicas_manager.rs
Labels: feature🚀, auto merge, ready to review, waiting-review, AI review first

#2252 [ISSUE #2251]🚀NotificationProcessor and PopMessageProcessor add shutdown method
  rocketmq-broker/src/processor/notification_processor.rs
  rocketmq-broker/src/processor/pop_message_processor.rs
Labels: feature🚀, auto merge, ready to review, waiting-review, AI review first

#2250 [ISSUE #2249]🚀AckMessageProcessor and BrokerStatsManager add shutdown method
  rocketmq-broker/src/processor/ack_message_processor.rs
  rocketmq-store/src/stats/broker_stats_manager.rs
Labels: feature🚀, auto merge, ready to review, waiting-review, AI review first

#2254 [ISSUE #2253]⚡️Change ConsumerManager signature of new method
  rocketmq-broker/src/broker_runtime.rs
  rocketmq-broker/src/client/manager/consumer_manager.rs
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first

#2256 [ISSUE #2255]🚀Add BrokerFastFailure struct for rust
  rocketmq-broker/src/latency.rs
  rocketmq-broker/src/latency/broker_fast_failure.rs
  rocketmq-broker/src/lib.rs
Labels: feature🚀, auto merge, ready to review, waiting-review, AI review first

#2260 [ISSUE #2259] 🚀TransactionMetricsFlushService and TransactionalMessageCheckService add shutdown method
  rocketmq-broker/src/transaction/transaction_metrics_flush_service.rs
  rocketmq-broker/src/transaction/transactional_message_check_service.rs
Labels: feature🚀, auto merge, ready to review, waiting-review, AI review first

#2262 [ISSUE #2261]🚀ColdDataCgCtrService and ColdDataPullRequestHoldService add shutdown method
  rocketmq-broker/src/coldctr/cold_data_cg_ctr_service.rs
  rocketmq-broker/src/coldctr/cold_data_pull_request_hold_service.rs
Labels: feature🚀, auto merge, ready to review, waiting-review, AI review first

#2264 [ISSUE #2263]🚀DefaultTransactionalMessageService and EscapeBridge add shutdown method
  rocketmq-broker/src/failover/escape_bridge.rs
  rocketmq-broker/src/transaction/queue/default_transactional_message_service.rs
Labels: feature🚀, auto merge, ready to review, waiting-review, AI review first

#2266 [ISSUE #2265]🚀ScheduleMessageService and TopicRouteInfoManager add shutdown method
  rocketmq-broker/src/schedule/schedule_message_service.rs
  rocketmq-broker/src/topic/manager/topic_route_info_manager.rs
Labels: feature🚀, auto merge, ready to review, waiting-review, AI review first

#2267 [ISSUE #2242]🚀Optimize BrokerRuntime shutdown💥
  rocketmq-broker/src/broker_runtime.rs
  rocketmq-broker/src/client/default_consumer_ids_change_listener.rs
  rocketmq-broker/src/schedule/schedule_message_service.rs
Labels: feature🚀, auto merge, ready to review, waiting-review, AI review first, rocketmq-broker crate

#2272 [ISSUE #2268]💫Optimize BrokerRuntime start method🧑‍💻
  rocketmq-broker/src/broker_runtime.rs
  rocketmq-common/src/common/broker/broker_config.rs
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first, rocketmq-broker crate

#2269 [ISSUE #1851]Adding #[inline] for QueryResult methods
  rocketmq-client/src/base/query_result.rs
Labels: enhancement⚡️, rust, auto merge, ready to review, waiting-review, AI review first, Difficulty level/Easy, rocketmq-client crate

#2271 [ISSUE #2270]Adding #[inline] for ClientConfig methods.
  rocketmq-client/src/base/client_config.rs
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first

#2274 [ISSUE #2273]🏗️Optimize BrokerRuntime message_store start make it stronger
  rocketmq-broker/src/broker_runtime.rs
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first

#2276 [ISSUE #2275]🔥Remove rocketmq-store log crate
  Cargo.lock
  rocketmq-store/Cargo.toml
  rocketmq-store/src/consume_queue/mapped_file_queue.rs
  rocketmq-store/src/index/index_file.rs
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first, rocketmq-store crate

#2282 [ISSUE #2281]🚀BrokerStatsManager and ColdDataCgCtrService add start method
  rocketmq-broker/src/coldctr/cold_data_cg_ctr_service.rs
  rocketmq-store/src/stats/broker_stats_manager.rs
Labels: feature🚀, auto merge, ready to review, waiting-review, AI review first

#2280 [ISSUE #2279]🚀BrokerFastFailure and BrokerPreOnlineService add start method
  rocketmq-broker/src/broker/broker_pre_online_service.rs
  rocketmq-broker/src/latency/broker_fast_failure.rs
Labels: feature🚀, auto merge, ready to review, waiting-review, AI review first

#2284 [ISSUE #2281]🚀BrokerStatsManager and ColdDataCgCtrService add start method
  rocketmq-broker/src/coldctr/cold_data_pull_request_hold_service.rs
  rocketmq-broker/src/processor/notification_processor.rs
Labels: feature🚀, auto merge, ready to review, waiting-review, AI review first

#2286 [ISSUE #2285]🚀 PopMessageProcessor,TimerMessageStore and TopicQueueMappingCleanService add start method
  rocketmq-broker/src/processor/pop_message_processor.rs
  rocketmq-broker/src/topic/topic_queue_mapping_clean_service.rs
  rocketmq-store/src/timer/timer_message_store.rs
Labels: feature🚀, auto merge, ready to review, waiting-review, AI review first

#2288 [ISSUE #2287]🚀Implement BrokerRuntime start method💫
  rocketmq-broker/src/broker_runtime.rs
Labels: enhancement⚡️, feature🚀, auto merge, ready to review, waiting-review, AI review first, rocketmq-broker crate

#2290 [ISSUE #2289]🤡Add PopConsumer for example🚀
  Cargo.lock
  Cargo.toml
  rocketmq-example/Cargo.toml
  rocketmq-example/examples/consumer/pop_consumer.rs
  rocketmq-tools/src/admin/default_mq_admin_ext.rs
Labels: feature🚀, auto merge, ready to review, waiting-review, AI review first, rocketmq-example crate

#2292 [ISSUE #2291]🙈Change QueryAssignmentProcessor process_request method return paramter⚡️
  rocketmq-broker/src/processor.rs
  rocketmq-broker/src/processor/query_assignment_processor.rs
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first, rocketmq-broker crate

#2294 [ISSUE #2293]🤡Remove MessageRequestModeManager#set_message_request_mode clone⚡️
  rocketmq-broker/src/load_balance/message_request_mode_manager.rs
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first

#2297 [ISSUE #2296]📝Add comment for RebalancePushImpl#client_rebalance
  rocketmq-client/src/consumer/consumer_impl/re_balance/rebalance_push_impl.rs
Labels: documentation📝, auto merge, ready to review, waiting-review, AI review first

#2299 [ISSUE #2298]⚡️Remove PopMessageProcessor useless code
  rocketmq-broker/src/processor/pop_message_processor.rs
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first

#2301 [ISSUE #2300]🚀Implement PopMessageProcessor start method
  rocketmq-broker/src/long_polling/long_polling_service/pop_long_polling_service.rs
  rocketmq-broker/src/processor/pop_message_processor.rs
Labels: feature🚀, auto merge, ready to review, waiting-review, AI review first

#2303 [ISSUE #2302]⚡️Optimize PopMessageProcessor#process_request
  rocketmq-broker/src/processor/pop_message_processor.rs
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first

#2305 [ISSUE #2304]🏗️Add RemotingCommand encodeHeader method for Zero Copy🚀
  rocketmq-remoting/src/protocol/remoting_command.rs
Labels: feature🚀, auto merge, ready to review, waiting-review, AI review first

#2307 [ISSUE #2306]⚡️Remove useless set_cmd_version from RemotingCommand
  rocketmq-remoting/src/protocol/remoting_command.rs
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first

#2309 [ISSUE #2308]🚀Add some method for SelectMappedBufferResult
  rocketmq-store/src/base/select_result.rs
Labels: feature🚀, auto merge, ready to review, waiting-review, AI review first
