Repository mxsm/rocketmq-rust, pull requests merged in 2025-07, with the labels that each got.

#3549 [ISSUE #3548]🔨Add codeql.yml action
  .github/workflows/codeql.yml
Labels: feature🚀, auto merge, ready to review, waiting-review, AI review first

#3553 Bump tokio from 1.46.0 to 1.46.1
  Cargo.lock
Labels: auto merge, ready to review, waiting-review, AI review first

#3564 [ISSUE #3563]Add missing semicolon in default HA service client initialization
  rocketmq-store/src/ha/default_ha_service.rs
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first

#3570 [ISSUE #3569]Code Cleanup: Remove Commented Dead Code in CommitLog
  rocketmq-store/src/log_file/commit_log.rs
Labels: auto merge, ready to review, waiting-review, AI review first, refactoring, cleanup, code-quality, maintenance

#3573 [ISSUE #3572]⚡️Optimize handle_disk_flush_and_ha error handling and status resolution
  rocketmq-store/src/log_file/commit_log.rs
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first

#3577 [ISSUE #3576]🚀Add new constructor for service task with Arc support✨
  rocketmq/src/task/service_task.rs
Labels: feature🚀, auto merge, ready to review, waiting-review, AI review first

#3581 [ISSUE #3580]⚡️Fix GroupTransferService memory leaks and improve request processing reliability
  rocketmq-store/src/ha/group_transfer_service.rs
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first

#3583 [ISSUE #3582]⚡️Complete GroupTransferService request lifecycle with customer notification and timeout handling
  rocketmq-store/src/ha/group_transfer_service.rs
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first

#3585 [ISSUE #3584]⚡️Implement HA connection management with concrete connection list functionality
  rocketmq-store/src/ha/auto_switch/auto_switch_ha_service.rs
  rocketmq-store/src/ha/default_ha_service.rs
  rocketmq-store/src/ha/general_ha_service.rs
  rocketmq-store/src/ha/group_transfer_service.rs
  rocketmq-store/src/ha/ha_service.rs
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first

#3590 [ISSUE #3589]♻️Simplify HA client initialization and remove unnecessary ArcMut wrappers
  rocketmq-store/src/ha/default_ha_client.rs
  rocketmq-store/src/ha/default_ha_service.rs
  rocketmq-store/src/ha/general_ha_client.rs
  rocketmq-store/src/message_store/local_file_message_store.rs
Labels: refactor♻️, auto merge, ready to review, waiting-review, AI review first

#3592 [ISSUE #3591]♻️Fix typo in flush manager module name: defalut -> default
  rocketmq-store/src/log_file/commit_log.rs
  rocketmq-store/src/log_file/flush_manager_impl.rs
  rocketmq-store/src/log_file/flush_manager_impl/default_flush_manager.rs
Labels: refactor♻️, auto merge, ready to review, waiting-review, AI review first

#3601 [ISSUE #3600]⚡️Improve HAService interface consistency and placeholder implementations
  rocketmq-store/src/ha/auto_switch/auto_switch_ha_service.rs
  rocketmq-store/src/ha/default_ha_service.rs
  rocketmq-store/src/ha/general_ha_service.rs
  rocketmq-store/src/ha/ha_service.rs
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first

#3603 [ISSUE #3602]♻️Improve HA client interface with proper type safety and optionality
  rocketmq-store/src/ha/auto_switch/auto_switch_ha_service.rs
  rocketmq-store/src/ha/default_ha_service.rs
  rocketmq-store/src/ha/general_ha_service.rs
  rocketmq-store/src/ha/ha_service.rs
Labels: refactor♻️, auto merge, ready to review, waiting-review, AI review first

#3605 [ISSUE #3604]⚡️Improve HA connection shutdown mechanism and complete message processing
  rocketmq-store/src/ha/default_ha_connection.rs
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first

#3609 [ISSUE #3608]⚡️Improve HA connection management and state notification
  rocketmq-store/src/ha/default_ha_service.rs
  rocketmq-store/src/ha/ha_connection_state_notification_service.rs
Labels: auto merge, ready to review, waiting-review, AI review first, enhancement

#3611 [ISSUE #3610]♻️Convert HA system shutdown methods from sync to async
  rocketmq-broker/src/broker_runtime.rs
  rocketmq-store/src/base/message_store.rs
  rocketmq-store/src/ha/auto_switch/auto_switch_ha_service.rs
  rocketmq-store/src/ha/default_ha_service.rs
  rocketmq-store/src/ha/general_ha_client.rs
  rocketmq-store/src/ha/general_ha_service.rs
  rocketmq-store/src/ha/group_transfer_service.rs
  rocketmq-store/src/ha/ha_connection_state_notification_service.rs
  rocketmq-store/src/ha/ha_service.rs
  rocketmq-store/src/message_store/local_file_message_store.rs
Labels: refactor♻️, auto merge, ready to review, waiting-review, AI review first

#3614 [ISSUE #3613]♻️Clean up AckMessageProcessor - remove unused variables and lint suppressions
  rocketmq-broker/src/processor/ack_message_processor.rs
Labels: refactor♻️, auto merge, ready to review, waiting-review, AI review first

#3617 [ISSUE #3613]♻️Convert HA service is_slave_ok method from sync to async
  rocketmq-store/src/ha/auto_switch/auto_switch_ha_service.rs
  rocketmq-store/src/ha/default_ha_service.rs
  rocketmq-store/src/ha/general_ha_service.rs
  rocketmq-store/src/ha/ha_service.rs
  rocketmq-store/src/message_store/local_file_message_store.rs
Labels: refactor♻️, auto merge, ready to review, waiting-review, AI review first

#3621 changes typo on line 467 \rocketmq-rust\rocketmq-broker\src\broker_ru…
  rocketmq-broker/src/broker_runtime.rs
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first

#3623 [ISSUE #3622]Fix broken unimplemented! macro in recover_initialize_service function
  rocketmq-broker/src/broker_runtime.rs
Labels: bug🐛, auto merge, ready to review, waiting-review, AI review first

#3624 Potential fix for code scanning alert no. 7: Workflow does not contain permissions
  .github/workflows/sync-issue-labels.yml
Labels: auto merge, ready to review, waiting-review, AI review first

#3625 Potential fix for code scanning alert no. 2: Workflow does not contain permissions
  .github/workflows/auto_request_review.yml
Labels: auto merge, ready to review, waiting-review, AI review first

#3626 Potential fix for code scanning alert no. 6: Workflow does not contain permissions
  .github/workflows/codecov.yml
Labels: auto merge, ready to review, waiting-review, AI review first

#3631 [ISSUE #3620]♻️Enhance DefaultHAConnection with specialized I/O and OffsetDecoder
  rocketmq-store/src/ha/default_ha_connection.rs
Labels: refactor♻️, auto merge, ready to review, waiting-review, AI review first, performance, protocol

#3633 [ISSUE #3413]♻️Refactor UnregisterClientRequestHeader with derive marco RequestHeaderCodec
  rocketmq-remoting/src/protocol/header/unregister_client_request_header.rs
Labels: refactor♻️, auto merge, ready to review, waiting-review, AI review first, Difficulty level/Easy, rocketmq-remoting crate

#3634 [ISSUE #3409]♻️Refactor QueryTopicConsumeByWhoRequestHeader with derive marco RequestHeaderCodec
  rocketmq-remoting/src/protocol/header/query_topic_consume_by_who_request_header.rs
Labels: refactor♻️, auto merge, ready to review, waiting-review, AI review first, Difficulty level/Easy, rocketmq-remoting crate

#3636 [ISSUE #3635]🔨Update automerge.yml to trigger on pull_request instead of pull_request_target
  .github/workflows/automerge.yml
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first

#3642 [ISSUE #3641]🔨Remove codeql CI
  .github/workflows/codeql.yml
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first

#3644 [ISSUE #3643]Removed unnecessary code from DefaultHAService
  rocketmq-store/src/ha/default_ha_service.rs
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first, Difficulty level/Easy

#3646 Removed unnecessary code from ChangeInvisibleTimeProcessor
  rocketmq-broker/src/processor/change_invisible_time_processor.rs
Labels: enhancement⚡️, auto merge, ready to review, waiting-review, AI review first, Difficulty level/Easy

#3649 [ISSUE #3648]✨Implement atomic transfer notifications and HA service integration
  rocketmq-store/src/ha/default_ha_service.rs
  rocketmq-store/src/ha/group_transfer_service.rs
Labels: auto merge, ready to review, waiting-review, AI review first, ha-service, enhancement✨, concurrency
